### ISSUE TITLE
No Matter From Shaped Recipe Logging Errors 0.2.6.1

### ISSUE THREAD

**Issue by jsaggers** [simeonradivoev/MatterOverdrive#10]
A little bit of a bug report, Your latest version 0.2.6.1, delays the loading of my world by more than 10 minutes, actually I have to kill the instance via MultiMC, I had to clear the log file because it was getting to be 100's of MB's in size.

The fml-client-latest.log file is 461650 lines in length of just [com.MO.MatterOverdrive.handler.MatterRegistry:getMatterFromRecipe:220]

No matter from shaped recipe for: tile.solsBlock. (2)

No matter from shaped recipe for: item.blazePowder

No matter from shaped recipe for: tile.computercraft:advanced_turtle - has the most lines.

 

So I will have to revert to the previous version.

**Comment by simeonradivoev** [comment]
It has to do with my new Matter Calculation System. I works on a background thread, but I haven't tested it with a lot of mods.

**Comment by simeonradivoev** [comment]
I just tested it with a bunch of mods. I works fine. But I don't think the crash came from Matter Overdrive. As for the size of the log. I will have to remove the debug messages for the matter calculation.

**Comment by jsaggers** [comment]
The game isn't crashing, the pack loads fine, it takes a long time to launch the world when normally it would take about 20 seconds to load the save.
I have 176 mods.
I have changed a few computer craft recipes so they use Pneumaticraft tubes instead of redstone, would that be affecting it at all?

**Comment by simeonradivoev** [comment]
I have no idea. I will remove the massages that write to the log. And will see how that works out.

**Comment by simeonradivoev** [comment]
I tested it with a Direwolf20 pack and it calculated the recipe of 2345 items for 3.8 seconds. Hope it works with you as well.
