### ISSUE TITLE
MatterOverdrive and Adventure Backpacks (I think?)

### ISSUE THREAD

**Issue by sigmareaver** [simeonradivoev/MatterOverdrive#100]
I'm not really sure what this means, but I think it is a MatterOverdrive bug.
http://pastebin.com/jAa8SKba
This goes on for a long time in the log and I didn't copy the whole log because it was taking forever just to highlight the entire thing. Also, this doesn't crash my game. This happens when I am creating a new world. I do make it into the game OK (so far.)

Should I add Adventure Backpacks to matter registry blacklist?

**Comment by shadoxxhd** [comment]
it might be because of the various crafting recipes for the backpacks, but i'm not sure

**Comment by shadowfacts** [comment]
Can you reproduce this with the latest versions of all mods involved?

**Comment by shadowfacts** [comment]
1. 1.7.10 is no longer supported.
2. No response from reporter
