### ISSUE TITLE
Another crash starting minecraft :/

### ISSUE THREAD

**Issue by xXDerMCFreakXx** [simeonradivoev/MatterOverdrive#101]
hi guys i have another crash :/ here is the report: https://gist.github.com/xXDerMCFreakXx/c3e0e16c2607e78a1f52

**Comment by simeonradivoev** [comment]
What version of the mod do you use ?

**Comment by shadowfacts** [comment]
Do you have CoFHLib installed?

**Comment by xXDerMCFreakXx** [comment]
I have cofhlib and i have the version 0.4.0.b1 of matteroverdrive

**Comment by xXDerMCFreakXx** [comment]
But the computer havent a internet connection

**Comment by simeonradivoev** [comment]
try the latest hotfix version

**Comment by xXDerMCFreakXx** [comment]
I mean the version of matteroverdrive is 1.7.10-0.4.0-RC1

**Comment by xXDerMCFreakXx** [comment]
Did u mean with hotfix the version 0.2.4?

**Comment by xXDerMCFreakXx** [comment]
Or the 0.3.4.1 version?

**Comment by simeonradivoev** [comment]
the latest hotfix

**Comment by xXDerMCFreakXx** [comment]
What is that, a hotfix?

**Comment by simeonradivoev** [comment]
0.4.0-RC1 HOTFIX 3 http://minecraft.curseforge.com/mc-mods/229694-matter-overdrive/files

**Comment by xXDerMCFreakXx** [comment]
Thanks!
