### ISSUE TITLE
Resize Bug

### ISSUE THREAD

**Issue by MrVizzyTM** [simeonradivoev/MatterOverdrive#108]
1) Vanila ("up_arrow")
![2015-07-13_10 17 11](https://cloud.githubusercontent.com/assets/7906418/8643129/cfc79660-2948-11e5-87d5-ddec74146aff.png)
    Faithful like this ("up_arrow" It deviates from the center to the right and increased in size in minecraft)
![2015-07-13_10 17 22](https://cloud.githubusercontent.com/assets/7906418/8643149/162f890a-2949-11e5-8334-ea74fea320e5.png)
2) Vanila ("crosshair" and "heal")
![2015-07-13_10 25 18](https://cloud.githubusercontent.com/assets/7906418/8643188/afdb896e-2949-11e5-9c3e-9f9dec8b9020.png)
    Faithful ("crosshair" and "heal"  It deviates from the center to the right and increased in size in minecraft)
![2015-07-13_10 25 25](https://cloud.githubusercontent.com/assets/7906418/8643196/f5996304-2949-11e5-8cbe-93845975347f.png)
And this bug with all page button in gui. And because of this bug i can not do the normal Faithful textures and have to leave it like vanilla :(

**Comment by simeonradivoev** [comment]
Yes i automatically draw icons with their image size. So if the images have a bigger resolution they are drawn bigger.

**Comment by TheVizzy** [comment]
yes. I need to fix it)

**Comment by simeonradivoev** [comment]
Fixed in 0995925d7559f68ad74d54c3ad79a6bf5b9a45ea
