### ISSUE TITLE
How can i use star maps and ships? O_o

### ISSUE THREAD

**Issue by xXDerMCFreakXx** [simeonradivoev/MatterOverdrive#110]
Ive found a block called star map. It works fine but what are they doing? How can i use them???
I also found a items called like scout ship, ship factory, base and colony ship. How can i use them? Ive spend days to search videos about the star map. Also searching in the wiki... Can u help me? Are the items done or did they do nothing yet?

**Comment by xXDerMCFreakXx** [comment]
Forgot to say, my mo version is the latest hotfix

**Comment by simeonradivoev** [comment]
The Star Map is not done yet. The only thing you can do with it for now is to send ships from one planet to another. I will do a full wiki guide once the Star Map is complete or at least until i decide it's good enough.
