### ISSUE TITLE
Flyable ships!

### ISSUE THREAD

**Issue by xXDerMCFreakXx** [simeonradivoev/MatterOverdrive#111]
Hey guys! Can u add self-buildet-ships and space please? My idea is, that u can build a ship at any planet like haribote aircraft and launch it into the space! It would be awesome, if the ship could be maximum 10000 blocks big. The space need to be like galacticraft. Add also an communicator system, so when u add a transporter room to your ship, and press any button to open the communicator, choose the npc at the transporter room, click energy and u will be beamed back/away from the ship. Isnt that cool?!? Add also borg ships that attack you with lasers. That laser will destroy so many blocks that tier it is: when the blocks are tier 1, and the laser cannon tier 1, it will make a 5 x 5 hole in the ship. Add also a generator to be invisible like in the mod warp drive. Add a warp generator controller. It will shows like the fusion generator controller where the special blocks need to be placed. When the warp room its done, u can use the star map to say where the ship need to warp. BUT: it need to be possible, to be IN the ship and MOVE inside!!!!! the phaser controll room can be controlled like the transporting room and become an real captian with a real working ship! Please add that things!!! The mod will become 100% the best sience mod like flans mod the best gun mod!!!!!

**Comment by xXDerMCFreakXx** [comment]
If you, simon (or other admins), want more of my ideas, just tell it!

**Comment by xXDerMCFreakXx** [comment]
It would me awesome too, if u add a oxygen system so when the hole in the ship that the lasers created will run out of oxygen and npcs or players will just flush away in the space and will die because there is no oxygen! So the ship need to close that hole with strong blocks that hold the other amount of oxygen in the ship inside! If the ship dont close the hole? The ship explode or something like this. Add also OMG I HAVE TOO MANY IDEAS!!!! Add also please a emp laser so when the ship will be shooted from that emp laser, it cant use the energy inside and the matter inside! The only thing u can do is: walking and standing

**Comment by xXDerMCFreakXx** [comment]
Add please too that u can build an rescue capsule to you ship so if your ship will explode because of a overheating warp system (it will warn you with sounds and a messege in the chat like bla bla bla warp system is overheating bla bla bla. Or if evething is burning because of an laser then u can go to a rescue capsule, click a button and the rescue capsule will fly to the nearst planet/space station (u can choose when the rescue capsule is throwed off the ship) :D

**Comment by xXDerMCFreakXx** [comment]
Add please too an tractor beam (only for BIG ships that have an hangar). The tractor beam controller (everything big like invisible generator, Warp generator or phasers need an controller like the fusion reactor) will scan if the enemys ship is small enough for the hangar and if its run out of energy (or its attacket with emp) it will be beamed in the ship and cant go out anymore and the bigger ship can kill the crew of the smaller ship :D when the crew of the bigger ship has killed the crew of the smaller ship then can the crew of the bigger ship 1. Sell the ship for diamonds, etc. 2. Throw it out the hangar or own the smaller ship as an fighter and give it a pilot. And one thing for the communicator: when in multiplayer, the captain (builder) of the ship will choose the jobs (transporter man, security man, fighter etc.) and then when the players become the jobs, the captain need to pick up his communicater, go to settings, click add player, type in the player name, type in the job that the player have and done! PLEASEEEE ADD MY IDEAS

**Comment by xXDerMCFreakXx** [comment]
#Loooooongestideasofthewebside

**Comment by shadowfacts** [comment]
While your ideas would be quite fun to play with, the amount of work needed to create something on this large of a scale is enormous and is far out of scope for the abilities of two people. *If* this was not a Minecraft mod, but instead, it's own game, and *if* we had a full scale development team, then *maybe* something like this would be possible.

**Comment by simeonradivoev** [comment]
@shadowfacts Yes indeed :smiley:

**Comment by shadoxxhd** [comment]
@xXDerMCFreakXx 

> #Loooooongestideasofthewebside

nope. #299
