### ISSUE TITLE
Invalid Android loot drop

### ISSUE THREAD

**Issue by SylverSun** [simeonradivoev/MatterOverdrive#112]
Line 90 of EntityRougeAndroidMob.java causes Rogue Androids to sometimes drop an unusable Android Torso with the value 5011:4. I think.

**Comment by simeonradivoev** [comment]
The Random.int bound is exclusive. Have you tested it in game?

**Comment by SylverSun** [comment]
I have, though not on purpose. I've got an invalid android torso with the mentioned ID.

**Comment by simeonradivoev** [comment]
what version of the mod ?

**Comment by SylverSun** [comment]
0.3.4.1

**Comment by simeonradivoev** [comment]
ah, It's fixed in the newer versions.

**Comment by SylverSun** [comment]
Great, thanks anyway!
