### ISSUE TITLE
Star Map NPE Shift + Right Click

### ISSUE THREAD

**Issue by Master0r0** [simeonradivoev/MatterOverdrive#117]
When Shift and Right Clicking the Star Map I get an NPE that results in a crash

http://pastebin.com/nt8gD4FU

Also normal right clicking the Star Map does nothing however it throws the items in my inventory into random slots that are not really there creating ghost items, clicking on these items in these slots will also cause an array exception due to that item not actually existing there, this could be a bug with InvTweaks sorting

**Comment by simeonradivoev** [comment]
What version of the mod are you using ?

**Comment by Master0r0** [comment]
0.4.0 RC2

**Comment by simeonradivoev** [comment]
Can you copy the whole crash log, and try do delete galaxy.dat file from your world folder.

**Comment by Master0r0** [comment]
Deleting the galaxy.dat file actually fixed the issues, I assume it was down to having an older version of the galaxy.dat this is also seemed to have fixed the issue I was having with the Matter Scanner GUI
