### ISSUE TITLE
Forcing Java 8

### ISSUE THREAD

**Issue by Dyonovan** [simeonradivoev/MatterOverdrive#118]
I am just wondering why you are forcing Java 8. Many people are are still using Java 7.

**Comment by shadowfacts** [comment]
A portion of the new compatibility system depends on Java 8. We are also using lambdas, which were introduced in Java 8.

Additionally, Java 8 is only released version of Java that is supported by Oracle. Nobody should be using any prior version of Java. (If you have a computer that cannot run the latest version of Java, you should not be playing Minecraft with it (especially not modded), you should be working on fixing your computer).

If you use something else which requires Java 7 you can install multiple versions of Java and configure Minecraft to use Java 8.
