### ISSUE TITLE
Recipe's for Charging Station and Ship Factory

### ISSUE THREAD

**Issue by Master0r0** [simeonradivoev/MatterOverdrive#120]
Recipe's for these two blocks are missing but the blocks were mentioned in the latest changelog as being added to the game, does that mean fully added or you just added them for the future and they should not have recipe's yet?

**Comment by simeonradivoev** [comment]
The Charging Station is the only one implemented. The Star Map is still in development.

**Comment by Master0r0** [comment]
So you are saying there should be a recipe for the charging station? because there isn't, at least not one visible to NEI

**Comment by simeonradivoev** [comment]
there is no recipe of the charging station yet.
