### ISSUE TITLE
[Request][Mod Interaction] Method/Interface/API Hook to blacklist certain items from being fabricated

### ISSUE THREAD

**Issue by ReikaKalseki** [simeonradivoev/MatterOverdrive#121]
Mainly for balance reasons with mods like mine, where producing one unit of a material may be trivial but producing viable quantities is decidedly not.

**Comment by shadowfacts** [comment]
Closed in favor of #123

**Comment by shadowfacts** [comment]
@ReikaKalseki Until #123 is finished [MatterRegistry.addToBlacklist](https://github.com/simeonradivoev/MatterOverdrive/blob/master/src/main/java/matteroverdrive/handler/MatterRegistry.java#L131) can be used.

**Comment by ReikaKalseki** [comment]
Thank you. :)

**Comment by shadowfacts** [comment]
No problem
