### ISSUE TITLE
Server-side crash when placing Fusion Reactor Controller

### ISSUE THREAD

**Issue by Gideonseymour** [simeonradivoev/MatterOverdrive#13]
http://paste.feed-the-beast.com/view/30648b05
The crash occurred when I placed a Fusion Reactor Controller next to a Stabilized Gravitational Anomaly. Didn't occur on the client side

Somewhat unrelated: am I supposed to be able to right click on the Reactor Controller to access the GUI?

**Comment by simeonradivoev** [comment]
You can access the gui once the Reactor Controller has a valid structure.
