### ISSUE TITLE
Null Pointer Exception when opening GUI of Scanner in version 0.3.5.

### ISSUE THREAD

**Issue by Nimmo** [simeonradivoev/MatterOverdrive#131]
http://paste.ee/p/04kxj

I've repeated this bug, any time I try to open my matter scanner I crash to desktop.

**Comment by shadowfacts** [comment]
What version of Matter Overdrive are you using?

**Comment by Nimmo** [comment]
Sorry, I'd stated it in the title as 0.3.5, but not in the post.

I've just realised I'm running Java 7, so I've updated that to 8 and decided to experiment with the 4.0 RC2 to see if that resolves the issue.
