### ISSUE TITLE
Replicator : Item Extrcation does not work from the Top

### ISSUE THREAD

**Issue by 6210classick** [simeonradivoev/MatterOverdrive#133]
the replicated items can be extracted from all sides except the top

MO 0.4.0-RC2
Ender IO 2.2.8 v381
Extrau Utilities v1.2.8
Forge 1490

i tried both XU Transfer/Retrieval Node & EIO Item conduit and it didn't work from the top

**Comment by simeonradivoev** [comment]
The top side is reserved for the Matter Scanner. But now that the matter scanner does nothing in the replicator. I might change the topside to be output as well.
