### ISSUE TITLE
Pattern Monitor not accetping any portable power source

### ISSUE THREAD

**Issue by 6210classick** [simeonradivoev/MatterOverdrive#134]
portable RF power Source like EIO Banks , Creative battery .. etc cannot be inserted in the Energy slot like other machines

MO v0.4.0-RC2

also is it possible to either remove the power requirement for the Pattern Monitor or add an option on the config file to disable it , it ruins the the look of the Matter System because the Pattern Monitor is not a full block

**Comment by simeonradivoev** [comment]
The Pattern monitor does not need power for anything. It can function without power.

**Comment by 6210classick** [comment]
then why does it shows that it needs 512 RF in Waila tool tips ? and whats the lighting slot for ?

**Comment by simeonradivoev** [comment]
It contains energy, but it's not used for anything right now.
