### ISSUE TITLE
Matter value doesn't care about metadata

### ISSUE THREAD

**Issue by medsal15** [simeonradivoev/MatterOverdrive#138]
If 2 things have the same metadata but not the same recipe (like in Mariculture) the same matter value will be given to both. This value is based on the recipe of the X:0 only.

**Comment by simeonradivoev** [comment]
That's not entirely true. Matter Overdrive stores Matter values based on the unlocalized name of an item. Most items with the same id and different metadata have unique unlocalized names, but apparently some have the same names.

**Comment by simeonradivoev** [comment]
Fixed in 949399b7e42df50d346fc94a710560b72f2a119b
