### ISSUE TITLE
Cross Compatibility Bug with EnderIO

### ISSUE THREAD

**Issue by NullMagic** [simeonradivoev/MatterOverdrive#143]
The good news is, I finally solved that bug, apparently having Matter Overdrive and EnderIO (and sophisticated wolves, but we won't go into that) in the same pack causes all kinds of weirdness, that seems off topic, but it's not I promise. 

EnderIO, when installed client side (and only client side, there's no crashing unless a client is connecting to a server with Matter Overdrive and servers with both don't ever crash because of the two interacting nor does a person in a single player world), causes the client to crash with this error: http://pastebin.com/uCNC5NuH whenever a Scientist is in the area.

I have no idea why, or how, I've already reported it to the peeps over at EnderIO (https://github.com/SleepyTrousers/EnderIO/issues/2687).

All the above said, we'd like to keep both mods, and the quickest and easiest way to solve this problem would be to just turn off Scientists, except they don't have a config for turning them off, for that matter Androids don't either (though you can set their spawning to 0 which I think does it).

Another issue that cropped up a little bit ago was when two mods wanted to have the same ID for one of their mobs (Matter Overdrive and Atum), which I unfortunately couldn't fix because neither mod allows the IDs of it's mobs to be changed, so I'd like to further suggest the ability to change the ID of both the android and the scientist.

**Comment by simeonradivoev** [comment]
The id of the Scientist and the Android is automatically assigned, by getting the first available ID. I't the same way Minecraft does it. So the problem is then an ID is manually assigned. That makes conflicts.

**Comment by simeonradivoev** [comment]
You crash is the same as #137.

**Comment by simeonradivoev** [comment]
Are you saying that you have EnderIO only on your client and not your server ?

**Comment by shadowfacts** [comment]
> Well - having EnderIO installed only on one side (server or client) is not supported.

1. That's not supported by any mods other than explicitly client-only ones.
2. Does this happen when MO and EIO are on both the server and the client?
3. Does this only happen on a dedicated server?

**Comment by NullMagic** [comment]
1. I did not mean to imply that we have it only on the client side, though I can see how my wording could have sounded that way, that said many packs on, I believe it's the AT launcher? Allow for the downloading of other mods for personal use even if they're not on the pack's official launcher, though that is NOT the case here, we have EnderIO on both the client and server, the emphasis I was making was that it doesn't crash the client in single player, or a running server, but only a client connecting to the server.

2. Yes, it happens when both MO and EIO are on both the server and client.

3. Yes.

4. It is the same crash, and I'm sorry it ended up in two places, honestly I'm sorry it's even a thing, I'm also sorry that I'm probably giving you whiplash over this since I came back to you with it so fast.

**Comment by b0bst3r** [comment]
You'd have to try this without Cauldron as it may be their issue.

**Comment by NullMagic** [comment]
Alright, we found the problem. It turns out we DID have a mod installed on only the client and not the server (By accident, I assure you), though it didn't show up in any of the crash logs as being active, so that might be why I missed it. Removing the mod fixed everything.

I now feel horribly stupid and am going to go gibber quietly to myself in a corner.

**Comment by simeonradivoev** [comment]
No worries
