### ISSUE TITLE
Rogue Android dimension blacklist not working

### ISSUE THREAD

**Issue by Crumbology** [simeonradivoev/MatterOverdrive#145]
Even on default settings Hell/Sky both those dimensions are still getting Android spawns, they pretty much outnumber Endermen in the End.

**Comment by medsal15** [comment]
Wait, they aren't supposed to spawn in the nether?

**Comment by Crumbology** [comment]
Hell is automatically blacklisted in the configs, but the config isn't working, so no, they aren't supposed to by default.

**Comment by simeonradivoev** [comment]
Also it's not a dimension blacklist, but a biome blacklist.
