### ISSUE TITLE
Matter storage upgrade

### ISSUE THREAD

**Issue by dominx** [simeonradivoev/MatterOverdrive#146]
Upgrade enlarging amount of kM would be nice. There are two reasons: being able to decompose and replicate item having more than 1024kM and speedup in crafting item having large kM value. I'm replicating nether stars and it not only takes ages to produce but it also takes long to fill the replicator back up and replication won't start unless the replicator is full.

Another way to solve this issues would be to produce/consume kM gradually during the process not just at the completion.

**Comment by simeonradivoev** [comment]
Added in b91a756c4986d0f4c1c693333e3d961059fb5bb9
