### ISSUE TITLE
Ticking on Server

### ISSUE THREAD

**Issue by DoughnutDev** [simeonradivoev/MatterOverdrive#149]
MatterOverdrive Version:
MatterOverdrive-1.7.10-0.4.0-RC2.jar

MinecraftForge Version:
10.13.4.1492

SSP or SMP? (Client or Server):
Server

Crash Report (via. Pastebin):
http://pastebin.com/SerYJ8E7

What happens / happened?:
Sitting on the server I get this crash. There is also a bug were I think that your anomaly are crashing servers with falling sand. If you would like I can post that too.

**Comment by simeonradivoev** [comment]
hmm a null building. How did that happen :laughing:

**Comment by simeonradivoev** [comment]
When did the crash happen. Did the crash happen the first time you started your server or the second time? Did it happen while doing nothing or were you playing with the starmap?

**Comment by shadowfacts** [comment]
> Sitting on the server I get this crash. There is also a bug were I think that your anomaly are crashing servers with falling sand. If you would like I can post that too.

Could you please create another issue for this?

**Comment by DoughnutDev** [comment]
This crash is the second one. The falling sand one seemed to have left but
still sometimes happens

**Comment by simeonradivoev** [comment]
You can try to delete the galaxy file. As for the falling sand bug. Please post it as another issue.
