### ISSUE TITLE
A few issues

### ISSUE THREAD

**Issue by DestinyPlayer** [simeonradivoev/MatterOverdrive#15]
First, a vanilla bug.
If you try to scan a plant (growing wheat, for example) with a Scanner, it crashes the game.

Second, a not-so vanilla bug.
If you try to decompose compressed cobblestone from Extra Utilities, it crashes the game.

**Comment by simeonradivoev** [comment]
maybe a crash log ?

**Comment by DestinyPlayer** [comment]
Oh, sorry, totally forgot about that.
http://pastebin.com/54rZ2WRe - This is the plant problem.
http://pastebin.com/3TxP7LpB - This is the "Compressed Cobblestone" problem.
