### ISSUE TITLE
Crash with Falling Sand

### ISSUE THREAD

**Issue by DoughnutDev** [simeonradivoev/MatterOverdrive#150]
MatterOverdrive Version:
MatterOverdrive-1.7.10-0.4.0-RC2.jar

MinecraftForge Version:
10.13.4.1492

SSP or SMP? (Client or Server):
Server

Crash Report (via. Pastebin):
http://pastebin.com/KZGpXWr7

What happens / happened?:
There is a bug were I think that your anomaly are crashing servers with falling sand. I am not sure if this is your mod or BOP but the BOP devs won't message me back so you are my last resort because it started happening after MO was added.

**Comment by DoughnutDev** [comment]
http://pastebin.com/E68MzDU5

**Comment by DoughnutDev** [comment]
Now that person that was in that chunk gets "Connection was forcibly closed by the remote host"

**Comment by simeonradivoev** [comment]
It's a biomes o plenty bug.
