### ISSUE TITLE
Not a Bug - Need to ask a question

### ISSUE THREAD

**Issue by DoughnutDev** [simeonradivoev/MatterOverdrive#154]
Are your androids using the playerAPI so if so you should change it so they do not load chunks, because we started a new server and we do not have chunk loaders but the farms were fully grown and the only thing I can think of doing this is the Androids because they walk around and there are a few mods that do this. If it is possible could you please either change it or make it a config option.

**Comment by simeonradivoev** [comment]
No. Androids do not use playerAPI they are just normal mobs with vanilla behavior.

**Comment by DoughnutDev** [comment]
Okay thank you.
