### ISSUE TITLE
Fusion Reactor issue

### ISSUE THREAD

**Issue by DestinyPlayer** [simeonradivoev/MatterOverdrive#16]
That one is pretty simple. The Fusion Reactor doesn't appear to work with Chuck Loaders. At the very least, Chicken Chuck Loaders. It simply doesn't generate/output any energy.
Also could be due to the fact that it's placed in a different dimension, but it still should work with a chunk loader.

**Comment by simeonradivoev** [comment]
I just tried it in the overworld with chunk loaders and it works fine. Are you putting in in mystraft dimension or what ? Also it needs Matter to run.

**Comment by DestinyPlayer** [comment]
Yes, it is placed in a Mystcraft dimension. And it has matter, an automated generator of matter, in fact, by using Igneous Extruders feeding cobble into about four decomposers.
