### ISSUE TITLE
Android sprinting produces rapid energy drain

### ISSUE THREAD

**Issue by atomiccheese** [simeonradivoev/MatterOverdrive#161]
When I'm an android with a ThermalExpansion RF battery installed, after sprinting for a second or so my power level starts draining rapidly (multiple % per second). This happens with all types of batteries, Leadstone through Resonant.

**Comment by john156** [comment]
:+1:

**Comment by simeonradivoev** [comment]
what abilities do you have unlocked and does that happen with MatterOverdrive batteries ?

**Comment by atomiccheese** [comment]
I didn't have any abilities, and I can't reproduce it even with TE batteries now. I'm not sure what happened, but I'll close the issue until I can reliably reproduce it in a test world.
