### ISSUE TITLE
i found a bag

### ISSUE THREAD

**Issue by Maks2103** [simeonradivoev/MatterOverdrive#164]
I downloaded and installed version 0.4.0 but can't find Phaser Rifle, network flash device & energy pack

**Comment by simeonradivoev** [comment]
it's not out yet. It will be in the 0.4.0 RC3

**Comment by Maks2103** [comment]
when released 0.4.0 RC3?

**Comment by simeonradivoev** [comment]
Soon hopefully. If you can't wait just head over to the Jenkins builds and you can get the newest builds http://ci.rx14.co.uk/job/shadowfacts/job/MatterOverdrive/
