### ISSUE TITLE
i found a bug

### ISSUE THREAD

**Issue by Maks2103** [simeonradivoev/MatterOverdrive#166]
installed the mod Galacticraft, and in the mode of Android to be on other planets without oxygen equipment is still not possible

**Comment by simeonradivoev** [comment]
Yes this is a know bag.

**Comment by Maks2103** [comment]
is it possible to fix this bug, and in which version it will be removed

**Comment by shadowfacts** [comment]
8a922b4018c88151de80a65695d3deb2d05118d0
