### ISSUE TITLE
Game crashes on GUI opening

### ISSUE THREAD

**Issue by Nodore** [simeonradivoev/MatterOverdrive#17]
I know I already posted this on the other page but now that I've found the issues page I figured I should post it again and go into more detail. The game crashes whenever I open the pattern monitor, the matter scanner gui (although that one may be fixed), the tasks screen on most of the machines' guis, and the matter analyzer. Sometimes, with some mod combination, instead of crashing the entire game it just says disconnecting from server. Also most of the color modules for the phasers don't render and just appear black. I tried using CofhLib and CofhCore but neither seem to fix it. I love this mod but I can't really use it.

Here's the latest crash report:
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 6/3/15 9:45 AM
Description: Rendering screen

java.lang.NoSuchMethodError: com.MO.MatterOverdrive.gui.element.ElementGrid.drawStencil(IIIII)V
	at com.MO.MatterOverdrive.gui.element.ElementGrid.drawBackground(ElementGrid.java:81)
	at com.MO.MatterOverdrive.gui.element.ElementBaseGroup.drawBackground(ElementBaseGroup.java:67)
	at cofh.lib.gui.GuiBase.drawElements(GuiBase.java:285)
	at com.MO.MatterOverdrive.gui.MOGuiBase.func_146976_a(MOGuiBase.java:70)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(bex.java:76)
	at cofh.lib.gui.GuiBase.func_73863_a(GuiBase.java:88)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:989)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.MO.MatterOverdrive.gui.element.ElementGrid.drawBackground(ElementGrid.java:81)
	at com.MO.MatterOverdrive.gui.element.ElementBaseGroup.drawBackground(ElementBaseGroup.java:67)
	at cofh.lib.gui.GuiBase.drawElements(GuiBase.java:285)
	at com.MO.MatterOverdrive.gui.MOGuiBase.func_146976_a(MOGuiBase.java:70)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(bex.java:76)
	at cofh.lib.gui.GuiBase.func_73863_a(GuiBase.java:88)

-- Screen render details --
Details:
	Screen name: com.MO.MatterOverdrive.gui.GuiPatternMonitor
	Mouse location: Scaled: (341, 176). Absolute: (683, 353)
	Screen size: Scaled: (683, 353). Absolute: (1366, 706). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityClientPlayerMP['Nodore'/971, l='MpServer', x=-1666.50, y=5.62, z=622.50], MCH_ViewEntityDummy['McHeliDummyEntity'/2614, l='MpServer', x=-1665.50, y=6.62, z=625.50]]
	Chunk stats: MultiplayerChunkCache: 361, 361
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-1666,4,625), Chunk: (at 14,0,1 in -105,39; contains blocks -1680,0,624 to -1665,255,639), Region: (-4,1; contains chunks -128,32 to -97,63, blocks -2048,0,512 to -1537,255,1023)
	Level time: 821 game time, 821 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 145 total; [EntitySalvadorii['Crocodile Monitor'/71257, l='MpServer', x=-1729.84, y=4.00, z=683.44], EntitySlime['Slime'/105981, l='MpServer', x=-1631.00, y=4.50, z=611.11], EntitySalvadorii['Crocodile Monitor'/71256, l='MpServer', x=-1732.44, y=4.00, z=678.16], EntitySavanna['Savanna'/71258, l='MpServer', x=-1731.63, y=4.00, z=677.09], EntitySavanna['Savanna'/71261, l='MpServer', x=-1731.06, y=4.00, z=682.50], EntityZebra['Zebra'/71249, l='MpServer', x=-1597.91, y=4.00, z=602.41], EntityDryad['Dryad'/71251, l='MpServer', x=-1729.50, y=4.00, z=667.94], EntityDryad['Dryad'/71250, l='MpServer', x=-1729.50, y=4.00, z=669.16], EntityDryad['Dryad'/71253, l='MpServer', x=-1730.50, y=4.00, z=671.50], EntitySalvadorii['Crocodile Monitor'/71254, l='MpServer', x=-1729.80, y=4.00, z=680.60], EntityRabbit['Rabbit'/71240, l='MpServer', x=-1600.56, y=4.50, z=593.93], EntityRabbit['Rabbit'/71241, l='MpServer', x=-1601.34, y=4.00, z=595.66], EntityRhino['Rhino'/71242, l='MpServer', x=-1605.23, y=4.00, z=599.00], EntityRhino['Rhino'/71243, l='MpServer', x=-1596.16, y=4.00, z=592.25], EntityRhino['Rhino'/71244, l='MpServer', x=-1594.50, y=4.00, z=599.50], EntityClientPlayerMP['Nodore'/971, l='MpServer', x=-1666.50, y=5.62, z=622.50], EntityRhino['Rhino'/71245, l='MpServer', x=-1596.97, y=4.00, z=599.59], EntityZebra['Zebra'/71246, l='MpServer', x=-1597.75, y=4.00, z=604.72], EntityZebra['Zebra'/71247, l='MpServer', x=-1609.75, y=4.00, z=602.91], EntityRabbit['Rabbit'/71238, l='MpServer', x=-1600.71, y=4.00, z=597.05], EntityRabbit['Rabbit'/71239, l='MpServer', x=-1599.28, y=4.08, z=595.33], EntityPerentie['Perentie'/71289, l='MpServer', x=-1708.22, y=4.00, z=698.00], EntityPerentie['Perentie'/71288, l='MpServer', x=-1698.50, y=4.00, z=694.50], EntityRhino['Rhino'/71295, l='MpServer', x=-1703.84, y=4.00, z=707.66], EntityRhino['Rhino'/71294, l='MpServer', x=-1709.25, y=4.00, z=699.88], EntityLace['Lace'/71283, l='MpServer', x=-1621.25, y=4.00, z=606.31], EntityRhino['Rhino'/71281, l='MpServer', x=-1611.07, y=4.00, z=605.70], EntitySlime['Slime'/123611, l='MpServer', x=-1700.59, y=4.47, z=692.61], EntityPerentie['Perentie'/71287, l='MpServer', x=-1710.38, y=4.00, z=692.72], EntityPerentie['Perentie'/71286, l='MpServer', x=-1707.03, y=4.00, z=698.78], EntityLace['Lace'/71285, l='MpServer', x=-1624.31, y=4.00, z=606.41], EntityCow['Cow'/71274, l='MpServer', x=-1630.91, y=4.00, z=595.06], EntityBeetleBS['Small Beetle'/1866, l='MpServer', x=-1742.41, y=4.00, z=577.22], EntityCow['Cow'/71275, l='MpServer', x=-1622.19, y=4.00, z=597.44], EntityRhino['Rhino'/71278, l='MpServer', x=-1624.08, y=4.00, z=599.01], EntityRhino['Rhino'/71279, l='MpServer', x=-1625.27, y=4.00, z=596.65], EntityCow['Cow'/71276, l='MpServer', x=-1620.50, y=4.00, z=595.50], EntityCow['Cow'/71277, l='MpServer', x=-1617.50, y=4.00, z=594.50], EntitySlime['Slime'/122494, l='MpServer', x=-1715.61, y=4.39, z=657.00], EntityYellowFinch['Yellow Finch'/1856, l='MpServer', x=-1570.58, y=17.49, z=569.26], EntityChameleon['Chameleon'/71193, l='MpServer', x=-1587.50, y=4.00, z=641.50], EntitySlime['Slime'/5437, l='MpServer', x=-1736.90, y=4.00, z=552.72], EntitySlime['Slime'/125476, l='MpServer', x=-1713.19, y=4.00, z=547.79], EntityLace['Lace'/71184, l='MpServer', x=-1741.50, y=4.00, z=669.50], EntityLace['Lace'/71186, l='MpServer', x=-1743.50, y=4.00, z=672.50], EntityLace['Lace'/71183, l='MpServer', x=-1735.78, y=4.00, z=676.28], EntityItem['item.item.muttonraw'/96544, l='MpServer', x=-1710.47, y=4.13, z=610.44], EntityLace['Lace'/71179, l='MpServer', x=-1746.50, y=4.00, z=669.50], EntitySlime['Slime'/143384, l='MpServer', x=-1625.60, y=4.00, z=666.40], EntityGreenFinch['Green Finch'/1282, l='MpServer', x=-1570.69, y=6.11, z=599.54], EntitySlime['Slime'/145250, l='MpServer', x=-1717.50, y=4.00, z=662.50], EntitySlime['Slime'/124973, l='MpServer', x=-1662.78, y=4.00, z=592.78], EntityLace['Lace'/71226, l='MpServer', x=-1725.22, y=4.00, z=680.36], EntitySlime['Slime'/140632, l='MpServer', x=-1726.21, y=4.50, z=678.90], EntityLace['Lace'/71223, l='MpServer', x=-1722.50, y=4.00, z=673.50], EntityItem['item.tile.cloth.white'/96543, l='MpServer', x=-1710.38, y=4.13, z=611.00], EntityLace['Lace'/71221, l='MpServer', x=-1725.88, y=4.00, z=676.56], EntityLace['Lace'/71220, l='MpServer', x=-1728.50, y=4.00, z=674.50], EntityOstrich['Ostrich'/71219, l='MpServer', x=-1731.02, y=4.00, z=679.72], EntityOstrich['Ostrich'/71218, l='MpServer', x=-1731.81, y=4.00, z=681.31], EntitySlime['Slime'/40087, l='MpServer', x=-1732.33, y=4.10, z=546.24], EntityOstrich['Ostrich'/71217, l='MpServer', x=-1729.44, y=4.00, z=682.06], EntitySlime['Slime'/140901, l='MpServer', x=-1712.11, y=4.00, z=641.77], EntityOstrich['Ostrich'/71216, l='MpServer', x=-1728.66, y=4.00, z=677.66], EntityZebra['Zebra'/71214, l='MpServer', x=-1583.84, y=4.00, z=644.69], EntityZebra['Zebra'/71210, l='MpServer', x=-1594.11, y=4.00, z=647.65], EntityZebra['Zebra'/71208, l='MpServer', x=-1584.50, y=4.00, z=642.50], EntityCrow['Crow'/1562, l='MpServer', x=-1574.54, y=12.10, z=666.02], EntityOstrich['Ostrich'/71204, l='MpServer', x=-1588.47, y=4.00, z=628.25], EntityOstrich['Ostrich'/71205, l='MpServer', x=-1597.53, y=4.00, z=638.57], EntityOstrich['Ostrich'/71202, l='MpServer', x=-1589.59, y=4.00, z=637.56], EntityOstrich['Ostrich'/71203, l='MpServer', x=-1590.50, y=4.00, z=634.50], EntityCow['Cow'/71141, l='MpServer', x=-1738.25, y=4.00, z=665.69], MCH_ViewEntityDummy['McHeliDummyEntity'/2614, l='MpServer', x=-1665.50, y=6.62, z=625.50], EntityGreenFinch['Green Finch'/2064, l='MpServer', x=-1747.26, y=7.66, z=624.48], EntityRabbit['Rabbit'/71140, l='MpServer', x=-1674.16, y=4.00, z=535.02], EntityCow['Cow'/71142, l='MpServer', x=-1746.50, y=4.00, z=664.50], EntityRabbit['Rabbit'/71137, l='MpServer', x=-1669.97, y=4.00, z=543.25], EntityRabbit['Rabbit'/71139, l='MpServer', x=-1674.88, y=4.00, z=544.91], EntityRabbit['Rabbit'/71138, l='MpServer', x=-1669.72, y=4.00, z=539.00], EntitySlime['Slime'/63982, l='MpServer', x=-1720.66, y=4.47, z=545.67], EntityBlueFinch['Blue Finch'/2045, l='MpServer', x=-1665.81, y=5.49, z=510.49], EntitySlime['Slime'/105541, l='MpServer', x=-1614.67, y=4.08, z=648.88], EntityBeetleBS['Small Beetle'/1525, l='MpServer', x=-1667.56, y=4.00, z=556.60], EntityChameleon['Chameleon'/71110, l='MpServer', x=-1746.94, y=4.00, z=613.03], EntityChameleon['Chameleon'/71109, l='MpServer', x=-1746.41, y=4.00, z=611.59], EntityBeetleBS['Small Beetle'/1252, l='MpServer', x=-1662.69, y=4.00, z=736.25], EntityIguana['Iguana'/71108, l='MpServer', x=-1735.44, y=4.00, z=623.31], EntityIguana['Iguana'/71106, l='MpServer', x=-1745.13, y=4.00, z=617.03], EntitySlime['Slime'/83785, l='MpServer', x=-1625.15, y=4.09, z=600.79], EntityIguana['Iguana'/71105, l='MpServer', x=-1744.41, y=4.00, z=615.69], EntitySlime['Slime'/23768, l='MpServer', x=-1722.72, y=4.87, z=545.26], EntityGreenFinch['Green Finch'/2008, l='MpServer', x=-1705.68, y=6.99, z=671.06], EntityYellowFinch['Yellow Finch'/1530, l='MpServer', x=-1734.55, y=7.13, z=600.51], EntityGreenFinch['Green Finch'/1504, l='MpServer', x=-1669.11, y=10.27, z=583.21], EntityCrow['Crow'/1275, l='MpServer', x=-1607.45, y=11.31, z=590.60], EntitySlime['Slime'/35601, l='MpServer', x=-1601.27, y=4.00, z=607.87], EntityKomodo['Komodo'/71073, l='MpServer', x=-1713.38, y=4.00, z=611.75], EntitySlime['Slime'/107981, l='MpServer', x=-1729.42, y=4.00, z=636.22], EntityKomodo['Komodo'/71072, l='MpServer', x=-1707.76, y=4.09, z=617.98], EntityKomodo['Komodo'/71075, l='MpServer', x=-1718.50, y=4.00, z=599.50], EntityKomodo['Komodo'/71074, l='MpServer', x=-1717.50, y=4.00, z=603.50], EntityRhino['Rhino'/71077, l='MpServer', x=-1713.25, y=4.00, z=599.91], EntityRhino['Rhino'/71076, l='MpServer', x=-1705.85, y=4.00, z=612.70], EntitySlime['Slime'/70605, l='MpServer', x=-1639.80, y=4.50, z=665.58], EntityRhino['Rhino'/71079, l='MpServer', x=-1700.50, y=4.00, z=607.50], EntityCrow['Crow'/1158, l='MpServer', x=-1659.34, y=18.26, z=588.03], EntityRhino['Rhino'/71078, l='MpServer', x=-1707.09, y=4.00, z=602.78], EntityCrow['Crow'/1160, l='MpServer', x=-1648.66, y=16.24, z=555.55], EntityRabbit['Rabbit'/71080, l='MpServer', x=-1683.16, y=4.00, z=698.14], EntityRabbit['Rabbit'/71083, l='MpServer', x=-1682.65, y=4.00, z=701.01], EntityRabbit['Rabbit'/71082, l='MpServer', x=-1681.78, y=4.00, z=694.00], EntityRabbit['Rabbit'/71301, l='MpServer', x=-1732.06, y=4.00, z=582.24], EntityIguana['Iguana'/71088, l='MpServer', x=-1689.13, y=4.00, z=697.88], EntityRabbit['Rabbit'/71300, l='MpServer', x=-1728.34, y=4.00, z=585.13], EntityYellowFinch['Yellow Finch'/1169, l='MpServer', x=-1766.67, y=11.21, z=594.17], EntityYellowFinch['Yellow Finch'/2117, l='MpServer', x=-1783.36, y=9.80, z=651.29], EntityIguana['Iguana'/71089, l='MpServer', x=-1689.50, y=4.00, z=701.50], EntityIguana['Iguana'/71090, l='MpServer', x=-1693.50, y=4.00, z=701.50], EntityIguana['Iguana'/71091, l='MpServer', x=-1690.91, y=4.00, z=696.09], EntitySlime['Slime'/69178, l='MpServer', x=-1602.82, y=4.00, z=547.02], EntityRhino['Rhino'/71296, l='MpServer', x=-1703.06, y=4.00, z=699.31], EntityRabbit['Rabbit'/71299, l='MpServer', x=-1732.78, y=4.00, z=581.78], EntityRabbit['Rabbit'/71298, l='MpServer', x=-1730.63, y=4.00, z=583.13], EntityKomodo['Komodo'/71309, l='MpServer', x=-1733.56, y=4.00, z=585.56], EntityKomodo['Komodo'/71308, l='MpServer', x=-1732.72, y=4.00, z=584.88], EntityKomodo['Komodo'/71307, l='MpServer', x=-1731.38, y=4.00, z=584.88], EntityKomodo['Komodo'/71306, l='MpServer', x=-1729.44, y=4.00, z=584.56], EntityBlueFinch['Blue Finch'/1184, l='MpServer', x=-1766.57, y=4.29, z=643.19], EntityRabbit['Rabbit'/71051, l='MpServer', x=-1748.56, y=4.23, z=504.57], EntityRabbit['Rabbit'/71049, l='MpServer', x=-1749.50, y=4.00, z=505.50], EntityRabbit['Rabbit'/71048, l='MpServer', x=-1752.72, y=4.00, z=504.53], EntityRhino['Rhino'/71058, l='MpServer', x=-1572.91, y=4.00, z=582.84], EntityRhino['Rhino'/71056, l='MpServer', x=-1570.91, y=4.00, z=586.44], EntityRhino['Rhino'/71057, l='MpServer', x=-1571.63, y=4.00, z=580.53], EntityRhino['Rhino'/71066, l='MpServer', x=-1568.31, y=4.00, z=588.44], EntitySlime['Slime'/47074, l='MpServer', x=-1744.18, y=4.27, z=634.66], EntityRhino['Rhino'/71067, l='MpServer', x=-1566.13, y=4.00, z=588.25], EntityRhino['Rhino'/71064, l='MpServer', x=-1566.13, y=4.00, z=593.95], EntitySlime['Slime'/67214, l='MpServer', x=-1682.53, y=4.47, z=600.40], EntityRhino['Rhino'/71065, l='MpServer', x=-1570.88, y=4.00, z=591.72], EntityTrail['unknown'/2911, l='MpServer', x=-1666.50, y=5.62, z=622.50], EntitySheep['Sheep'/71071, l='MpServer', x=-1703.50, y=4.00, z=611.50], EntitySheep['Sheep'/71068, l='MpServer', x=-1709.45, y=4.00, z=619.13], EntitySheep['Sheep'/71069, l='MpServer', x=-1713.69, y=4.00, z=609.31]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:909)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.7.0_71, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 398652320 bytes (380 MB) / 919298048 bytes (876 MB) up to 1037959168 bytes (989 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.113.1380 Minecraft Forge 10.13.3.1380 48 mods loaded, 48 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	FML{7.10.113.1380} [Forge Mod Loader] (forge-1.7.10-10.13.3.1380-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Forge{10.13.3.1380} [Minecraft Forge] (forge-1.7.10-10.13.3.1380-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	AM2-Preloader{0.0.2} [AMCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	ivtoolkit{IvToolkit} [1.2] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	TooManyItems{1.7.10} [TooManyItems] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	sapmanpack{2.1.0} [SanAndreasPs Manager Pack CORE edition] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	arsmagica2{1.4.0.008} [Ars Magica 2] (1.7.10_AM2-1.4.0.008.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	CraftableAnimals{2.4.3.0} [Craftable Animals] ([1.7.10]CraftableAnimals v2.4.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	DamageIndicatorsMod{3.2.0} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	lightsabers{0.7.1} [Advanced Lightsabers Mod] (AdvancedLightsabers-1.7.10-0.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	koresample{1.7.10-1.2.5} [Kore Sample] (KoreSample-1.7.10-1.2.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	dendrology{1.7.10-1.3.1} [Ancient Trees] (AncientTrees-1.7.10-1.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	antiqueatlas{4.2.1-1.7.10} [Antique Atlas] (antiqueatlas-4.2.1-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	BiblioCraft{1.10.2} [BiblioCraft] (BiblioCraft[v1.10.2][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	claysoldiers{2.0.0b} [Clay Soldiers Mod] (ClaySoldiersMod-1.7.10-2.0.0b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	clonecraft{3.0} [CloneCraft] (CloneCraft-vB3.0 - MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	CoFHCore{1.7.10R3.0.0B9} [CoFH Core] (CoFHCore-[1.7.10]3.0.0B9-40.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	craftguide{1.6.8.1} [CraftGuide] (CraftGuide-1.6.8.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	DragonMounts{r41-1.7.10} [Dragon Mounts] (DragonMounts-r41-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	grim3212core{V0.2 - 1.7.10} [Grim3212 Core] (Grim3212 Core-V0.2 - 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	extinguisher{V0.1 - 1.7.10} [Extinguisher] (Extinguisher-V0.1 - 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	fossil{1.7.10 Build 7.1.0} [Fossils and Archeology Revival] (Fossils_Archeology_Revival-1.7.10_Build-7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	GraviGun{4.0.0-beta} [GraviGun] (GravityGun-4.0.0-beta.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	headcrumbs{1.5.3} [Headcrumbs] (Headcrumbs-1.5.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	herobrinemod{3.7} [The Herobrine Mod] (Herobrinemod1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	3DDCore{0.0.1} [3DDCore] (HPWands-1.7.10-0.0.2 Beta.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	HPWands{0.0.2 Beta} [Harry Potter Wands] (HPWands-1.7.10-0.0.2 Beta.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	TimberPlus{0.1.4 Beta} [Timber+] (HPWands-1.7.10-0.0.2 Beta.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	InventoryPets{1.1.2a} [Inventory Pets] (inventorypets-1.7.10-1.1.2a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	jcanimation{1.2.4-JC} [JCAnimationAPI] (JurassiCraft-1.4.0-build-165.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	jurassicraft{1.4.0-build-165} [JurassiCraft] (JurassiCraft-1.4.0-build-165.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	mo{0.3} [Matter Overdrive] (MatterOverdrive-0.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	mcheli{0.10.6} [MC Helicopter] (mcheli) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	millenaire{6.0.0} [MillÃ©naire] (millenaire-6.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Morph{0.9.1} [Morph] (Morph-Beta-0.9.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	MutantCreatures{1.4.8} [Mutant Creatures] (MutantCreatures-1.7.10-1.4.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	mwaw{1.7.10-0.0.6} [Elemental Witch Mod] (mwaw-1.7.10-0.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	ParticleMan{v1.0} [Particle Man] (ParticleMan-1.4.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	ProjectZulu|Core{1.7.10-1.4c2} [Project Zulu] (ProjectZulu-1.7.10-1.4c2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	quiverchevsky{b100} [QuiverBow] (QuiverBow_1.7.10_b100.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	reptilemod{1.7.10} [Reptile Mod] (reptilemod-1.7.10-2.5.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	SmashBatsMod{1.4.5_1-MC1.7.2} [ƒXƒ}ƒbƒVƒ…ƒoƒbƒgMOD (Smash Bats Mod)] (SmashBatsMod-1.4.5_1-MC1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Torched{4.0.0} [Torched] (Torched-4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	AS_UpdateCheck{1.1.6} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Launched Version: 1.7.10-Forge10.13.3.1380-1.7.10
	LWJGL: 2.9.1
	OpenGL: Mobile Intel(R) 4 Series Express Chipset Family GL version 2.1.0 - Build 8.15.10.1808, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because EXT_framebuffer_object is supported.
Anisotropic filtering is supported and maximum anisotropy is 2.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (UK)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by simeonradivoev** [comment]
The version of CoFHCore you are using is pretty old. And the CoFHLib version it includes is and old one as well. Try and updating the CoFHCore or using a newer CoFHLib library.

**Comment by Nodore** [comment]
I did try to use a newer CoFHCore but it messed up my game.

**Comment by Nodore** [comment]
I'll try updating CoFHLib though

**Comment by Nodore** [comment]
I finally got it to work. Thank you so much. I hate it when I can't get mods this good to work. Now I can finally enjoy it.

**Comment by simeonradivoev** [comment]
good to hear !
