### ISSUE TITLE
World Load

### ISSUE THREAD

**Issue by Mattabase** [simeonradivoev/MatterOverdrive#183]
https://dl.dropboxusercontent.com/u/15990261/ShareX/2015/08/crash-2015-08-21_08.51.40-server.txt

**Comment by simeonradivoev** [comment]
Fixed in e3ac579b2bbdd78723fd1497805107607dd504f3

**Comment by Mattabase** [comment]
Any ETA on release of that?

**Comment by simeonradivoev** [comment]
another hotfix. Soon

**Comment by Mattabase** [comment]
Thanks
