### ISSUE TITLE
i found a bug

### ISSUE THREAD

**Issue by Maks2103** [simeonradivoev/MatterOverdrive#187]
game will stop loading on "Matter Fuel Calculation Started"

**Comment by simeonradivoev** [comment]
I need more than that. Post the crash log. And also tell me what version of the game are you using ?

**Comment by Maks2103** [comment]
crash log not creating
version minecraft 1.7.10
mod list:
AdvancedLightsabers-1.7.10-0.7.2
ae2stuff-0.4.3.47-mc1.7.10
AnimationAPI-1.7.10-1.2.4
appliedenergistics2-rv2-stable-10
AsieLib-1.7.10
bdlib-1.9.1.97-mc1.7.10
Botania r1.6-187
buildcraft-6.4.15
BuildcraftAdditions-1.7.10-2.2.0
buildcraft-compat-6.4.2
ChickenChunks-1.7.10-1.3.4.19-universal
Chisel2-2.3.10.37
ChiselFacades-1.7.10-2.10-cricket
CodeChickenCore-1.7.10-1.0.6.43-universal
CoFHCore-[1.7.10]3.0.2-262
CoFHLib-[1.7.10]1.0.2-160
DragonAPI 1.7.10 V7f
DummyCore1.13
ElectricalAge_BETA-1.10_r50
ElectriCraft 1.7.10 V7e
Enchanting-Plus-Mod-1.7.10
EnderIO-1.7.10-2.2.8.381
EnderStorage-1.7.10-1.4.7.33-universal
EssentialCraftv4.6.1710.42
Eureka-1.7.10-3.0.2
ExtraCells-1.7.10-2.2.73b129
extrautilities-1.2.10
forestry_1.7.10-3.5.6.15
GalacticraftCore-1.7-3.0.12.350
Galacticraft-Planets-1.7-3.0.12.350
IC2NuclearControl-2.2.1a-Yolo
iChunUtil-4.0.0
ImmersiveEngineering-0.4.4
industrialcraft-2-2.2.719-experimental
InventoryTweaks-1.59-dev-152
ironchest-1.7.10-6.0.60.741-universal
Jabba-1.2.1a_1.7.10
JourneyMap5.0.1_Unlimited_MC1.7.10
magneticraft-0.3.2
Mantle-1.7.10-0.3.2
MatterOverdrive-1.7.10-0.4.0-RC3
Mekanism-1.7.10-8.1.2.229
MekanismGenerators-1.7.10-8.1.2.229
MekanismTools-1.7.10-8.1.2.229
MicdoodleCore-1.7-3.0.12.350
MineFactoryReloaded-[1.7.10]2.8.0-104
Morph-Beta-0.9.2
neiaddons-1.12.8.27-mc1.7.10
NEIIntegration-MC1.7.10-1.0.9
NoMoreRecipeConflict-0.2(1.7.10)
NotEnoughItems-1.7.10-1.0.4.106-universal
ProjectBlue-1.1.4-mc1.7.10
ProjectRed-1.7.10-4.7.0pre8.92-Base
ProjectRed-1.7.10-4.7.0pre8.92-Compat
ProjectRed-1.7.10-4.7.0pre8.92-Fabrication
ProjectRed-1.7.10-4.7.0pre8.92-Integration
ProjectRed-1.7.10-4.7.0pre8.92-Lighting
ProjectRed-1.7.10-4.7.0pre8.92-Mechanical
ProjectRed-1.7.10-4.7.0pre8.92-World
Railcraft_1.7.10-9.6.1.0
RedstoneArsenal-[1.7.10]1.1.0-80
RefinedRelocation-1.7.10-1.0.8b
RotaryCraft 1.7.10 V7f
StevesFactoryManagerA92
TConstruct-1.7.10-1.8.5
Thaumcraft-1.7.10-4.2.3.5
thaumcraftneiplugin-1.7.10-1.7
ThaumicBases-1.3.1710.4
thaumicenergistics-0.8.10.10
ThaumicExploration-1.7.10-1.1-37
ThaumicTinkerer-2.5-1.7.10-493
ThermalDynamics-[1.7.10]1.0.0-122
ThermalExpansion-[1.7.10]4.0.1-182
ThermalFoundation-[1.7.10]1.0.0-81
TMechworks-1.7.10-0.2.10
Transformers-1.7.10-0.5.4
Waila-1.5.10_1.7.10

**Comment by simeonradivoev** [comment]
I can't do much without the crash log. Also what Version of the mod are you using ?

**Comment by Maks2103** [comment]
i will say RC3

**Comment by simeonradivoev** [comment]
download the latest hotfix 3 and try it

**Comment by Maks2103** [comment]
game is not crashing, just stopping loading

**Comment by Maks2103** [comment]
i use RC3 hotfix 3, i use lasted version

**Comment by simeonradivoev** [comment]
Then you can send the log that generates. Just start minecraft. Try and get into your world and when it stops just close minecraft without doing anything else. Then go into your logs folder in minecraft. And copy the fml-client-latest.log and paste it into http://pastebin.com/ and post the link to it.

**Comment by Maks2103** [comment]
this is the only log I can provide You, as there is simply no other:
https://yadi.sk/i/4R4WHXupibLFj

**Comment by Maks2103** [comment]
when i close game, crash log not creating

**Comment by simeonradivoev** [comment]
What about game log? Not Crash log.

**Comment by MrGraphic** [comment]
I think that this is another case of MO/registry engine and RotaryCraft incompatibility. Debug prints a lot of repeating lines like ~852k instances of: 
[Matter Overdrive/mo]: Could not find matter entry for: item.item.jumpboots
[Matter Overdrive/mo]: No OreDictionary support for: item.item.jumpboots
for example. There are few items like this one - rechargable via combination with another item in crafting grid. Logs are way too fat to be posted.

**Comment by SJ1133** [comment]
Hey im having a similar issue whre the game just gets stuck on Server thread/INFO] [Matter Overdrive]: Matter Fuel Calculation Started.
Here is the full log: https://gist.github.com/SJ1133/a75cf8f661003578fa61

**Comment by simeonradivoev** [comment]
@SJ1133 your problem is fixed in 53289b7528efff925f4da6e4920ca30f25690512

**Comment by SJ1133** [comment]
Ah thank you didnt notice that. Can i expect a release soon?

**Comment by simeonradivoev** [comment]
I doubt it. You can always try the builds. The latest build fixes your problem. You can find them at http://simeon.co.vu/Mods/MatterOverdrive/builds/

**Comment by SJ1133** [comment]
Ah Thank You :) Didnt know where i could find the dev builds or if they were even public.

**Comment by Maks2103** [comment]
let's start a minecraft crash-test :)
