### ISSUE TITLE
0.4.0-RC3-Hotfix3 stuck on registering fuels

### ISSUE THREAD

**Issue by Exuraz** [simeonradivoev/MatterOverdrive#189]
Hi,

On Matter Overdrive 0.4.0-RC3-Hotfix3, with Forge 1492, when creating a world in SP, it gets stuck on calculating matter fuel. The game keeps displaying the loading screen for world creation, and no matter how long I wait, it keeps trying to calculate matter fuel.

http://pastebin.com/KdXeM2VH

**Comment by simeonradivoev** [comment]
Fixed in 53289b7528efff925f4da6e4920ca30f25690512

**Comment by Exuraz** [comment]
Excuse me for opening this again, but how do I get the build that has that fix? Or am I supposed to wait over 2 weeks to be able to include MO in my modpack?

**Comment by simeonradivoev** [comment]
you can download the builds from here http://simeon.co.vu/Mods/MatterOverdrive/builds/

**Comment by Exuraz** [comment]
Ah alright thank you very much!
