### ISSUE TITLE
Weapon Station causing OpenGL shader errors for Macs

### ISSUE THREAD

**Issue by Nonsanity** [simeonradivoev/MatterOverdrive#19]
Looking at a Weapon Station using a Mac causes constant OpenGL errors until Minecraft crashes:

[15:42:44] [Client thread/ERROR]: ########## GL ERROR ##########
[15:42:44] [Client thread/ERROR]: @ Post render
[15:42:44] [Client thread/ERROR]: 1282: Invalid operation

Have any new shaders been added to this block that aren't compatible across all platforms?

**Comment by simeonradivoev** [comment]
yes. The hologram shader

**Comment by Nonsanity** [comment]
I don't know how long it will take to tweak the shader to work on other platforms (I'm available for testing, if need be), so adding a client-side config to disable the hologram would let people continue to use the block in the meantime. :)
