### ISSUE TITLE
Change to Rogue Android spawning

### ISSUE THREAD

**Issue by NEbuddy** [simeonradivoev/MatterOverdrive#196]
Any chance that Rogue Android spawning can be changed from a biome blacklist to either a dimension blacklist or (ideally) a dimension whitelist or biome whitelist? If they just spawned in the Overworld, they wouldn't be that big of a deal, but without adding a TON of biomes to the blacklist, Androids are spawning literally EVERYWHERE and preventing mobs that should spawn in certain areas from spawning much at all. 

Because of the default biome blacklist setting, when playing with other mods that add new biomes (like Twilight Forest and Biomes O Plenty), Rogue Androids take over the spawns for The End, most of the Twilight Forest biomes, the BoP Nether biomes, as well as vanilla biomes like Mushroom Island and Mushroom Island Shore. This is ridiculous. 

Honestly, if I was playing single player instead of playing on a server and had the option, I would remove Matter Overdrive and never touch it again because of the overly-aggressive Android spawns and the sound bug from anomalies that causes the sound to loop continuously after passing near one (with the only "fix" being a relog).

**Comment by shadowfacts** [comment]
1. Yes this can be done
2. Instead of whining about the sound bug and thinking about how you'd rather play without MO, you could report it and it would be fixed.

**Comment by NEbuddy** [comment]
1. Awesome
2. I didn't mean to come across as whining. I honestly thought the sound bug had been reported already. It wouldn't be as big of a deal if the sound didn't end up giving me a really bad headache after hearing it for awhile. Not sure what it is exactly, but something about the tone just messes with my ears after a few minutes and it added to my frustration with the frequency of Android spawns.

**Comment by simeonradivoev** [comment]
you can always lower the sound of the gravitational anomaly to 0
