### ISSUE TITLE
BioticStatNanoArmor damage calculation is incorrect

### ISSUE THREAD

**Issue by CplPibald** [simeonradivoev/MatterOverdrive#201]
The handler `BioticStatNanoArmor.onLivingEvent()` is multiplying the event damage by the percent negated (`getDamageNegate()`), instead of the percent that would get through (`1 - getDamageNegate()`).  The result is that android nano armor is much more powerful than intended, and gets worse at higher levels.

For example, at level 1, `getDamageNegate` returns 0.12, which is multiplied by the damage amount.  The result is that only 12% of the damage gets through, for an effective damage reduction of 88%.  At level 4, `getDamageNegate` returns 0.3, which means that 30% of the damage gets through and 70% is negated.

To fix, you need to multiply by the damage that gets through, and not the damage negated.  Change this line:

    ((LivingHurtEvent) event).ammount *= getDamageNegate(level);

to this

    ((LivingHurtEvent) event).ammount *= (1 - getDamageNegate(level));

Alternatively, rename `getDamageNegate` to something like `getAdjustedDamage` and change the calculation accordingly.

**Comment by simeonradivoev** [comment]
Ah thank you
