### ISSUE TITLE
Charging station seems to go negative RF

### ISSUE THREAD

**Issue by Kazzamkablam** [simeonradivoev/MatterOverdrive#202]
I got myself the android stuff and put resonant flux capacitor in and charging station energy went below zero to negative values, currently at -4000000 based on waila with MatterOverdrive 0.4.0 rc3

I don't know if it's a bug with waila or the mod.

**Comment by simeonradivoev** [comment]
are you still being charged ?

**Comment by Kazzamkablam** [comment]
yup, still charging
