### ISSUE TITLE
[Enhancement] Add Tritanium Nugget

### ISSUE THREAD

**Issue by hron84** [simeonradivoev/MatterOverdrive#203]
It would be good if Tritanium should have a nugget form, because some mods (mostly targeting to get stuff via harvesting plants) detects valuable stuffs based on their nugget.

**Comment by hron84** [comment]
Thanks

**Comment by simeonradivoev** [comment]
I don't know how exactly other mods detect and match nuggets with ingots with no special metadata. It might just be using the ore Dictionary name and its naming conventions.

**Comment by hron84** [comment]
Neither me. But, for example AOBDBB and some more farmable ore plants cannot work if an ingot does not have a nugget variant since it's a balancing point to not harvest a whole ingot from a single crop.
