### ISSUE TITLE
Crash when opening Computercraft computer attached to Transporter

### ISSUE THREAD

**Issue by elijahlorden** [simeonradivoev/MatterOverdrive#205]
I placed a computer next to the transporter, and got the following crash when I opened the computer's interface: http://pastebin.com/CsPJwLEs

**Comment by shadowfacts** [comment]
You can download [Build 76](http://simeon.co.vu/Mods/MatterOverdrive/builds/) which contains this fix if you do not wish to wait for a release.

**Warning:** These builds can be more unstable, be careful, and make sure to backup regularly.
