### ISSUE TITLE
Java 7

### ISSUE THREAD

**Issue by Horneat** [simeonradivoev/MatterOverdrive#206]
i have the question if you use java 7 ?

**Comment by shadowfacts** [comment]
No. Java 8 is **required**.

**Comment by Horneat** [comment]
oh damit than i have a problem i use Chromaticcraft and this mod is only with Java 7 compatible

**Comment by shadowfacts** [comment]
Not true. I use ChromatiCraft in the Endeavour modpack perfectly fine with Java 8.

**Comment by SvEgiiVEteR** [comment]
please do it for the java 7. more appropriate ...

**Comment by shadowfacts** [comment]
No.

1. Java 8 is the only fully released version of Java that is supported by Oracle.
2. Java 8 has many features which make developing easier.
3. Java 8 has a number of performance benefits for end-users.
4. I conducted [a poll](http://strawpoll.me/5239766/r) a while ago and out of 250 people, 207 of then use Java 8 or newer.

**Comment by Badcholo** [comment]
If your ChromatiCraft only works with java 7, then shouldn't you be placing an issue with the mod author to update to java 8. Everything is now java 8. Even Voltz 1.5.2 can be ran in java 8.
I have a voltz server and i play from client java 8 to the server java 8.

**Comment by SvEgiiVEteR** [comment]
less demand on system resources in general, more controlled, large database software, part of the software does not support java 8.
those who voted would vote 8, as the site once it is downloaded, and click-and not have to think where to take 7 java.
And of course, almost all mode 7 support java. there are also supporting 7+ 8 java

**Comment by shadowfacts** [comment]
> less demand on system resources in general

Where'd you get that?

> more controlled

u wot m8

> large database software, part of the software does not support java 8

You can run multiple Java installations on 1 computer.

> those who voted would vote 8, as the site once it is downloaded, and click-and not have to think where to take 7 java.

u wot m8

> And of course, almost all mode 7 support java. there are also supporting 7+ 8 java

There are also mods that only support Java 8.

**Comment by Bogdan-G** [comment]
@shadowfacts Why for your mod, we have to put Java 8?

**Comment by shadowfacts** [comment]
I am not going to add support for somethings that is so old the creators don't need support it any more.

**Comment by Bogdan-G** [comment]
@shadowfacts Despite this Forge supports himself minecraft Java 6.
