### ISSUE TITLE
[MO - build .76] - matter registry algorithm "forgets" about registry file during loading.

### ISSUE THREAD

**Issue by MrGraphic** [simeonradivoev/MatterOverdrive#208]
Simply as that. Registry file is in correct place, saved after every recalculation - recalculation makes items "valuable" again until nest restart.

**Comment by simeonradivoev** [comment]
what do you mean by valuable ? Is it all items that are not vanilla. Can you also send me a copy of the log file.

**Comment by MrGraphic** [comment]
By "valuable" I means with matter vallues :). Every item that got value during calculation/recalculation process will have that value untill restart. So, every vanilla item like coal, wood or ingots for example will have their fixed matter values but crafting table or chest will not. I will send you log when I will be able to generate proper one for report purpose.

**Comment by shadowfacts** [comment]
Can you please provide the **exact** steps you used to reproduce this?

**Comment by MrGraphic** [comment]
Sorry for the delay - I was driven off by hunting some world leaks caused on my instance by combination of FMP and Factoriztion/LogisticPipes.

Turns out - from logs, that registry algorithm trys to recalculate every restart and it fails for some reason. Debuging will be my next steep.
So far:
Scenario 1: no matter registry
1- New world start, MO starts calculation and it fails at first step,
2- world loads without issue,
3- user starts manual calculation by command,
4 - calculation ends without issue, all matter values for items are in place ( for example crafting table ).
Simplified log from manual calculation : http://pastebin.com/MTCnznxC

Scenario 2: matter registry is present
1 - user starts new world/loads other world without restarting instance ( from scenario 1 ),
2 - MO claims that loaded n matter recipes from registry file:
[21:51:46] [Server thread/INFO] [Matter Overdrive/mo]: Registry Loaded with 2951 entries, from version 0.4.0-RC3 from: C:\Users\Misiek\AppData\Roaming\.minecraft\WERSJE\newera17\config\MatterOverdrive\Registry.matter
3 - world loads, all values are in place as in scenario 1.

Scenario 3: matter registry present
1 - fresh instance start/instance restart
2 - user load same world as in scenario 1
3 - Mo claims that the recipe list changed, starts calculation and it fails of course
4 - as in scenario 1, world loads fine and there are no matter values from recipe list ( again crafting table as an exmple )
log with debugging on: http://tinyurl.com/q722u86

During my bug hunting procedure ( slow shrinking of the amount of mods ) I noticed that at some point it started to pass calculation properly and Forestry was still in the pack - so it will not be forestry as one can assume reading logs.
I my look for the mod that is proabably causing issue but it will take time.

**Comment by axlsjolund** [comment]
I've run into a similar issue. Last night matter values were in place for many of my items from various mods. Rebooted server today as general maintenance. When it came back up, only vanilla items for the most part had registry values. And most of the items in the pattern storage were suddenly invalid.

Manually rebuilt matter registry, and all was well.

**Comment by axlsjolund** [comment]
Just to mention, this issue was reproduced using the latest RC4 download from the main site. The one with hotfix.

**Comment by simeonradivoev** [comment]
I've forgot to show the Exeption error in the log. Can you try it with the latest build and send me the log in the scenario where the registry file is not generated. It should be build 100.

**Comment by Mysteryem** [comment]
Yeah, I'm getting something like this too, but combined with https://github.com/simeonradivoev/MatterOverdrive/issues/254

If I start the server with no Registry.matter file, only the items with predefined matter values will have a value. Chests and other results from crafting will have no value and no Registry.matter file will be produced.

If I then run the /matter_registry recalculate command, chests and other crafting results will get their matter values and a Registry.matter file will be created. But, any items/blocks/oredictionary entries in "new items" lose their matter values (and thus, any recipes that used those items won't get given matter values).

**Comment by simeonradivoev** [comment]
what version are you using ? what OS ?

**Comment by Mysteryem** [comment]
Both Beta 0.4.0-RC4 and 1.7.10-0.4.0-RC4-build-122, windows 7 in singleplayer. I had tried updating to build 122 to see if it would fix the problem.

The logs produced when the debug options are on in the config are way too big to do anything easily with them.

None of the information below actually looks very useful in my eyes, but I don't see a reason not to include it.

Some grep results on the log before recalculating (item.pe_covalence_dust_medium is crafted from 1 iron ingot + 1 redstone to produce 40 medium covalence dust which ends up with a matter value of 1 and tile.pe_alchemy_chest has been given a matter value of 394 in the config)
https://gist.github.com/Mysteryem/a1a20a326f0728fb36d8 (log was about 50MB at this point) (vanilla chests and covalence dust have no matter values at this point, alchemical chest has its expected value at this point).

And here are some grep results on the log after recalculating https://gist.github.com/Mysteryem/6c143226009e146a8c66 (you should be able to see everything from the previous gist here too) (log was about 500MB at this point) (vanilla chests and covalence dust have their expected matter values at this point, alchemical chest has no matter value at this point).

I managed to take this log from the minecraft launcher which doesn't include the debug output but does show the matter calculation finishing and a few NPEs it produced along the way (one of the mods I'm using is being bad and using some items/blocks with no name) https://gist.github.com/Mysteryem/a7c010e8c62287ef550e

If you're feeling crazy, here's the full 600MB log from that single 2 hours and 2 minutes session, compressed to about 6MB https://drive.google.com/open?id=0B46BH5jHk8uaQ0hVbzJ1dGRHck0. As you can probably tell from that compression ratio, there's a lot of duplicated text in the log.

**Comment by simeonradivoev** [comment]
So you have the matter calculation debug config option on ? These seem like normal dump log. The problem is not that the matter registry isn't populated. The problem is that it's not saved to disk.
The save process isn't even called. The log must contain a line "Saving Registry to Disk" and "Registry saved at..". This might be do to the stopping or crashing of the calculation thread. I run the calculation on a different thread.

**Comment by Mysteryem** [comment]
Mm, that line is missing, yeah. All I get when starting a singleplayer world is
```
[20:51:43] [Server thread/WARN] [Matter Overdrive/mo]: Recipe List File missing! Recalculation required!
[20:51:43] [pool-3-thread-1/INFO] [Matter Overdrive/mo]: Starting Matter Recipe Calculation !
[20:51:43] [pool-3-thread-1/INFO] [Matter Overdrive/mo]: Matter Recipe Calculation Started for 22171 recipes at pass 1, with 323 matter entries
[20:51:43] [pool-3-thread-1/DEBUG] [Matter Overdrive/mo]: There was a problem calculating matter from recipe for net.minecraft.item.ItemBlock@3e86790f
```
And restarted with matter calculation debug enabled:
https://gist.github.com/Mysteryem/3c852bb1792f1d1882c1

No idea what block is causing this though.

**Comment by simeonradivoev** [comment]
Can you try the latest build http://simeon.co.vu/Mods/MatterOverdrive/builds/

**Comment by Mysteryem** [comment]
That latest build seemed to get further, but then hit another problem: https://gist.github.com/Mysteryem/fac3f2fad3469295e7a6

**Comment by simeonradivoev** [comment]
Does the calculation finish ? try this one http://mvn.rx14.co.uk/shadowfacts//matteroverdrive/MatterOverdrive/1.7.10-0.4.0-RC4-build-125/MatterOverdrive-1.7.10-0.4.0-RC4-build-125.jar

**Comment by Mysteryem** [comment]
Calculation still does not finish, failing at around about the same place, but an exception output this time:
```
[22:19:05] [pool-3-thread-1/DEBUG] [Matter Overdrive/mo]: Calculating Recipe for: item.natura.pickaxe.fusewood
[22:19:05] [pool-3-thread-1/DEBUG] [Matter Overdrive/mo]: Could not calculate recipe for: item.natura.pickaxe.fusewood. Matter from recipe is 0.
[22:19:05] [pool-3-thread-1/DEBUG] [Matter Overdrive/mo]: Calculating Recipe for: item.natura.bow.darkwood
[22:19:05] [pool-3-thread-1/DEBUG] [Matter Overdrive/mo]: Could not calculate recipe for: item.natura.bow.darkwood. Matter from recipe is 0.
[22:19:05] [pool-3-thread-1/DEBUG] [Matter Overdrive/mo]: Calculating Recipe for: item.natura.pickaxe.darkwood
[22:19:05] [pool-3-thread-1/DEBUG] [Matter Overdrive/mo]: Recipe missing output
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:1.8.0_60]
	at java.util.ArrayList$Itr.next(Unknown Source) ~[?:1.8.0_60]
	at matteroverdrive.handler.MatterRegistry.getMatterFromRecipe(MatterRegistry.java:365) ~[MatterRegistry.class:?]
	at matteroverdrive.handler.thread.RegisterItemsFromRecipes.run(RegisterItemsFromRecipes.java:80) [RegisterItemsFromRecipes.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_60]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_60]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
```

**Comment by simeonradivoev** [comment]
Ah i see. :laughing:. Threading is the bomb. It seems that I didn't even thought of using a synchronized list. The recipe list is used by multiple threads.

**Comment by Mysteryem** [comment]
I tried build 126, but still no Registry.matter produced. However, the recipe calculation did finish. It simply stops after printing the fact it's started furnace calculation now.
```
[23:25:09] [pool-3-thread-1/INFO] [Matter Overdrive/mo]: Matter Recipe Calculation for pass 8 complete. Took 7155 milliseconds. Registered 1 recipes
[23:25:09] [pool-3-thread-1/INFO] [Matter Overdrive/mo]: Matter Recipe Calculation, Complete ! Took 72606 Milliseconds. Registered total of 4232 items
[23:25:09] [pool-3-thread-1/INFO] [Matter Overdrive/mo]: Matter Furnace Calculation Started
```

**Comment by simeonradivoev** [comment]
Crap. You can disable the furnace calculation from the configs for now.

**Comment by shadowfacts** [comment]
@simeonradivoev has this been fixed?

**Comment by simeonradivoev** [comment]
Yes it has.
