### ISSUE TITLE
Crash with Galacticraft

### ISSUE THREAD

**Issue by StarVYT** [simeonradivoev/MatterOverdrive#211]
Hi. there seems to be an issue with Galacticraft and Matter Overdrive. It seems that both mods use an ID of 29 for something. (Possibly player format or similar.)

Here is the crash log: http://pastebin.com/uVpYVH8r

This happens when I try to create or join a world.

I am using Galacticraft 3.0.12.357 and Matter Overdrive 0.4.0 RC3

**Comment by simeonradivoev** [comment]
You must change the ID from either Galacticraft or Matter Overdrive. In Matter Overdrive you can go to the config in the 'abilities ' category and change the 'android energy watch id' to another value.
