### ISSUE TITLE
Can't replicae diamond block

### ISSUE THREAD

**Issue by Acolox** [simeonradivoev/MatterOverdrive#214]
I try to replicate a diamond block,but it won't,but i can replicate any other block.

**Comment by simeonradivoev** [comment]
a diamond block requires about 2k matter. The replicator has an internal tank of 1024. You must use matter storage upgrades to increase the storage.

**Comment by Acolox** [comment]
But I can't put the upgrade in the replicator.
Dana 12. 9. 2015. 23:05 "Simeon Radivoev" <notifications@github.com> je
napisao/la:

**Comment by simeonradivoev** [comment]
what version of the mod are you using ?

**Comment by Acolox** [comment]
0.4.0 RC3
nedjelja, 13. rujna 2015. korisnik Simeon Radivoev <notifications@github.com>
napisao je:

**Comment by simeonradivoev** [comment]
what about the hotfixes ? I don't remember if I fixed it in the hot-fixes but it is fixed now. You can always try the builds.
