### ISSUE TITLE
Caused a divide by 0 error on both client and server.

### ISSUE THREAD

**Issue by Guardian9978** [simeonradivoev/MatterOverdrive#216]
I placed a Decomposer down and gave it power then threw a plank in the machine and it gave me 4 Matter I then added 4 Hyper Speed Upgrades to the machine and placed another plank in and both server and client had a divide by 0 error.

Client Crash Report: http://pastebin.com/DasExaxG
Server Crash Report: http://pastebin.com/kwCG8Kx6

**Comment by simeonradivoev** [comment]
similar to #190 fixed in 2fb0982ea2f00a357b62eb27800158227f3749ad
