### ISSUE TITLE
Server hangs on Matter Fuel Calculation Started

### ISSUE THREAD

**Issue by nonsintetic** [simeonradivoev/MatterOverdrive#219]
Updated to the latest version 0.4.0 - RC3 and now the server hangs on:

[Server thread/INFO] [Matter Overdrive/mo]: Matter Fuel Calculation Started

Log: http://nonsintetic.ro/forge-log.txt

**Comment by simeonradivoev** [comment]
Similar to #189 fixed in 53289b7528efff925f4da6e4920ca30f25690512. You can either wait for the 0.4.0 - RC4 release or you can use the builds in http://simeon.co.vu/Mods/MatterOverdrive/builds/
