### ISSUE TITLE
Duplicate id value for 29

### ISSUE THREAD

**Issue by computertranslator** [simeonradivoev/MatterOverdrive#224]
Building my own modpack, saw this issue was open and then closed previously as attached below:

https://github.com/simeonradivoev/MatterOverdrive/issues/113

I downloaded latest revision of Matter Overdrive from the beta section and crashes with the same error. I've cleaned out the entire Minecraft instance and reinstalled. Prior to the installation of Matter Overdrive the pack is stable.

Here's the full log:

http://pastebin.com/ndxUbaeq

Error occurs promptly when attempting to create new creative single player world.

**Comment by simeonradivoev** [comment]
The bug was fixed in 92fb6286914c391b0478d6fa78b2e2daaf69ddb4. The update hasn't been pushed yet to a beta release. I believe the latest beta version has the option in the config to change the ID of "android energy watch id" in the abilities category. Or you can try the latest build from http://simeon.co.vu/Mods/MatterOverdrive/builds/

**Comment by Alaberti** [comment]
As of RC4-build-115, this option is not present. I had the same problem when I use this mod with Advent of Ascension, which uses 27-30 by default. Is it possible this commit was superceded/not flowing to your builds?

**Comment by simeonradivoev** [comment]
Can you post the crash log ? You should be able to change the id in the Matter Overdrive Config. It should be in "abilities" as "android energy watch id".

**Comment by simeonradivoev** [comment]
The automatic ID assignment will only work if Matter Overdrive is loaded after the Advent of Ascension mod. There isn't much I can do about it if the crash comes from Advent of Ascension.

**Comment by Alaberti** [comment]
My config file: http://pastebin.com/h8ujBxGY
Crashlog: http://pastebin.com/RJcPTizs

You'll note I have a lot of mods in that file; I had previously and systematically added each mod (and required dependencies) one at a time until I got the crash with MO, so I can say I exhaustively verified the interaction. As you can see in the crashlog, it doesn't exactly narrow it down. I found the line itself in my console output during world creation: http://pastebin.com/raw.php?i=VMhyQ1iZ

I fixed the issue by changing id 29 to 31 on the AoA side as my config (freshly generated on 115) does not have the that option.

**Comment by simeonradivoev** [comment]
Ah now I see. Will fix it soon.

**Comment by Alaberti** [comment]
Just happy to help lol.
