### ISSUE TITLE
A suggestion about translatable datapad

### ISSUE THREAD

**Issue by Joccob** [simeonradivoev/MatterOverdrive#225]
I really love this mod and I hope more people, who come from other country like me, can enjoy this mod. I have to say that the idea of the ingame data pad is great. It would be nice if you can put all the content in the lang file (or maybe a separate xml file) and make it translatable. I hope it is easy to be done...anyway, thx for bring us this marvelous mod, you guys are the best

**Comment by simeonradivoev** [comment]
The data pad is translatable. I separated each info into a separate file for convenience. You just need to put the info in the appropriate folder. For example en_US for US English and just like @MrVizzyTM did with Russian in ru_RU,

**Comment by Joccob** [comment]
sorry，didn't see that
