### ISSUE TITLE
Issue with Power Selection GUI and Powers in 0.4.0 RC4 Update

### ISSUE THREAD

**Issue by Bluesnarf** [simeonradivoev/MatterOverdrive#227]
There is an issue with multiple Android players in SMP in 0.4.0 RC4 update if they are in visible distance of each other:

Issue #1) Two androids that don't have the same powers cannot use the power selection gui next to each other. Once they go far enough away from each other it works.

Issue #2) Two androids that have the same powers within visible distance of each other cause the other android not to be able to use that same power or both not at all. This was tested with teleportation. This issue resolves when the players are out of render distance of each other.

Issue #3) Players share abilities even when they haven't unlocked them. Ex: I went down the power tree and my friend went down the defence tree. I went to use the night vision power and ended up using projectile shield on my own character and his at the same time when i activated it even though I did not unlock it. This issue resolves when players are out of render distance from each other.

I did not see any exceptions in my logs to post which are on debug level.

**Comment by simeonradivoev** [comment]
Hm so weird. It's a pain to test SMP alone. Will check it out.

**Comment by Bluesnarf** [comment]
Thanks Simeon, loving the mod thus far. Also, modpack being used is FTB Horizons: Daybreaker v1.1.0. Manually updated the mod. This issue did not occur in v0.4.0 RC2/RC3 on the same pack.

**Comment by simeonradivoev** [comment]
Ah found the problem. And such a simple fix it is.

**Comment by Bluesnarf** [comment]
You are amazing, thank you!

**Comment by simeonradivoev** [comment]
I uploaded the hotfix on curse. It will be up and running in no time.

**Comment by Bluesnarf** [comment]
Already downloading and applying the build. :)

**Comment by Bluesnarf** [comment]
Confirmed working.
