### ISSUE TITLE
Data Pad Client Crash

### ISSUE THREAD

**Issue by Bluesnarf** [simeonradivoev/MatterOverdrive#228]
Data Pad causes client to crash when used in v0.4.0 RC4, manually updated in FTB Horizons: Daybreaker v1.1.0:

Crash Report:
http://pastebin.com/stkX5ed6

**Comment by simeonradivoev** [comment]
When does this happen ? in SSP or SMP

**Comment by Bluesnarf** [comment]
This happens in SMP.

**Comment by Divineaspect** [comment]
Having the same crash
http://pastebin.com/kNZVXjdY
Note, my pack includes fastcraft.

**Comment by Divineaspect** [comment]
and it specifically doesn't take place in single player.

**Comment by Divineaspect** [comment]
This is my Client Log http://paste.atlauncher.com/view/42658530

Here is what the Server is doing http://pastebin.com/0muFZV5w
