### ISSUE TITLE
Crash when loading MO up.

### ISSUE THREAD

**Issue by MechWarrior99** [simeonradivoev/MatterOverdrive#230]
The game crashes when loading. I only have MO in and I am using the newest forge and MO versions.
http://pastebin.com/0Wq68XAp

**Comment by simeonradivoev** [comment]
As of 0.4.0-RC1 Matter Overdrive only supports Java 8

**Comment by Yulife** [comment]
Strange. I get a [similar crash](http://paste.ee/p/nT8dH) and I am using Java 8.

**Comment by simeonradivoev** [comment]
Do have CofhLib or CofhCore installed ?

**Comment by Yulife** [comment]
Oh, I don't! :open_mouth: Never knew that was a dependency :) Weird that it didn't show the "Missing mods" screen and just crashed

**Comment by simeonradivoev** [comment]
Yea. Unfortunately CofhLib is not exactly a mod.
