### ISSUE TITLE
Crash when placing Tritanium Glass :(

### ISSUE THREAD

**Issue by basil-ionin** [simeonradivoev/MatterOverdrive#231]
http://pastebin.com/iw2eJsyC - Crash Report

I just placed Tritanium Glass and...

(Matter Overdrive 0.4.0-RC4-build-99, CoFH Core 3.0.4B1-308, MC Forge 10.13.4.1492, Java 1.8.0_45)

**Comment by simeonradivoev** [comment]
Ah. This is an EnderIO problem on our side.

**Comment by shadowfacts** [comment]
Was EnderIO installed? If so, what version were you using?

**Comment by simeonradivoev** [comment]
I tried it in SSP with no mods and I get the same error

**Comment by shadowfacts** [comment]
Yup, I derped and included `@Optional.Method` on the `checkEIO` method.

**Comment by 401090527** [comment]
I also encountered this problem.

**Comment by shadowfacts** [comment]
Once the CI finishes, you'll be able to use build 127 (download [here](http://simeon.co.vu/Mods/MatterOverdrive/builds/)).
