### ISSUE TITLE
Phaser Loses power first With Power Armor

### ISSUE THREAD

**Issue by Badcholo** [simeonradivoev/MatterOverdrive#237]
All other devices and items keep their power like RF. It seems that Power Armor keeps taking power from the phasers and rifle first before taking from batteries or capacitors. All other hand tools, multi drills from other mods are ok, just wondering what may be different from yours. Mojangsters Modpack from the technic launcher

**Comment by simeonradivoev** [comment]
What do you mean by power armour ? And how does it take the RF just bu having them in your inventory ?

**Comment by shadowfacts** [comment]
This sounds like a problem with whatever mod adds the power armor you're using. We don't do anything special on our end in regards to the way Phasers handle RF.

**Comment by simeonradivoev** [comment]
True. We use the RF Energy API. This makes the phaser act like a power storage. The only way I can think of is by making the maximum energy extract 0.

**Comment by Badcholo** [comment]
Power Armor. 
https://github.com/QMXTech/MachineMusePowersuits/releases

Technic Launcher "Mojangsters" Custom Modpack.
http://www.technicpack.net/modpack/mojangsters.583708

I am about to add your mod to the modpack, I used RC3 since it crashed when i used RC4.
I will be updating CoFH core and all others soon, i just need to make sure they will run properly.

It seems PA takes power from all other devices depending on what position they are in, It is meant to allow you the use of having a power cube or such in your inventory to power the suit.

For some odd reason, it seems to like taking power away from your phaser and rifle first which of course is bad, I have upgraded the phaser and with a bigger battery it's not so bad, The Capacitor can recharge it quickly enough to ignore the drain, the problem is when i'm not holding it, it will get drained completely eventually and it will not be ready for quick use. Wasn't sure if there was a quick way to stop it from allowing other mods to take energy from it. I understand it needs to be like a battery so that my wireless charger can charge it while i'm at home.

Thanks for your time, Really enjoying your mod. Modular power armor is not being updated, it was just ported to 1.7.10, just enough to make it work. They aren't really working on it anymore, but it's really awesome. It has very similar enhancements, except they are in armor form. Check out my modpack and see if you can understand what i mean. I understand if you just close this issue out thou.
