### ISSUE TITLE
Ability to Remove Upgrades

### ISSUE THREAD

**Issue by Badcholo** [simeonradivoev/MatterOverdrive#238]
I haven't found a way to remove the upgrades so that i can choose different ones. Possibly allow for all of them to be installed and balance out the effects. I have been thinking of adding this mod to Mojangsters Modpack from the technic launcher. It's really amazing!! Great Job.

Ability to remove upgrades using the android station. Maybe i just don't know how.

**Comment by simeonradivoev** [comment]
Yes this is a must. They only way to do that now is by using the commands http://simeon.co.vu/Mods/MatterOverdrive/commands/

**Comment by Badcholo** [comment]
Thank You, I can't believe i haven't seen this mod before. Its very nicely done.

**Comment by simeonradivoev** [comment]
Added as a Yellow Pill in 6b71b6682e4d57374e2b83a436db0b55715c84cd

**Comment by Badcholo** [comment]
Nice!!!
