### ISSUE TITLE
A way to collapse or remove Anomalys

### ISSUE THREAD

**Issue by Badcholo** [simeonradivoev/MatterOverdrive#239]
We could use a way to Capture, Move or collapse Anomaly's. It would be nice to be able to place them or create one in a preferred location. 

Also at max size with an Anomaly, I am unable to add stabilizers with 2 power grids on it, if i place the stabilizers they just get chewed up by the Anomaly's. i can however add stabilizers before it gets to max size and countinue making it grow to max size white keeping all stabilizers on it. I like the setup and difficulty level of creating such an event. 

Possibly a Block like the Stabilizer but instead collapses the Anomaly.
![2015-09-25_18 08 30](https://cloud.githubusercontent.com/assets/10932905/10115058/7ecdfa44-63b1-11e5-98c3-ab2c2de5ce78.png)

**Comment by Badcholo** [comment]
Same as the Stabilizer but creates an Anomaly using tremendous amounts of Energy and Matter.

**Comment by simeonradivoev** [comment]
I was planning on making an item that you throw in the anomaly to collapse it.

**Comment by simeonradivoev** [comment]
It would be a lot cooler to and an explosive that destroys an area and forms an anomaly based on the combined matter of all the blocks.

**Comment by Badcholo** [comment]
I do like that idea. 
I also like the tossing in Antimatter into the anomaly to destroy it.

**Comment by Badcholo** [comment]
I like it, I can always sell the anomays at the shop for a very high price so they can be replaced if they get too big for the player to handle or other.
