### ISSUE TITLE
Crash when shift clicking upgrades into the decomposer

### ISSUE THREAD

**Issue by Badcholo** [simeonradivoev/MatterOverdrive#241]
http://pastebin.com/GX3NVxtJ

I wanted to upgrade the matter decomposer in SSP when i tried to add the upgrades by Shift right clicking caused me to crash. I may have tried to shift left click by mistake first. I can't seem to join the game now as it keeps crashing on me. Again it's SSP and it was a new world so no big deal.

I was able to replicate this.

Create a new world.
place a matter decomposter
Add a battery and melons to it, so it's active.
Shift left click the hyper speed upgrades. 
Crash. can't log back in.
It does not have to be connected to an entire setup. it can be placed by it'self.

**Comment by simeonradivoev** [comment]
Does this happen only when you Shift click the updates ? And is fixed in the latest version, you should use it.

**Comment by simeonradivoev** [comment]
Similar to #190. Fixed in 2fb0982ea2f00a357b62eb27800158227f3749ad. You should try the newest version.

**Comment by Badcholo** [comment]
It has been fixed in RC4 sry. I have updated to the latest version.
