### ISSUE TITLE
In SSP Crash

### ISSUE THREAD

**Issue by Badcholo** [simeonradivoev/MatterOverdrive#242]
Steps
It does not crash so it technically does not produce a Crash report.
In SSP it just stops working and i also can't close it and go to the title screen.
I have to force shutdown the whole technic laucher.

create a new creative world.
go into survival.
eat the red pill.
You don't die and the game remains stuck, breaking blocks like dirt don't give off anything.
Its like your in ghost mode. exiting to title screen keeps you stuck, you have to force close it.
latests logs after deleting them before running the launcher.

https://www.dropbox.com/sh/zaoe7lbightlhk2/AACC6JGdmUkBrEU7y7DGBgsya?dl=1

**Comment by Badcholo** [comment]
I have added this mod to Mojangsters Modpack from the technic launcher, i'll to find if it's another mod causing this issue.

**Comment by simeonradivoev** [comment]
Keep in mind that you die if you eat the red pill. If you are in creative or in hardcore mode this might cause problems. Dying in creative mode was fixed in the latest version of the mod. I haven't tested it in hardcore mode.

**Comment by Badcholo** [comment]
I have tried with the latest version of your mod and updated forge to 1492
It seems to only happen in SSP. I wasn't in creative or hardcore mode. I'll try to find out what mod is causing this.

**Comment by Badcholo** [comment]
I found out what it was, it was a client mod called. Blood-Particles-Mod-1.7.10
It would prevent me from dying in SSP once i took the red pill and would lag out the server intensely in Multiplayer.
