### ISSUE TITLE
Nano Armor or Attack Boost.

### ISSUE THREAD

**Issue by Badcholo** [simeonradivoev/MatterOverdrive#243]
I'm having to choose after i get nanobots. Either Nano Armor or Attack Boost.
I am using RC3 thou, so i may just have to update.
I can't seem to choose both. The requirements still say, you just need nano bots.
I really love this feature. Its the best part of the mod.

**Comment by simeonradivoev** [comment]
That's not a bug. It's intentionally made so that you must choose either the defence tree or the attack tree.

**Comment by Badcholo** [comment]
ah, ok i see, it's just not finished yet.
