### ISSUE TITLE
Eating the Red pill Removes All Armor and Enchantments.

### ISSUE THREAD

**Issue by Badcholo** [simeonradivoev/MatterOverdrive#244]
So i eat the red pill and any armor or enchantment i wear is useless.
protection enchantment and armor values aren't being used for some reason.
I can wear diamond armor with protection and it's way better than any upgrade you can provide from abilities. Why is it that turning into a android is worse than being human?
A way to customize how much health can be increased by abilities would be great.
Same with the force field and regeneration. My server is hard core and with all of your android abilities i can be 1 shot by a creeper. Even with max enchanted ender io armor. 
watch my vid and you'll get it.
https://www.youtube.com/watch?v=rgjhDlkoh2w

**Comment by Badcholo** [comment]
just to be clear, i can wear armor and enchantments, but the damage that the mobs do to me was as if i wasn't wearing any armor.

**Comment by Badcholo** [comment]
I updated the server to cauldron forge 1492. I am using the lates Matter Overdrive. Seems to have gotten better, but i still drop to 15% health from 1 creeper explosion With fully enchanted Ender io armor. i'd lose maybe at the most 1/2 a heart if any without going borg. Is there a way to allow the full effects of armor and enchantments? maybe a config option?

**Comment by simeonradivoev** [comment]
The Android should only remove enchantments. You should be able to use any armor with no diminishing effects.

**Comment by simeonradivoev** [comment]
Have you tested the armour protection when you're an Android and when you're not.

**Comment by simeonradivoev** [comment]
I tested the scenario of wearing an armor while being an Android and while being Human. I even tested it with Nanobots and Nano Armour unlocked. I see no difference in damage reduction when wearing armour while being an Android. Having Nano Armour and Nanobots ability with diamond armour makes me quite hard to kill.

**Comment by Badcholo** [comment]
I understand, can't use enchantments while in Android mode. That is what i must have noticed.

Yes, close to the end of the video, it shows how many hearts and force field yellow hearts you can eventually obtain. Does the Android health increase with more hearts you have or is it a fixed number. Your able to obtain 30 red hearts and 10 yellow force field hearts. Force field hearts regenerate after you haven't taken damage for 5 sec quite quickly.

On my server your able to get protection X in survival. As well as Fortune V, Sharpness X, Fire Aspect V, so pvp as a android would not be very effective if you can't use enchantments.
It would be nice to know the reasoning for no enchantments as a android? it's on the armor not the Character. Your still able to gain experience as a android right?

maybe a config to allow enchantments?

**Comment by simeonradivoev** [comment]
I meant potion effects :disappointed: sorry about that. Enchantments will work just fine. 
The only way to increase max health is through Android Parts like the Tritanium Spine and Rouge Android Parts. They give you a set amount of hearts. Hopefully they stack with other mods.

**Comment by Badcholo** [comment]
Does it stack with The yellow hearts Absorbtion? I have certain items ingame that provide Absorbtion (yellow hearts) for consuming or wearing certain armor. I will create a new issue for that.
maybe a gui for absorbtion and a config to allow potion effects / eating. I'd like to be half android.

The "absorption" effect likewise adds 4 (Absorption Heart.svgAbsorption Heart.svg) for each effect level. This special health cannot be healed or regenerated by normal means. Naturally, it will be removed when the effect expires. Absorption can be gained by eating either type of golden apple.

**Comment by simeonradivoev** [comment]
I use the vanilla stats for increasing max health. So i don't know why it's messing with anything. I don't do anything special. Just use the same mechanic that minecraft uses to increase your max health.

**Comment by Badcholo** [comment]
Armor value is working as intended. It was the missing potion effects that i noticed.
