### ISSUE TITLE
Let users know it has a dependency of CoFH Core, 

### ISSUE THREAD

**Issue by Badcholo** [simeonradivoev/MatterOverdrive#246]
I tried running Matter Overdrive mod by itself to test something out and it kept crashing, 
Once added CoFH core it loaded up without crashing, I haven't tried just adding CoFH core lib files.

**Comment by shadowfacts** [comment]
MO does not depend on CoFH Core, it depends on CoFH Lib.

Technically, CoFH Lib is not a mod and therefore we can't use the normal method of alerting the user of dependencies.

If you had read the description, or looked in the dependencies section of the CurseForge page, you would see that CoFH Lib is a [required library](http://puu.sh/kprcD.png).

**Comment by simeonradivoev** [comment]
It's not a dependency of CofhCore. I just use CofhLib which is not a mod. It's a library. I wanted to package it with my mod so that it's not fatal when you don't have the library itself, but the creators did not like me repackaging the library.

**Comment by Badcholo** [comment]
I checked the curse page before i posted this, I didn't see any post about a dependency of the CoFH Lib. Also i wasn't trying to be rude. I was just trying to help notify other players who may want to try out your mod. Not everyone uses CoFH lib or core.

**Comment by shadowfacts** [comment]
If you look at the bottom of the [file page](http://minecraft.curseforge.com/mc-mods/229694-matter-overdrive/files/2258902) there is a section called "Related Projects."

**Comment by Badcholo** [comment]
How the F*** am i supposed to know it's there?

**Comment by shadowfacts** [comment]
Uh... Eyes?

**Comment by Badcholo** [comment]
Most people post it at the top of the page so it's the first thing people see. It's quite important information ya know.

**Comment by Badcholo** [comment]
I said "how am i supposed to know it's there?" Not What do i use to see my screen?

**Comment by shadowfacts** [comment]
Alas, I am not in charge of CurseForge and cannot make any changes about that. Feel free to make yourself a custom stylesheet or pester Curse employees about it.

**Comment by shadowfacts** [comment]
It is on your screen... You use your eyes to see the screen... Therefore, you use your eyes to see the Related Projects section... Ya follow?

**Comment by simeonradivoev** [comment]
http://simeon.co.vu/Mods/MatterOverdrive/download_category/downloads/ you can see the install instructions. As @shadowfacts we can't do much in the way of showing info ingame, because cofhlib is not a mod itself. It's just a collection of scripts with no main mod file and it does not function as a mod.

**Comment by Badcholo** [comment]
I figured it out quite quickly that it needed a dependency, It's not a mod but it is still needed to run the mod so it's quite important information. I was trying to help because there are probably a lot of players who install your mod and it causes them to have a crash, They would immediately blame your mod, possibly create a New issue with a report or just delete your mod and move onto the next one. I was just trying to be helpful, clearly someone needs to find another place to do their trolling.

**Comment by shadowfacts** [comment]
I am not trolling, I am being perfectly serious. You originally escalated the conversation:

> How the F*** am i supposed to know it's there?

Additionally, both myself and Simeon had answered you (multiple times) yet you were still pestering us.

**Comment by simeonradivoev** [comment]
We appreciate your help. I plan on removing the dependency of CofhLib sometime in the future, but it will require a bit of work. For now there isn't much I can do but tell the people who miss the information and tell them that it's a dependency.

**Comment by Badcholo** [comment]
Your a Troll and you got issues. Seems to me like you haven't gotten laid in some time. You need to relax and stop bothering people who are just trying to help. Trolls will be trolls, but you need to work at it if your going to be anything other than a "Yawn" Don't say anything if your not even in charge of the page. I'll just post it in the comments at curse page. I can see by the comments there, a few players have missed that bit of information.
