### ISSUE TITLE
Server Lag

### ISSUE THREAD

**Issue by Badcholo** [simeonradivoev/MatterOverdrive#251]
So i have a modpack and a Server. When i add your mod to the Testing server, i can turn into a Android. The problem happens after i die as a Android. I begin to get massive tps drop to 6.5
I have deleted all region files and made a flat world for spawn.
there is nothing running but the mods and it only happens after i die as an Android. I'll post server logs as soon as i can. I have been trying to install Mobis core, and Opis to try and figure out where the tps drop is coming from but it keeps causing me to crash. i don't think they are updated to forge 1492 yet.
keeps crashing about mapwriter rendering or something. 
Any ideas on how i can debug or figure out where this tps drop is coming from? 
I have my main server and all is well, pregenerated. I copied the server and ran it for testing purposes and the only mod i add to it is Matter Overdrive. As soon as i go Android and die i get the tps drop. I have stopped all other servers and have full cpu and 16gb of ram and seem to still drop to 6.5 tps.
if you know any way that i can find what mod is causing this it would be great since it would take me forever with 1 mod at a time, specially from the server.

**Comment by simeonradivoev** [comment]
The only way i can think of is through the logs.

**Comment by simeonradivoev** [comment]
This only happens in SMP ?

**Comment by Badcholo** [comment]
yeah, it only happens in SMP

**Comment by Badcholo** [comment]
I'll get you fresh logs as soon as i get back from picking up some lunch

**Comment by Badcholo** [comment]
http://pastebin.com/xMUpe9sa
You don't really have to, but does this crash make any sense to you?
I have been trying to use opis.

**Comment by Badcholo** [comment]
https://www.dropbox.com/sh/zaoe7lbightlhk2/AACC6JGdmUkBrEU7y7DGBgsya?dl=1

Server logs
Deleted all logs, ran the server.
logged on.  typed in /gc /tps
ate the redpill
got stuck in limbo, relogged.
typed in /gc /tps and watched it drop to 11.5
i forgot to delete the client logs. i'll get you some.

**Comment by simeonradivoev** [comment]
It might be a client issue. The server logs don't have any useful information.

**Comment by Badcholo** [comment]
It's definitely server lag, cause it drops tps instead of fps. I'll let you know when i find something. sry and thanks.

**Comment by simeonradivoev** [comment]
what does the /gc command do ? When I tried on my local server with the server and client on the same machine in debug mode with a lot of mods and I can't get the lag. What is your average tps ?

**Comment by Badcholo** [comment]
It is from Essentials bukkit plugin.
/gc: Displays chunk, memory, and world information.
tps, max memory, alloted memory, free memory, amount of chunks loaded in what dimensions.

    * essentials.gc
i was able to get opis working on single player i noticed quite a few anomalys spawning around me.
A config to not naturally spawn in or less of anomalys would be nice.
Having so many anomalys, does that cause lag? if they are not yet active.

**Comment by simeonradivoev** [comment]
There is a config to disable anomaly spawning as well as entity pulling and block destruction. But i don't see why they would cause a problem only when you die as an Android.

**Comment by Badcholo** [comment]
I'll do some more testing and see if i can get you some more info.

**Comment by Badcholo** [comment]
Server lag had nothing to do with your mod. Sry and thank you for putting up with me.

**Comment by simeonradivoev** [comment]
What was it then ?

**Comment by Badcholo** [comment]
I'm not sure but i made a clean install server and updated a few mods and my tps has been dropping to 10 - 29, it keeps going up and down as i get into my spawn world. It maybe a plugin protection flag at spawn cause i can't build stargates from lanteacraft at spawn anymore. i'm learning how to use JVM to find out what class or mod is causing the tps drop. i can't install opis cause mobiscore isn't compatible with cauldron. I may have to change to forge/spigot for 1.7.10, but i'm not sure how to get that set up yet. This may take a while, but i'll keep you updated as soon as i get more info on the root cause. my server hasn't had any tps issues since it started.
