### ISSUE TITLE
Editing matter calculation

### ISSUE THREAD

**Issue by Ganjalf-Amsterdoom** [simeonradivoev/MatterOverdrive#252]
Hello,

I just updated to rc4 and custom matter values are not being taken.

For a test I tried making dirt value 5 and run the command to recalculate, nothing.
I removed the registry file and run the command, nothing.
I removed the registry file and restarted the game, nothing.

What am I doing wrong? should i post the lines I use for the setup?

Thank you.

**Comment by simeonradivoev** [comment]
Yes that would be helpful.

**Comment by Ganjalf-Amsterdoom** [comment]
"item overrides" {
        test {
        I:dirt=5
        }
    }

**Comment by simeonradivoev** [comment]
oh my. Where did you get the idea to format it like that. http://simeon.co.vu/Mods/MatterOverdrive/configurations-guide/ here is the guide. Try it out and tell me if it works. I will add an ingame command soon to register items.

**Comment by simeonradivoev** [comment]
4fca8b776ad91026d55831d7efa71358f09f4e6d Here I added the command. You can use it by holding the item and typing /matter_registry register (item/itemstack) [matter value] and substituting the necessary parts.

**Comment by Badcholo** [comment]
Nice, i can really use this. Great Thinking!

**Comment by Ganjalf-Amsterdoom** [comment]
I copied exactly from your doc page, is kind of vague, can you please post a working example.

**Comment by simeonradivoev** [comment]
You have to follow the pattern in the category "matter registry" in "item overrides" for overrides and "new items" for adding new entries.
I:[1]=[2]

1. Unlocalized name with item or tile prefix. You can also use Ore Dictionary name.
2. The matter amount.

**Comment by Ganjalf-Amsterdoom** [comment]
So I was just missing the brackets?

**Comment by simeonradivoev** [comment]
no without the brackets

**Comment by simeonradivoev** [comment]
it should become 
"item overrides" {
    I:tile.dirt=5
}

**Comment by Ganjalf-Amsterdoom** [comment]
"item overrides" {
    I:tile.dirt=5
    }

Deleted the registry file and regenerated via command. Dirt stay 1.

**Comment by simeonradivoev** [comment]
where did you put the 
"item overrides" {
I:tile.dirt=5
}

**Comment by Ganjalf-Amsterdoom** [comment]
"matter registry" {
    B:"automatic matter calculation from furnace"=true
    B:"automatic matter calculation from recipe"=true
    S:blacklist <
     >
    S:mod_blacklist <
     >

    ##########################################################################################################
    # new items
    #--------------------------------------------------------------------------------------------------------#
    # Registration of new items and the amount of matter they contain. Add them like so: I:[unlocalized name or ore Dictionary name]=[matter amount]
    ##########################################################################################################

    "new items" {
    }

    ##########################################################################################################
    # item overrides
    #--------------------------------------------------------------------------------------------------------#
    # Overriding of existing items and the amount of matter they contain. Add them like so: I:[unlocalized name or ore Dictionary name]=[matter amount]
    ##########################################################################################################

    "item overrides" {
    I:tile.dirt=500000
    }

}

**Comment by simeonradivoev** [comment]
it seems that dirt's unlocalized name is "tile.dirt.default"

**Comment by Ganjalf-Amsterdoom** [comment]
Ok now it works, the recalculation does not however, I need to remove the registry file and reload the game to get the new matter data/configuration.
