### ISSUE TITLE
Feature Suggestion: Spawn egg for Crazy Villager

### ISSUE THREAD

**Issue by Badcholo** [simeonradivoev/MatterOverdrive#253]
My modpack creates many new varieties of villagers. I didn't even realize it until i needed a specific one to place at spawn. I wanted to create a Borg Power plant facility where i could show off the mod anomaly's fusion reactors and the awesome machines your mod provides.

I kept trying to get your mods villager with no success for like 30min in creative mode. I don't know if it is a new mob that just spawns in the villages or if it is a type or variety of a villager. 
If it's not that much trouble, it would be nice to have a spawn egg for him.
Or maybe i just didn't see it?

**Comment by Badcholo** [comment]
I am preparing to make a mod showcase, so i usually like to be very well prepared.
I want to make a really awesome mod showcase, because i really think this mod deserves it.
could you use some decoration blocks? i can design some nice decoration blocks, like for borg walls or such, i'll make some and give you the download link, any you like feel free to keep and use them.
I'm only in like 2months of learning to write code and it's in java script, so i wish i could help more.

**Comment by shadowfacts** [comment]
You can use `/summon mad_scientist` in the mean time.

**Comment by simeonradivoev** [comment]
There is a spawn egg. It spawns the Mad Scientist.

**Comment by Badcholo** [comment]
I'm an idiot, Thanks.
