### ISSUE TITLE
Upgrades Not Dropping

### ISSUE THREAD

**Issue by axlsjolund** [simeonradivoev/MatterOverdrive#255]
Apparently a few users have been seeing a bug that when they wrench a machine that has upgrades in it, the upgrades don't drop and just "disappear" into nothingness. They double checked by reloading game, and seeing if maybe they stayed in machine when it was placed again. Nothing showing.

Don't know if this is a bug, or a planned feature. Sounds like a bug.

**Comment by simeonradivoev** [comment]
If you wrench machines the upgrades stay in the black and should still be there when placed.

**Comment by simeonradivoev** [comment]
what version of the mod are you using ?

**Comment by axlsjolund** [comment]
I'm using the latest from the site. RC4 with hotfix 1. The machine was wrenched. Specifically it happened with a teleporter

**Comment by simeonradivoev** [comment]
I can't seem to be able to reproduce it with any machine on SSP and SMP.

**Comment by simeonradivoev** [comment]
You can try the newest build 108 and see if the wrenched machine blocks even display on their tooltip the items stored.

**Comment by simeonradivoev** [comment]
Should be fixed in 30aefe75ca2d5626acdee955e34dcda048796512
