### ISSUE TITLE
Minecraft start crash

### ISSUE THREAD

**Issue by alesharik** [simeonradivoev/MatterOverdrive#259]
I use Matter Overdrive v.0.4.0-RC4-Hotfix1 and CoFH Lib v.1.0.3-175 and I can't start minecraft:
http://pastebin.com/isDqxNMJ

**Comment by simeonradivoev** [comment]
The problem is that your minecraft is loading the older version of CofhLib from CofhCore instead of the CofhLib jar. You do have them both ? The CofhCore and CofhLib. I really should release my dependency on CofhLib :X. You can try and update CofhCore.
