### ISSUE TITLE
Server crash with KCauldron

### ISSUE THREAD

**Issue by Towsty** [simeonradivoev/MatterOverdrive#261]
With KCauldron-1.7.10-1492.155, MatterOverdrive-1.7.10-0.4.0-RC4 Hotfix-1 there still seems to be a crash:

Crash:
http://pastebin.com/DZyn2fM5

Same issue was posted and closed already (#78), not sure if it was fixed though.

**Comment by simeonradivoev** [comment]
It's not exactly a problem with Matter Overdrive. The error seems to happen when Matter Overdrive gets a list of all loaded entities in the world, but KCauldron gives invalid information. It tells Matter overdrive that it has more entities than it really has.

**Comment by Towsty** [comment]
Okay, I posted this over on the Bug Reports section of the [KCauldron forums: here](http://tcpr.ca/forums/discussion/140/possible-compatibility-issue-between-kcauldron-155-and-matteroverdrive/p1)

**Comment by simeonradivoev** [comment]
Hope we can fix it

**Comment by Towsty** [comment]
Is there any reason this would be more likely in 155 than 152?

**Comment by simeonradivoev** [comment]
No idea.

**Comment by Towsty** [comment]
Kay thanks, I've reverted to 152 to see if it made a difference, its a pretty sporadic error in general so its hard to say if its made a difference.

**Comment by Towsty** [comment]
So 152 of KCauldron is the latest stable version of KCauldron, if anyone else has this issue it does not seem to be a problem on 152. Been playing for a couple of hours now - no issues, and it is what was recommended on their forums.

**Comment by spannerman79** [comment]
> and it is what was recommended on their forums.

There is no "official" forums for kcaulron.  There is an issue tracker but no official forums.

**Comment by Towsty** [comment]
tcpr.ca/forums/categories/bug-reports

**Comment by spannerman79** [comment]
As I stated, there is no official forum - not even Yive's Mirror forums is an official forum for kcauldron.

**Comment by Badcholo** [comment]
Either way, everyone who uses Kcauldron needs to be using version 152 or they are going to have problems and blame mods for it. It happened to me and i didn't get it until someone posted on Yive's Mirror forum.

**Comment by spannerman79** [comment]
On the actual kcaudron issue tracker is clearly states along the top, and I'll quote

     Don't use 153+ builds! It's testing builds and have some issues with performance and compatibility with mods. Latest stable build is .152

All Yive does is provide a location of a mirror for mods, plugins and servers and a forum. There are other projects he does but that's outside of the scope of his/her mirror.

**Comment by Badcholo** [comment]
oh, i totally missed that.
