### ISSUE TITLE
Feature Suggestion: A Power Core

### ISSUE THREAD

**Issue by Badcholo** [simeonradivoev/MatterOverdrive#263]
~~A Power Core Capable of holding Infinite Amount of RF. ~~
I noticed once i got a big enough reactor running even the highest tier energy cells or cubes got full quickly, even with MFR Mining Lasers.~~

**Comment by simeonradivoev** [comment]
To be honest I'm not too fond the unrealistic mechanics of RF power. And having an infinite power storage isn't a very appealing concept. I have other plans for the enormous amounts of RF produced from the anomaly. I will probably use it with the Galaxy Map and other features.

**Comment by Badcholo** [comment]
yeah, i was going to say we probably need a way to use the infinite power source. Maybe the stabilizers require power? Possibly something like:
Lots of power to create matter for producing precious metals and such. 
Lots of power to create Antimatter in a special machine?
Lots of power combined with Antimatter to create an explosive?
Lots of power to create special crystals from matter?
Lots of power to create a Impenetrable force field
![mffs force field](https://cloud.githubusercontent.com/assets/10932905/10324564/649692d0-6c3f-11e5-872f-8015fa2b969d.png)

What does the galaxy map do? will there be space travel eventually?

**Comment by simeonradivoev** [comment]
The star map will be more like a minigame, with base building and resource gathering.

**Comment by Badcholo** [comment]
I have installed your mod onto my actual Modpack and Server.
http://www.technicpack.net/modpack/mojangsters.583708
I'm using the build 166, and Kcauldron 152 with no issues so far. 
If you see users using Kauldron build 155 it has many issues with it. 
152 seems to be the most stable and i saw many issues disappear when i downgraded.
That seemed to be the source of the Lag, from the other issue i had posted. 
It also fixed a start up crash, stuck in limbo when dying, and spamming of some error on console.
I can't remember the error thou. Its really an amazing mod. Its so much fun to try to turn that anomaly into a reactor. I call it my baby. I need to feed it, burp it, and eventually it will grow up big and strong and make me proud.

**Comment by Badcholo** [comment]
i created a better issue.
