### ISSUE TITLE
Maybe crash?

### ISSUE THREAD

**Issue by Badcholo** [simeonradivoev/MatterOverdrive#264]
I broke a steam dynamo and there was a hopper above it. when i broke the dynamo the hopper broke by itself and caused the server to crash. any idea if it is related to your mod?
i have a anomaly far below it. 
http://pastebin.com/dwtZ3xbJ
Sry, i accidentally pressed the submit button.

**Comment by shadowfacts** [comment]
![](http://puu.sh/kDsWZ.png)

Uhm...

**Comment by simeonradivoev** [comment]
Yes !

**Comment by Badcholo** [comment]
oops..

**Comment by simeonradivoev** [comment]
What was in the Hopper ?

**Comment by Badcholo** [comment]
nothing

**Comment by Badcholo** [comment]
i had placed in coal, but it had all been put into the engine

**Comment by simeonradivoev** [comment]
I't doesn't seem to be connected to Matter Overdrive. The error actually comes from vanilla minecraft.

**Comment by Badcholo** [comment]
ok. i can't reproduce it in SSP or SMP. ok i'll let you know if i can get it to happen again. 
Very strange, very...
prob, cauldron again...
