### ISSUE TITLE
Use of Phaser Rifle causes extreme lag in SMP. 

### ISSUE THREAD

**Issue by AHrubik** [simeonradivoev/MatterOverdrive#265]
Client side everything seems fine. Graphically the rifle appears to function normally till you go to interact with something in the world. Extreme lag is then noticed. Server side reads as follows.

[21:33:20] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 56700ms behind, skipping 1134 tick(s)
forge tps
[21:34:24] [Server thread/INFO]: Dim 42 : Mean tick time: 0.141 ms. Mean TPS: 20.000
[21:34:24] [Server thread/INFO]: Dim -112 : Mean tick time: 0.046 ms. Mean TPS:20.000
[21:34:24] [Server thread/INFO]: Dim -1 : Mean tick time: 0.039 ms. Mean TPS: 20.000
[21:34:24] [Server thread/INFO]: Dim 2 : Mean tick time: 0.037 ms. Mean TPS: 20.000
[21:34:24] [Server thread/INFO]: Dim -28 : Mean tick time: 1.097 ms. Mean TPS: 20.000
[21:34:24] [Server thread/INFO]: Dim 0 : Mean tick time: 6.947 ms. Mean TPS: 20.000
[21:34:24] [Server thread/INFO]: Overall : Mean tick time: 575.548 ms. Mean TPS: 1.737
[21:34:25] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 65034ms behind, skipping 1300 tick(s)

This is repeatable.

Modpack: Feed the Beast Horizons II:Daybreaker version 1.2.0
Matter Overdrive version: Beta 0.4.0-RC4

**Comment by simeonradivoev** [comment]
I need more info than that. 
1. When does this happen? 
2. Anything interesting in the client logs ? 
3. Does this only happen with the phaser rifle and not the phaser? 
4. What do you mean by interact, like braking blocks or opening chests?
5. Can you fire the rifle without lag ?

**Comment by AHrubik** [comment]
1. Anytime the rifle is used.
2. I will check this evening and report back.
3. Yes. Only the Phaser Rifle is demonstrating this behaviour. The hand Phaser is working as expected. 
4. Anything.
      Client side: Opening a bag. Opening a door. Anything requiring input from the server.
      Server side: Console stops responding to input. You can see by the time stamp it took a full minute to respond to the "TPS" request. The server task manager does not show any unusual CPU usage or RAM usage. During this "pause" the Java process was humming along around 30% usage. The Java process did drop to around 19% usage after getting through the pause indicating there was some added processing going on during the issue.
5. Client side the rifle appears to work exactly as expected. Even after the server has stopped responding to input. There were never any indications anything was wrong until I attempted to interact with something requiring a response from the server.

**Comment by simeonradivoev** [comment]
I think I know why this might be happening. I implemented Latency Compensation. That might be causing the problem. I will add a debug message to the log to see if that might be causing the problem.

**Comment by simeonradivoev** [comment]
5ca027e0cfed9e7f8343c36d5243b766588b3891. The Jekins build is down for now. But should be online soon. You have to download the 117 build and then fire the phaser and send me the server log.
You can download the builds from http://simeon.co.vu/Mods/MatterOverdrive/builds/

**Comment by AHrubik** [comment]
I copied our server to my local machine. After using the new build on the local server I was unable to replicate the problem. Even after switching back to using the old build on that local server I was unable to replicate the problem.  I am still able to replicate it with the current RC4 version included with the FTB Horizons II: Daybreaker mod pack running on our server.

I will try to run the new build on a copy of the pack running on that server to see if network latency has any play in the equation.

**Comment by simeonradivoev** [comment]
Should be fixes since 9a55e0f5ba9475fb0f89cc28d7a0731763c5a696
