### ISSUE TITLE
Feature Suggestion: Enchantment or Baubles Gravity Belt

### ISSUE THREAD

**Issue by Badcholo** [simeonradivoev/MatterOverdrive#266]
I'd like to see a enchantment or Baubles Item that completely removes the 
getting sucked into the anomaly. In my modpack lots of mobs spawn and it's hard to fight mobs while wearing that thing or having to swap it in and out. Also even while wearing the space-time equalizer at 75 block up high and away from it, i still feel the effects and that really sucks.
It would be nice for something that would completely remove the effect like an enchantment or even better a baubles belt, ring or even necklace. Loving the mod by the way..

**Comment by Badcholo** [comment]
I did see the config option to turn off pulling in entities, but i'd hate to have to do that. It's one of it's coolest features.

**Comment by simeonradivoev** [comment]
There is a config to disable entity pulling and block destruction.
It's in the "server" category in "gravitational_anomaly" as "gravitational pull".
I made the armour to be uncomfortable for a reason. The only way to cancel the effect is through the Android ability. This makes the gravitational anomaly hard to handle, because of its OP nature. It produces a lot of energy for basicly some cobblestone converted as matter.

**Comment by Badcholo** [comment]
I was able to place it in a maximum compact machine and transfer power out from it. It's very well contained now. I understand what you are saying, but even if it very expensive, such as making the the stabilizers incredibly expensive. such as requiring ender eggs or nether stars. 
Maybe even requiring the space-time equalizer to require something incredibly expensive.
After all that work I would like to keep this mofo contained.
Maybe make the ore more rare. kinda like shiny metal from TE.
Only way to get that metal is as a secondary from the pulveriser.
Maybe you can create a metal as such that can only be made with matter.
At a high power and matter price.

Wait, did you say, you can negate the effect from just being an android?

**Comment by simeonradivoev** [comment]
Yes, there is an Android Ability that negates the gravitational anomaly.

**Comment by Badcholo** [comment]
Nice!!, thats all i need, this issue can be closed
