### ISSUE TITLE
Phasers Drain Rapidly w/ Powersuit

### ISSUE THREAD

**Issue by DarkLordIce** [simeonradivoev/MatterOverdrive#271]
When wearing a Power Armor from MachineMuse's Modular Powersuits, the phasers appear to try and transfer their power to the suit (acting like a battery would) and drain very rapidly.  Passive energy use from the suit is enough to drain them faster than an ender IO wireless charger can keep up with.

**Comment by simeonradivoev** [comment]
Yes this was fixed in 0b40367a0fc8e65b6191a5aa949c976caf0c9c72. I don't think the fix is in the latest 0.4.0 RC4 hotfix 1. But you can try the dev builds here http://simeon.co.vu/Mods/MatterOverdrive/builds/
