### ISSUE TITLE
Feature Suggestion: Android Player Respawns With .....

### ISSUE THREAD

**Issue by Badcholo** [simeonradivoev/MatterOverdrive#273]
On my Server When a player dies he respawns with only 1 1/2 hunger bars as a punishment for dying.
When a player dies on my server they do not get full hunger to prevent players from just dying to fill their hunger bar instead of looking for food. Also on my server when a player runs out of hunger bars they instantly die.

Suggestion: Possibly a Config to change: an Android player from spawning with a full battery vs a very low battery.

Suggestion: Config to change: Instantly dying from reaching 0% battery as an Android Player.

**Comment by simeonradivoev** [comment]
Shure, not a problem. I made it so that the player spawns with a full battery to prevent the player from dying again and again if there is no charging station around his spawn.

**Comment by Badcholo** [comment]
Yes, i want my players to die. My modpack is designed for MLG Pros or as i like to call em
Mojangsters.

**Comment by simeonradivoev** [comment]
Fixed in d719450d0064ff916cf88b5dedce4a75dff62fee. You can now specify the amount of Charging done on respawn.

**Comment by Badcholo** [comment]
I just read my comment and it sound so harsh. lol.
