### ISSUE TITLE
Galacticraft space + Android Oxygen requirement

### ISSUE THREAD

**Issue by DarkLordIce** [simeonradivoev/MatterOverdrive#274]
As an Android I am able to suffocate while in galactic-craft no oxygen environment!
This mod is awesome btw, as a huge Star Trek fan I'm blown away.

**Comment by simeonradivoev** [comment]
This should be fixed in 8a922b4018c88151de80a65695d3deb2d05118d0. What version of the mod are you using ?

**Comment by DarkLordIce** [comment]
Looks like 1.7.10-0.4.0-RC4-hotfix1
Included in http://www.technicpack.net/modpack/nuts-and-bolts-alpha.561420
Seems we have an outdated build, between this and the one I posted yesterday.  I'm sure they'll update it if I inform them!

Thanks for your help!

**Comment by simeonradivoev** [comment]
I'm working finishing the first Release version of the mod, but first i need to iron out some bugs and performance issues. There are always the dev builds, but they are not as stable as the beta versions.
