### ISSUE TITLE
Feature Suggestion: Warp Core

### ISSUE THREAD

**Issue by Badcholo** [simeonradivoev/MatterOverdrive#275]
Maybe we can Capture a Anomaly and turn it into a Warp Core. The warp core can be used to power your base but requires a constant supply of coolant and matter. Coolant can be made from ice, snow or water and the coolant type would determine how hot the core can get before it explodes, thus making it exciting to gain maximum RF output without making it blow.
It would have a temperature bar and a coolant tank to keep full. Higher temperature = more coolant used or better quality coolant.

Capturing an anomaly would be like ghostbusters capturing a ghost. Stabilize the anomaly with 5 stabilizers and under the anomaly place a containment device.

The containment device with the captured anomaly would produce a Contained anomaly.

Contained anomaly would be used to spark the plasma in your warp core to jump start it.

Warp core needs to have a force field around it or it will damage players. wither maybe,
Force field takes X amount of energy to keep active. Once the core temp is high enough it would produce excess RF to devices or Energy cells.

That's all i got, just spitting ideas, no worries if you don't like em. seems to kinda fit in with the mod.
![warpcore pic](https://cloud.githubusercontent.com/assets/10932905/10623376/4ab96770-7743-11e5-851d-ef24c638423a.jpg)

**Comment by Badcholo** [comment]
A force field seems to fit in too. something to protect your starship. players can create a starship base in the sky and protect it with a force field.
![enterprise-a-5000_4579823](https://cloud.githubusercontent.com/assets/10932905/10623536/a96c44b2-7744-11e5-89c5-a94084378e6e.jpg)

**Comment by shadowfacts** [comment]
[Warp Cores](http://memory-alpha.wikia.com/wiki/Warp_core) do not have anything to do with black holes/gravitational anomalies, however I could see matter/antimatter reactor being a method of energy generation.

**Comment by Harkole** [comment]
I believe the Romulan Starships use a singularity drive instead of a warp core, although if the lore exists about how it works I'm not sure.

A multi-block core for holding plasma (technically a warp core) that can be fed to the replicators and/or reactor control rather than having the decomposers as part of the structure would be good. My problems with the Reactor is that I over-feed the singularity and then struggle to pipe items in/energy out even with 6 stabilisers.

Even my small reactor has a gravity pull of over 22 which makes it painful anytime I go near that area. I tend to rely on some form of Tesseract to allow me to send/receive.

**Comment by Badcholo** [comment]
the player android has an ability to remove the anomaly pull.
i haven't tested it yet, but i think it removes it completely.
i aggree the pull extends quite far.

**Comment by Harkole** [comment]
The Singularity Chest piece (and the separate Android upgrade) both negate the effect for the player totally. It doesn't stop the actual affect on items (both blocks and entities) and can and usually will break cables long before it becomes an issue for the reactor blocks this prevents over powered reactors I guess but then people would just build Big Reactors or equivalent "something".

**Comment by Badcholo** [comment]
There is a config to remove the pulling of entities and destroying of blocks.
Just turn those off and make it as big as you want. I don't know why you would want to, but that's up to you. Do you have a dual fusion reactor on that 1 singularity?

**Comment by Harkole** [comment]
I didn't know you could have more than one Reactor, but my Singularity is actually only 0.54 in size so I'm guessing I couldn't put a second on yet any way.

I don't want to turn off the pull as otherwise it's almost free energy with no downside. I wonder if it would be possible to implement a gradually increasing pull and break strength rather than linear?

**Comment by simeonradivoev** [comment]
You can but more than one Reactors near the anomaly.
As for the pull I don't quite get what you mean by "a gradually increasing pull".  Linear increase is a gradual increase. I tried a realistic gravitational pull but it's dependent on the distance squared. That means that the gravitation pull decreases real fast when you get further from the anomaly.

**Comment by Harkole** [comment]
That was what I meant, a more realistic gravity pull. Going to do more
experimenting with the reactors tonight. The other thing I have noticed
that is annoying for me is the stabilisers have to fitted inside the
reactor ring again adding to the annoyance of the gravity pull when you
want to see how the feeding is going etc

**Comment by simeonradivoev** [comment]
No they don't have to be. The stabilizers have a radius of 64 blocks. The fusion reactor can be placed above and below the anomaly. The center of the anomaly can be left unblocked. The further away you put the fusion reactor the less energy it generates.

**Comment by Harkole** [comment]
Thank you, I seem to have missed a fair bit of information on the reactor.
Will have a play about with it tonight

**Comment by Badcholo** [comment]
I thought that you could only place 2 fusion reactors on the anomaly due to the positioning.
I'll have to play with it too to see what is possible. 
Any way to make stabilizers stack? Like if you place one in front of the other they put out twice the power to contain the anomaly? I'm still looking for something to use all this power on. 
I have setup the fusion reactor to hold 100mil RF and like 25k matter.
I have just been pumping in cobble..
Maybe the stabilizers should use X amount of power and coolant?

**Comment by simeonradivoev** [comment]
You can build Fusion reactors as far as 3 block up and 3 blocks down. The only condition is that the gravitational anomaly must be in the center. The Fusion reactor can also be placed vertically, that means you can create a ball of reactors. 
As for the stabilizers. You can't stack them, they are blocked by anything solid placed in front of them. You can place only glass in front of them. In the beginning stabilisers were planned to have power (you can even see now that they have an energy storage), but that would make the anomaly even more scary and hard to deal with.

**Comment by Badcholo** [comment]
I'm duping ores right now with the replicator. I really like it. so can i dupe anything that has a matter value? how does it know how many it needs to analyze before it gets the pattern?

**Comment by Badcholo** [comment]
That is so nice!

**Comment by simeonradivoev** [comment]
The matter analyzer analyses items by 20%.

**Comment by Harkole** [comment]
Placing a reactor Vertically is that done by rotating the machine block or just by building it that way and ignoring the white blocks? I presume this means that a single block can be shared by more than one multi-block structure or am I missing something?

**Comment by simeonradivoev** [comment]
The reactor has to be rotated. The guide blocks will be rotated as well. The reactor can share more than one multi block structure.

**Comment by simeonradivoev** [comment]
I made the gravitational pull more realistic. It seems it didn't have that big of a difference.
c804dd3419e42f5d943f9eae634cbee26e8f306d

**Comment by Harkole** [comment]
Happy to test the new build if you like?

**Comment by simeonradivoev** [comment]
go right ahead

**Comment by Harkole** [comment]
At work currently should be home and have the new update installed in the
next 6 hours, will report back then :)

**Comment by Harkole** [comment]
Loving the new gravity pull, much better in my opinion! it's slow and annoying but not in the way at distance but it's extremely dangerous if you miss-handle the singularity.

I was also testing Reactor layouts, had a 3 x 3 ring build around it which was nice. Combined output of the 6 reactors was 26,000 rf/t approximately.

I did notice a bug with the top ring reactor, it was flicking between 4% and 100% internal charge, the other connected Reactor Controllers were working normally slowly charging up, also all linked Matter Decomposers were randomly flicker values too (not in the video - although the video shows them not working as expected, they surely should of flashed from top right to bottom left based on input as they were when in a line and networked in?).

Removing the Decomposers from the reactor ring and having them side by side and then networking them in to the reactor controller stopped the flickering of matter between theme

This is from dev build 130.

Video of the GUI bugs - https://youtu.be/Sl43WEstaCc [I've just uploaded it but it should have a 720p res eventually.]

**Comment by simeonradivoev** [comment]
The flashing of the Matter Decomposer is totally normal. When they have matter the block icon changes. When they are emptied then they change to the empty block icon.
The Gui flashing of the reactors is quite peculiar.

**Comment by Harkole** [comment]
I should maybe capture the Matter Decomposer on video too, it's transferring 322 matter between those two machine ever second or so, nothing is actually in the machine... hang on (prepare for edit with another link! :) )

**Comment by simeonradivoev** [comment]
Ah yes I see the problem.

**Comment by simeonradivoev** [comment]
Fixed in 794687f6a130ad4a552f4005950caf3016f33393

**Comment by Harkole** [comment]
Thanks @simeonradivoev , downloading and dropping it in now, also is there two new blocks Matter Tube and Tritanium Plate Guided are they useful or just decorative?

**Comment by Harkole** [comment]
OK so new testing with setting up a new hole, with the new Newton law in use it's impossible to feed the singularity. Is there some kind of ability to just have items in the same block absorbed without doing  an actual entity collision test?

Everything I try feed it just gets flung out but 10-20 blocks currently

**Comment by simeonradivoev** [comment]
I'll look into it.

**Comment by Harkole** [comment]
thank you, the mod is brilliant I hope I'm not coming across as anything but enthusiastic!

**Comment by simeonradivoev** [comment]
Ah yes. How interesting. I even forsee a crash. If an item reaches 0 distance, is right in the center, then a devide by 0 occurs just like in real life :laughing: the center of a black hole.

**Comment by Harkole** [comment]
hmmm, how's this for an enhancement?

Super massive singularity (machine to force it larger or just fed to be large) minimum size would be two blocks that you can then use to teleport items/player to another location (in effect wormhole travel). Problem I see with this is how to generate the end point, should it be stable and what cost in game terms should there be to travel...

**Comment by simeonradivoev** [comment]
I'm planning on adding antimatter and wormholes. To implement with transporters and interdimensional travel.

**Comment by Harkole** [comment]
I'm still overly excited to see what you implement with the star map, now you give me this to wait on too. lol :+1:

**Comment by simeonradivoev** [comment]
Ah yes the starmap is quite the feature to implement.

**Comment by Harkole** [comment]
Is there a chat channel or something I can join rather than spamming your issue board?

**Comment by simeonradivoev** [comment]
We have a IRC channel on http://esper.net/ called #matteroverdrive

**Comment by Badcholo** [comment]
Ima close this issue since it's gotten kinda long.
