### ISSUE TITLE
Android Crash on Tick Entity Event

### ISSUE THREAD

**Issue by Harkole** [simeonradivoev/MatterOverdrive#276]
I'm struggling to recreate the issue on demand but occasionally I can crash the game with a OnTick event error. Appears to be related to wearing Magic Crops [4] armor and when trying to interact with doors or chests.

Apparent fix is to install PlayerAPI-1.7.10-1.2.

Posting this here to help others with similar errors as I don't believe it's MatterOverdrive that is at fault.

Similar to and possibly the same issue as #210 - apologies Simeon should of checked the posts before making this one, the log pasted in that issue looks very similar to the one I believe I've got at home.

**Comment by simeonradivoev** [comment]
Do you by any chance have the logs ?

**Comment by Harkole** [comment]
I've got them at home, just on lunch and didn't want to forget to do this - appreciate this isn't the most helpful post I'll update them tonight (hopefully in about 6 hours).

**Comment by Harkole** [comment]
Crash log is different to #210 - although turns out whilst I did download the RC4 hotfix 1, I never applied it to game. Will attempt to recreate the issue tonight. However below is the original crash log for this event.

http://pastebin.com/fp6L2Jky

**Comment by simeonradivoev** [comment]
Fixed in 3cc5a59208a37263145e9c8f8ab6d469112e6056
