### ISSUE TITLE
Android bonus missing when returning from the End

### ISSUE THREAD

**Issue by Harkole** [simeonradivoev/MatterOverdrive#277]
When going to the end the bonus for health/speed/experience upgrades are shown correctly, however when returning everything is reset to stock levels and you have to log out/in to get the correct values to show.

No errors are generated in the log that I've found and attempts at using the android station to remove the extra parts and replace them fail to trigger their update stats. Let me know if you need anything else for this one.

**Comment by simeonradivoev** [comment]
what version of the mod are you using ?

**Comment by Harkole** [comment]
RC4-1 updated it 2 nights ago.

**Comment by Harkole** [comment]
Just an update, this actually happens on arriving at the End as well as returning from the end. I decided to test this going to the nether and it also seems to reset the Android stats - I've not got any other dimensions available/installed at this time but it would appear to be any World change isn't getting the new stats.

**Comment by Badcholo** [comment]
nice!, been waiting. I'll update and test as soon as the build comes out.
