### ISSUE TITLE
Possible Mod Conflict - Able to walk through machine as Android

### ISSUE THREAD

**Issue by Harkole** [simeonradivoev/MatterOverdrive#278]
Mod Conflict with Crusher machine from Mekanism. As an Android I'm able to walk through (and not stand on to) the Mekanism Crusher machine. Cross posted on Mekanism GitHub Issue as #2998

Matter Overdrive Version RC4-hotfix1

**Comment by shadowfacts** [comment]
Can you post the `fml-client-latest.log` from when this happened?

**Comment by Harkole** [comment]
This is a cut down log from tonight, I recreated the issue briefly between 00:05 and 00:06, started the world went to the machine broke it form it's existing location and moved it to ground level. placed it and took three attempts to walk through it, tried for another minute or so to recreate it before shuttin down without interacting with anything.

http://pastebin.com/TQ6qy9ks

**Comment by shadowfacts** [comment]
o_O Can you try to reproduce this with other blocks (Vanilla & modded)?

**Comment by Harkole** [comment]
Will do tomorrow when I get on, only noticed it with the crusher machine so
far though and been on that works a good 10-12 hours worth of play. It's
not a major issue as it does crash the game or break anything else just
odd! :)

**Comment by shadowfacts** [comment]
Won't be an issue for 1.8.
