### ISSUE TITLE
Crash when placing tritanium glass

### ISSUE THREAD

**Issue by 1skandar** [simeonradivoev/MatterOverdrive#279]
http://pastebin.com/E9NWgtFx

World need to be world edited to remove the offending block before it can be loaded again.

**Comment by shadowfacts** [comment]
Oh god, I'm sorry, this has been on my todo list for months now >.< fixing it now.

**Comment by 1skandar** [comment]
No worries, these things happen. Thank you for your quick response.

**Comment by shadowfacts** [comment]
Once the CI finishes, you'll be able to use build 127 (download [here](http://simeon.co.vu/Mods/MatterOverdrive/builds/)).

**Comment by 1skandar** [comment]
Thank you. I was pushing an update to my pack anyway, this will fit in nicely. I appreciate the timely fix.
