### ISSUE TITLE
Issue scanning

### ISSUE THREAD

**Issue by zarkophine** [simeonradivoev/MatterOverdrive#28]
So when i am trying to scan blocks it will not scan or will keep scanning the same block with no results no increase in progress. it will also prevent me from moving on to other blocks to scan.

**Comment by simeonradivoev** [comment]
The scanner must be linked to a Pattern Drive, and will display chat info messages. The scanner can also be used to display information on a block, without needing to be connected.

**Comment by zarkophine** [comment]
Yes it was linked to a pattern drive with empty drives i was trying to scan more patterns. The mobile scanner would not scan them. no message no nothing.

**Comment by simeonradivoev** [comment]
what exactly were you scanning ?

**Comment by zarkophine** [comment]
i had already scanned dirt, grass block, Diamond block, poppy's, dandelions, sun flowers. I then was trying to scan diamond ore blocks, coal ore block, redstone ore block, glass, oak logs, lapis ore block, oak wood planks. Non of which will scan . . .
