### ISSUE TITLE
Shift click: gone

### ISSUE THREAD

**Issue by Badcholo** [simeonradivoev/MatterOverdrive#282]
When i sometimes shift click an item in the matter analyzer it dissapears. It's just gone.

**Comment by simeonradivoev** [comment]
Is this only in SMP ? What version of the mod are you using ?

**Comment by simeonradivoev** [comment]
Also you have to check if the item isn't an upgrade or a network filter. These items will go into their slots even if you don't see them. You can check the other GUI tabs.

**Comment by Badcholo** [comment]
It was a Medic kit from Medicraft. I have only tried this in smp and it was build 117.
I have just upgraded to 130, i noticed it has happened a couple of times. 
I will check the other tabs

**Comment by Badcholo** [comment]
It did go into a different tab. 
Destination address filter {  } slot.
