### ISSUE TITLE
Items in Machines don't drop when broken

### ISSUE THREAD

**Issue by Badcholo** [simeonradivoev/MatterOverdrive#283]
This may be a duplicate.
When i break a machine the items inside the machine are destroyed. such as a Matter Scanner.
They don't drop and they don't stay in the machine.

**Comment by Badcholo** [comment]
When adding items to the matter registry do i need to add them to the client also or can i just add them to the server?

**Comment by Badcholo** [comment]
Is it normal for the decomposer to allow oak logs but not birch logs? I see a lot of items that have matter value but are not allowed to be decomposed. Any way i can add them?

**Comment by simeonradivoev** [comment]
The decomposer allows all blocks with matter. You have to check if the secondary output is empty. The item will not be processed if the secondary output has matter dust with different matter amount.
The server sends the matter registry to all clients.
Is the braking of the machine only in SMP ? 
What version of the mod are you using ?

**Comment by Badcholo** [comment]
upgraded to 130 version.
decomposer fixed, 
items dropping fixed
thanks for the being able to add matter registry to items.
