### ISSUE TITLE
Crashed when holding the Scanner

### ISSUE THREAD

**Issue by Badcholo** [simeonradivoev/MatterOverdrive#286]
I was holding a scanner and i pressed the Backslash button to see what happens.
http://pastebin.com/sP2NZqpd

**Comment by simeonradivoev** [comment]
The crash seems to come from Twisted-Tweaks.

**Comment by Badcholo** [comment]
I'll look into this.

**Comment by Badcholo** [comment]
Did something break? I had a matter replicator, a analyzer, a terminal, and a pattern storage connected all together on a network and it worked nicely. 
even in a new world i can't get the network switch to connect the pattern storage and matter replicator on the same network. 
It seems to be the network switch isn't allowing the machines to connect to it.
![2015-10-23_12 32 36](https://cloud.githubusercontent.com/assets/10932905/10703095/8bffc24c-7982-11e5-8136-c06669642319.png)

**Comment by simeonradivoev** [comment]
The network switch's GUI isn't accurate. Do the machines work ? Are their redstone settings right ? You have to check the config page and see if the redstone setting is on low or disabled.

**Comment by Badcholo** [comment]
![2015-10-23_12 37 43](https://cloud.githubusercontent.com/assets/10932905/10703139/e7a61f6a-7982-11e5-88d6-798c340411cb.png)

This is in SSP in a new world.
I have 4 machines just like i did before, but they won't connect now. 
I have tried changing the redstone settings to disabled and also high with torches.
The machines do work, but i can't craft anything from the pattern monitor to the replicator.
When hit refresh it doesn't show my gold ore i analyzed.

**Comment by simeonradivoev** [comment]
Mine works fine. Maybe try the latest build.

**Comment by Badcholo** [comment]
The analyzer does nothing since it can't send the data to anything.
The pattern storage sends no data to the Pattern monitor so nothing shows up.
The pattern storage on my survival world when it did have a connection to the pattern storage did not send data to the Replicator.
I'm using build 130.

**Comment by Badcholo** [comment]
I'll look into where the issue is.

**Comment by simeonradivoev** [comment]
do you remember when exactly did the problem occur. From what version to what did you change.

**Comment by Badcholo** [comment]
i changed from version 117
I just updated to version 130

**Comment by Badcholo** [comment]
![mod list](https://cloud.githubusercontent.com/assets/10932905/10703397/c7f48808-7984-11e5-993c-9cfa8045d987.PNG)

**Comment by Badcholo** [comment]
Removed twisted tweaks and it does remove the crash when i backslash.

**Comment by Badcholo** [comment]
http://www.technicpack.net/modpack/mojangsters.583708

This is my modpack. I removed all the mods and in removing some mods, it seemed to get fixed, then it happened again, then the pipes were all wacky, not connecting to each other. It is very confusing and hard to find what works. I have completely removed all mods xept for 
CoFHCore-[1.7.10]3.0.3-303
MatterOverdrive-1.7.10-0.4.0-RC4-build-130

Still had issues with just the 2 mods, but i finally broke the switch and replaced it while all the pipes were there and it connected to all of them. Finally got it to work but removed all the mods does not really mean much. 

I haven't been able to get it work on my server, but i'll leave it as it is for now.

**Comment by Badcholo** [comment]
Build 137 has fixed the issue of the matter network switch not letting the machines connect together.
In the switch GUI it still doesn't show that it is connected and the machines all were set to redstone signal high. It works after changing the redstone signal set to disabled and breaking and replacing the network switch.
