### ISSUE TITLE
Enhancement of Reactors

### ISSUE THREAD

**Issue by Harkole** [simeonradivoev/MatterOverdrive#287]
Reactor Ring with an input (for matter) and output (for power) block, these blocks should be able to feed any connected reactor ring allowing for easier construction of a 3x3 ring.

currently the only way to achieve this is to have the Matter Decomposer in the ring it's self (requires 12 of them) or to have a network cable attached to each Reactor Controller, which also requires a connection for power for each one too, as the top and bottom sides are blocked by other Reactors and left and right sides are occupied for the construction of the ring this only really leaves the front and back of the reactors to get the power out and material in (which does work). However single ports for the entire ring would promote construction of this true end game object and make the dangers involved with working with the Grav. Anom's worth the extra material to build a full 6 ring system. 

![image](https://cloud.githubusercontent.com/assets/3703699/10706766/d40b7d56-79e1-11e5-99e3-1d2e0de1b2cb.png)

**Comment by simeonradivoev** [comment]
Added in 378c95da5e72f7045a8ecec2a9fe10fc72f4e24c
