### ISSUE TITLE
Can't add matter values for many ProjectRed items/blocks due to '|' character in unlocalized names

### ISSUE THREAD

**Issue by Mysteryem** [simeonradivoev/MatterOverdrive#288]
I tried giving basalt cobblestone (and many other ProjectRed blocks/items) matter values.

So for basalt cobblestone, this is ```I:tile.projectred.exploration.stone|2=1``` in the matter overdrive config. But this causes the following exception https://gist.github.com/Mysteryem/f3167eadf5eed01ad1a3

**Comment by simeonradivoev** [comment]
why did you add the | ?

**Comment by Mysteryem** [comment]
It's part of the unlocalized name, see the en_US.lang for project red here https://gist.github.com/Mysteryem/bb7f6e7634cf9b08f04a

**Comment by simeonradivoev** [comment]
Ah I see. The name from project red's block is "tile.projectred.exploration.stone|2". There's nothing i can really do about that. It's a limitation of Forge's config system.

**Comment by simeonradivoev** [comment]
did you try adding "" to the name ?

**Comment by simeonradivoev** [comment]
I:"tile.projectred.exploration.stone|2"=1

**Comment by Mysteryem** [comment]
I'll give it a go

**Comment by simeonradivoev** [comment]
You can also use the command ingame to register the item stack you're holding.
/matter_registry register itemstack

**Comment by Mysteryem** [comment]
Using quotation marks has worked.

Might I suggest adding a line similar to ```If the unlocalized name contains characters that are not alphanumeric and are not "-", "." or "_", the name must be surrounded in quotes like I:"tile.projectred.exploration.stone|2"=1``` to the configurations guide http://simeon.co.vu/Mods/MatterOverdrive/configurations-guide/

**Comment by simeonradivoev** [comment]
done :3
