### ISSUE TITLE
Feature Suggestion: Config to disable Android Sinking in water.

### ISSUE THREAD

**Issue by Badcholo** [simeonradivoev/MatterOverdrive#291]
I decided to turn into an android and i can't cross a river. I sink to the bottom and i can only dig down. This makes it very difficult to get clay cause the clay is at the bottom of the rivers. An ability to not sink, swim faster and mine underwater faster would be really nice and useful.

**Comment by simeonradivoev** [comment]
There is an ability to not skink.

**Comment by Badcholo** [comment]
Oh,sorry, I hadn't checked the abilities for a while. Thank you..
