### ISSUE TITLE
As Android, sneaking causes to discharge RF powered items in hand

### ISSUE THREAD

**Issue by artubi** [simeonradivoev/MatterOverdrive#297]
Hi,
I have a Issue while being an Android. Sneaking (holding Shift) while holding RF powered item causes to drain (discharge) them. This is a huge issue because it renders a lot of RF powered tools useless. Especially those with small capacity.

Tested:
MatterOverdrive-1.7.10-0.4.0

Steps to reproduce:
1. Become an Android
2. Use battery as main source power*
3. Drain it a little
4. Select RF powered item
5. Press and hold Shift
6. You should see that your energy level is increasing while item in your hand is discharging
*use some low capacity battery, it's easier to see it

I haven't saw anything about this in config, so I'm not sure whether this is a bug or it is intentional. However, this makes being Android really irritating since you can't use your RF powered tools / items without making them useless. Main example is Redstone Arsenal, pressing Shift on one of the tools immediately drains (discharge) them. Also, there are few item that aren't affected, mainly being Phaser, Pulse Rifle, Omni Tool.

I'd like to ask you:
Is this a bug or it is intentional?
And if it is intentional, please, could you add a config option to disable this?

**Comment by Badcholo** [comment]
I think it's ment so you can charge your android batteries without having to use the charging station.
I don't see a big issue, just use a capacitor and increase your android battery. Most items can't be used for long without a capacitor anyways.

**Comment by simeonradivoev** [comment]
It's not a bug It's suppose to be a feature. I will add a config option to disable it.

**Comment by artubi** [comment]
I wanted to get rid of some lava and didn't wanted to use BC pump. I'm using TE Magmatic dynamo as current power generator. So that why I don't want to waste lava. I got myself a TE FluiVac and tank. There was a pool of lava that I wanted to get rid of. Came to the edge of the block next to lava and used sneak to avoid falling down into it. Second later, my FluiVac is "dead" (discharged). Came back to base, recharged it, got back at lava pool, sneaked to the edge of the block, FluiVac is "dead" again. After three times of repeating this, I've found about this.

I mean, it's not bad feature, in fact it's excellent idea. However, the way it currently works is, well... kinda imperfect (in my opinion).

I guess this might be a bit silly, but what about to create:
white/blacklist for items that you can/can't use to charge yourself
some sort "portable charger", you know, like the android and weapons can hold any kind of RF battery, it would work same way; place any kind of RF battery into it and when held, it will charge you

**Comment by simeonradivoev** [comment]
a blacklist for android charging items is unnecessary. I will and the config option to disable it for now and maybe add a portable charger in the future, or I might even scrap the whole charging while holding a battery. It was a temporary solution until I added a way to charge androids without swapping batteries and now I have the Charging station.

**Comment by Badcholo** [comment]
The charging station works great and is not that hard to make. I would suggest it hold maybe 1mil RF just in case your power source is not stable yet. I would just scrap it.
