### ISSUE TITLE
Holographic sign recipe issue

### ISSUE THREAD

**Issue by 1skandar** [simeonradivoev/MatterOverdrive#298]
I'm not sure what the recipe is supposed to be but the 3 glass at the top row isn't taking vanilla glass or glass panes or MO Tritanium glass. The only glass they are taking in my current pack is Essential Craft Magical Reinforced glass, which I'm fairly sure isn't intended.

**Comment by simeonradivoev** [comment]
what pack are you using ?

**Comment by 1skandar** [comment]
Modular Mayhem: http://forum.feed-the-beast.com/threads/1-7-10-modular-mayhem.120584/

**Comment by 1skandar** [comment]
I think I see the problem. From the MORecipes:
addRecipe(new ShapedOreRecipe(new ItemStack(MatterOverdriveBlocks.holoSign), "GGG", "g0g", " T ", 'G', "glass"  

If I'm reading that right the recipe is calling for anything with e the oreDict of "glass".  However, vanilla glass oredict is blockGlass

**Comment by simeonradivoev** [comment]
It should be glass as well. But I will change it and see if that fixes your problem.

**Comment by 1skandar** [comment]
I just checked in a vanilla instance of Minecraft (well, vanilla plus NEI and NEIIntegration). I dumped the preDict and there is no "glass" oreDict entry. There is blockGlass for glass and paneGlass for glass panes.

**Comment by 1skandar** [comment]
And yeah, Forge does not natively add the "glass" oreDict to glass. See here: http://www.minecraftforge.net/wiki/Common_Oredict_names
