### ISSUE TITLE
Crash with "Dimension -17"

### ISSUE THREAD

**Issue by webmilio** [simeonradivoev/MatterOverdrive#303]
I recently installed MatterOverdrive on my modpack, which uses forge the .1492 build. For some reason, I can load the game perfectly fine, it's just that every time I load a save, the game crashes after a few seconds.

Here is the crash log : http://pastebin.com/yfbFW31z

**Comment by Badcholo** [comment]
I don't have a dimension 17. I wonder what that is.

**Comment by simeonradivoev** [comment]
The problem seems to come from codechicken's Chunk Loaders not Matter Overdrive

**Comment by webmilio** [comment]
Any idea why this crash only occurs with MatterOverdrive present?

**Comment by Badcholo** [comment]
do you have a full crash report?
update forge? clean install client and server?
what other mods are present? modpack?
version?

**Comment by webmilio** [comment]
Here is the [full crashlog](http://pastebin.com/JD0tZEcR). Not cut, not edited, nothing. I updated Forge to the latest build (.1541) and the crash still happens.

**Comment by simeonradivoev** [comment]
still no idea why this happens because of Matter Overdrive. Maybe add the issues to their github ass well

**Comment by webmilio** [comment]
It seemed to be caused by ExtraPlanets (addon for GalacticCraft). Sorry for the trouble.
