### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by MeatyLock** [simeonradivoev/MatterOverdrive#304]
Yeah I've looked through all the other issues and couldn't see anyone post a solution that worked. I've tried with COFHCore & COFH Lib. I've tried one or the other. I've also tried older versions of MatterOverdrive & COFH to no avail.

http://pastebin.com/e0C5Kx6R

**Comment by simeonradivoev** [comment]
You need to update your Java to Version 8 or above.

**Comment by MeatyLock** [comment]
It worked fine client side. I forgot to mention this is server side.

**Comment by shadowfacts** [comment]
Update Java on your server to 8 or above.

**Comment by MeatyLock** [comment]
Unfortunately I don't think thats possible. I'll ask my hosting company as they sponsor me.

**Comment by shadowfacts** [comment]
It is possible, there is a server, it is running Java, Java was installed, therefore another version of Java could also be installed. If your hosting company says it's not possible, they're probably just being lazy.

**Comment by MeatyLock** [comment]
Well thats what I mean. I'm not sure if they are willing. I'm asking now. Thank you for your time.

**Comment by MeatyLock** [comment]
Apparently Akliz added Java 8 support already because of Matter Overdrive. My dude just informed me. Thank you guys for the help.
