### ISSUE TITLE
Android hud lag and health meter

### ISSUE THREAD

**Issue by Omegatron9** [simeonradivoev/MatterOverdrive#305]
Can you add a config option to remove android hud lag? I find it hard to look at (and thematically it doesn't make sense anyway since the hud should be part of your brain).

Also, can you add a config option to move the health meter back to the normal position? I thought there was one at some point but I can't find it anymore.

**Comment by simeonradivoev** [comment]
There are config options to move GUI elements around (see the config tab of the android station). You can also lower the amount of lag by wearing a tritanium spine.

**Comment by Omegatron9** [comment]
Is there a way to change the health meter back to the classic style?

**Comment by simeonradivoev** [comment]
No. I will add a config.

**Comment by Omegatron9** [comment]
Thanks.

**Comment by Badcholo** [comment]
How will you know how much power you have as an android without the hud?
Will you still glitch when hit?

**Comment by Omegatron9** [comment]
Presumably the rest of the hud will still be there.

**Comment by Keridos** [comment]
The lag when turning around really is annoying, can we switch that off per config?

**Comment by simeonradivoev** [comment]
Yes you can

**Comment by Keridos** [comment]
What is the config option called, cannot seem to find it.

**Comment by simeonradivoev** [comment]
depends on the version you're using

**Comment by Keridos** [comment]
v0.4.0 from curseforge

**Comment by simeonradivoev** [comment]
Yes you will have to check out the dev builds.

**Comment by Keridos** [comment]
Still not found in latest dev build (186).

**Comment by simeonradivoev** [comment]
it should be in entities > android_player > hurt_glitching

**Comment by Keridos** [comment]
I mean the HUD moving when turning around. For me it is pretty laggy and lags behind.

**Comment by simeonradivoev** [comment]
Ah that can't be disabled for now

**Comment by Badcholo** [comment]
get optifine. i haven't had any problems with it. 
Get version OptiFine 1.7.10 HD C1
Drag and drop it into your mods folder and done.
You don't really need to configure it unless you really have a old computer or a bad video card.
but you can just change the setting ingame like you normally do to video settings, super easy.
make sure you change this setting in the config. ofFastRender:false
Also the config will be in the main directory or your install, such as where your mods folder or server.dat is at. it will be next to your options file called "optionsof"
Optifine config file will not be in the config folder.
If you already knew this hopefully it will help someone else who may be reading this.

**Comment by Keridos** [comment]
Thanks, but its not my FPS that is causing this, the HUD moves around on the screen when turning.

**Comment by simeonradivoev** [comment]
That's what it's suppose to do. But if you have a low fps it might jitter.

**Comment by Keridos** [comment]
It does not make sense to do that imo. Could you maybe add a config option to turn that off?

**Comment by simeonradivoev** [comment]
shure

**Comment by Keridos** [comment]
Thank you :+1:

**Comment by simeonradivoev** [comment]
Since the main feature was done awhile ago I can close it with @Keridos's one
