### ISSUE TITLE
Mod config file changing client-side on load

### ISSUE THREAD

**Issue by Slychocobo** [simeonradivoev/MatterOverdrive#307]
Running MatterOverdrive-1.7.10-0.4.0 Stable

Config file on client seems to change Entity ID's when Minecraft finishes loading up, causing the game to crash when connecting to a server with a different ID set.

This screenshot shows the content of the .conf file (copied from the server to the local client) before starting up Minecraft.
![pre-startup](https://cloud.githubusercontent.com/assets/10496590/10985722/71559388-841b-11e5-8540-67ff2958c65f.PNG)

This one shows the content on the .conf file once MC has finished loading and is on the title screen:
![post-startup](https://cloud.githubusercontent.com/assets/10496590/10985735/a7ebef3c-841b-11e5-8450-38fa9ec86f16.PNG)

This causes a client to crash when attempting to join due to ID mis-match.
(Log attached below)
http://paste.feed-the-beast.com/view/57c72deb

**Comment by Badcholo** [comment]
grab the server config and add it to the modpack.

**Comment by Slychocobo** [comment]
Not sure you're quite understood,  the configuration was copied from the server to the modpack, that's what the first screenshot shows.  

Its getting rewritten by the client on start-up

**Comment by simeonradivoev** [comment]
Matter Overdrive changes the entity IDs if there are any conflicts.

**Comment by Slychocobo** [comment]
OK, But.. if all my configs and installed mods match on both the remote server and the local client then shouldn't the ID's match up?

Otherwise, I fail to understand how this would work.. or how to fix such an issue..

**Comment by simeonradivoev** [comment]
Yes I can see the log. The IDs that Matter Overdrive defaults to are taken on the client. That is very strange. I will add mode debug info so that we can see what exactly takes up the IDs. Maybe try and copy all other mod configs from the server to the client.

**Comment by Slychocobo** [comment]
The configs were copied over fresh just before I launched the client/server combo as above.  I can try a newer/beta version if that will help

**Comment by simeonradivoev** [comment]
What happens when you copy them now ? do the ID change again

**Comment by simeonradivoev** [comment]
You can also try to copy the entity IDs from the client instead.

**Comment by Slychocobo** [comment]
I'm at work currently ;)  I've tried replacing the configuration file and it just reverts back, but I'll try copying the Client side to the server later and see what happens.

**Comment by Slychocobo** [comment]
Replacing the configuration files on the client results in them always being overwritten, however in reverse (copying the confilgs from client and overwriting the server side) seems to have resulted in a much more stable situation.

I'll keep an eye on this issue and report any new information I find.

**Comment by Slychocobo** [comment]
Sorry. Take that back.. It's still creating different configurations on Client/server side after a few restarts no matter what I seem to do..

**Comment by Badcholo** [comment]
Start ripping out mods until you find the one that is incompatible with MO.
Your gonna want to rip your hair out soon enough. 
The Modpack Author Life.

**Comment by webmilio** [comment]
I've had the same issue for a bit, #310, and my config file had gotten overwritten a couple of times. I deleted both side's configs, ran the server and copied it's config to my client and voila, it worked.
