### ISSUE TITLE
Night vision

### ISSUE THREAD

**Issue by thesixler** [simeonradivoev/MatterOverdrive#308]
Night vision effects (the only one i tested was liquid essence night vision) don't work if you're a cyborg. I'm running this on a modified Infinity pack, so fastcraft.

**Comment by Badcholo** [comment]
cyborgs can't have any kind of potion effects. You can disable this in the config, but the server has to do it as well as the client.

**Comment by thesixler** [comment]
haha wow im dumb thanks man
