### ISSUE TITLE
Sound crash with cofh on Madscientist

### ISSUE THREAD

**Issue by b0bst3r** [simeonradivoev/MatterOverdrive#31]
Don't know if you've just fixed this in #30 or not as it's slightly different crash

http://pastebin.com/L75pdbhM

Can you put the new build up or link me to it so I can try please?

**Comment by b0bst3r** [comment]
I've tried it with and without CoFHLib-[1.7.10]1.0.2-160.jar, it shouldn't need CoFHLib though as that's shipped with CoFHCore now.

**Comment by b0bst3r** [comment]
Should also point out that this only happens when you play SMP on a server, it's fine in single player.

**Comment by simeonradivoev** [comment]
Yes i know, I fixed it, Just need to do a new update after I'm done with some new stuff i'm adding.

**Comment by Crumbology** [comment]
any eta on this?  if the new stuff is gonna take long, could we get a bugfix release please?

**Comment by simeonradivoev** [comment]
Just released a bug fix

**Comment by Crumbology** [comment]
Great! thanks a lot :)
