### ISSUE TITLE
A Fatal Error Has Occured

### ISSUE THREAD

**Issue by webmilio** [simeonradivoev/MatterOverdrive#310]
I've recently fixed all the issues I could related to MO's launch, but now, it seems to always kick me out of the game when I join. This issue is similar to #260, except that this is using the latest version of all my mods, including custom builds. I tried running the latest release (0.4.0) as well as the last build (.158) but to no avail.

Server "crash log" (useless): http://pastebin.com/082mXSjR
Client crash log: http://pastebin.com/pm0KHU5T

**Comment by shadowfacts** [comment]
Are the server and client configs the same?

**Comment by webmilio** [comment]
Oh my. It's been so long I've had to check configs that I forgot. Thank you for the fast and accurate answer, good sir :+1: !
