### ISSUE TITLE
Phaser Rifle damage is underwhelming

### ISSUE THREAD

**Issue by 1skandar** [simeonradivoev/MatterOverdrive#311]
A Phaser with a Focusing Matrix does 23 ish damage at full power. A Phaser Rifle with a Focusing Matrix does....4.5? That seems incredibly underpowered, especially as it also takes over 4x the power per shot.

**Comment by Badcholo** [comment]
It would be nice to have a way to configure the damage of each weapon.

**Comment by simeonradivoev** [comment]
I'm working on adjusting the damages. There is even a bug. The phaser rifle does more damage then intended.

**Comment by simeonradivoev** [comment]
I would also need to adjust the range of the phaser. It should be a short range weapon.

**Comment by 1skandar** [comment]
As long as the phaser rifle can do comparable damage I'm perfectly fine with that. Having the phaser do 5x the damage is just pleh.

**Comment by simeonradivoev** [comment]
Fixed in db01813928a6fb573b5aaeb37a065b13992cc3cb
