### ISSUE TITLE
Running Gradlew build fails

### ISSUE THREAD

**Issue by ConvincingName** [simeonradivoev/MatterOverdrive#313]
I'd like to start by saying this is probably an error in my part. I'm not very familiar with Minecraft modding, so please forgive my relative ignorance. For some reason, running gradlew build doesn't work as it's supposed to. I successfully ran git clone and gradlew setupDecompWorkspace, but when I run gradlew build, the progress remains at 0% for an average of about 20 mins, then gives me the "build failed" error. I ran it with --info and the first few errors are: Failed to get resource: GET. [HTTP HTTP/1.1 403 Forbidden: https://libraries.minecraft.net/codechicken/ForgeMultipart/1.7.10-1.2.0.345/ForgeMultipart-1.7.10-1.2.0.345.pom]
Failed to get resource: GET. [HTTP HTTP/1.1 403 Forbidden: https://libraries.minecraft.net/codechicken/CodeChickenLib/1.7.10-1.1.3.138/CodeChickenLib-1.7.10-1.1.3.138.pom]
Failed to get resource: GET. [HTTP HTTP/1.1 403 Forbidden: https://libraries.minecraft.net/codechicken/CodeChickenCore/1.7.10-1.0.7.46/CodeChickenCore-1.7.10-1.0.7.46.pom].
It basically goes on like this for all of the dependencies until it crashes. I will post any more info if needed, but I'm hoping it's just something I overlooked.

**Comment by shadowfacts** [comment]
1. That's weird, looks like dependency resolution is failing, posting the whole log would help.
2. Why do you need to compile your own version of MO? The latest builds from the Continuous Integration server are available [here](http://simeon.co.vu/Mods/MatterOverdrive/builds/).

**Comment by ConvincingName** [comment]
1. The log has been attached. [gradle.txt](https://github.com/simeonradivoev/MatterOverdrive/files/31363/gradle.txt)
2. I want to get into modding and figured that modifying an open source mod would be a great place to start.

**Comment by shadowfacts** [comment]
I have no clue what's going on, it's probably something on your end because it works fine for me. As for learning modding, I suggest you take a look at Pahimar's Let's Mod Reboot series and MineMaarten's Advanced Modding series. They'll be a better entry point into modding than a pretty advanced and complicated mod.

**Comment by ConvincingName** [comment]
Thank you for all the help and modding advice. I probably overlooked something with gradle, so I'll start from something more basic.
