### ISSUE TITLE
Taking random damage as an android

### ISSUE THREAD

**Issue by 1skandar** [simeonradivoev/MatterOverdrive#314]
Not sure what happened, but all of a sudden I'm taking a little damage every few minutes.It isn't doing me much harm, but it is certainly annoying. 

Video here: https://www.youtube.com/watch?v=MKpfy1Fs9Bg right about 29 minutes and 20 seconds. It had been going on quite a bit before this, but I didn't get it on video, I don't think. Logging out and back in does not help and there isn't any mobs around (they can't spawn in my base) nor natural hazards.

**Comment by 1skandar** [comment]
Also took a look at my player.dat in the level.dat in my save file. Nothing seems off. I can give you the save if you like, (Modular Mayhem pack here:http://forum.feed-the-beast.com/threads/1-7-10-modular-mayhem.120584/)

**Comment by simeonradivoev** [comment]
There is no bug. While being an android the glitch effect appears each time you get hurt. No matter the way you got hurt. Are any other mods hurting you even a little. The damage can also be 0 but it can still count as a damage.

**Comment by simeonradivoev** [comment]
I will have to check ways into making the glitch only appear on certain attacks. The fastest fix I can do right now is to add a config option for disabling the android hurt glitch.

**Comment by simeonradivoev** [comment]
a847a98fa59974733824951316552214c62636d3 you can disable the hurt glitching.

**Comment by 1skandar** [comment]
That is the thing, there is nothing hurting me. At the 29:20 mark I'm standing in the middle of the room with absolutely nothing around me. I have a full battery, there are no mobs (I am in a spawn free zone), no environmental effects, zip, zilch, nada that should be causing me to be hurt even for 0 damage. 

I've been poking at it and, while I'm still not 100% certain, it seems to only pop up in GUIs, or shortly after I close them. I was fiddling with my android abilities with that GUI open and i got hurt twice. I spend too long paging through NEI recipes and sometimes I'll get hurt. Again, there is NOTHING external that can be hurting me. 

I've looked through the code and, if I'm not wrong, it looks like whenever the players hunger drops androids use energy instead of food. If there is no energy available they get hurt (much like the starvation effect). Right? If I had to make a wild guess that if you have a GUI open when your hunger drops it is trying to pull energy and fails, for whatever reason. 

Again, I am not 100% certain, I can't replicate it on demand and I'm not completely sure about the timing, but I've been paying closer attention to the last few times it has happened and *so far* this "damage from nowhere" only seems to happen if you leave a GUI open too long.

**Comment by simeonradivoev** [comment]
The out of power glitch is separate. It does not hurt you. You can hear on your video that there is the hurt sound effect before the glitch. That means the hurt time was changed and the hurt animation was triggered. The android out of power glitch does not hurt you, nor does the food filling. The food levels are filled each tick no matter where you are or if you are in a GUI. The hurt glitch effect is also triggered now when the hurt animation starts but by a Forge event that is called each time the player is hurt. This means that mods that only change the hurt animation will not trigger the glitch effect, but real damages will trigger it.

**Comment by 1skandar** [comment]
Then I have no clue. Something decidedly odd is going on. I'm being hurt then...by nothing? 

Well, that was my best guess. I literally have no clue what could be damaging me. The only other note is that this is recent. As in 3 or 4 hours recent. Up until this video I was fine....and it wasn't until the end that it started to crop up. 

Hmm, is there anything that would cause an android damage that wouldn't to a normal player? If so that might help me narrow this down.

**Comment by simeonradivoev** [comment]
None that I can think of. Is it only happening when you are an android ?

**Comment by 1skandar** [comment]
Yup. And it only started to show up a few hours ago. The only notable things I did between now and then was to a)fight a Wither b)stand fairly close to a fully shielded Matter Replicator spitting out shiny ingots and c)craft a Modular Armor belt with a magnet. (oh, and apparently androids can't sense or draw power from bauble slots) which pushes me up above 35 million in RF storage in capacitors and RF using devices.

And while testing right now I just got hurt....in the middle of the desert....in the middle of the day...with nothing within 10 blocks of me...and no GUIs or NEI open.

**Comment by simeonradivoev** [comment]
Can you test if you get hurt without being an android.

**Comment by 1skandar** [comment]
Yeah. I think. This thing isn't duplicable on demand. It might take me a few minutes.

**Comment by 1skandar** [comment]
Can't duplicate it as a human. That doesn't mean much, this thing is so random. 

Oh, and I found a sub bug. When taking off all the android pieces before becoming human again my health did not reset to 100% until I logged out and back in. 

At any rate, I gotta go. I'll look at this later.

**Comment by 1skandar** [comment]
Ok, heading out the door and I had a thought. How much trouble would it be to include either a debug command in MO itself or a separate mini-mod that traps player damage events and spits that to the console? That way we could stop wandering around in the metaphorical darkness?

**Comment by Alaberti** [comment]
I just grabbed dev 159, noticed that the config doesn't look any different after I deleted it and reloaded the game.

**Comment by simeonradivoev** [comment]
search for "hurt_glitching"

**Comment by Alaberti** [comment]
I figured it out, I'm an idiot who put 158 back in right after I deleted it. Derp.

**Comment by 1skandar** [comment]
Sigh, ok this looks to be not your issue. I forced myself back to human and I am still taking random damage for no discernible reason. I'm at a loss here.

**Comment by 1skandar** [comment]
Ok, it was wither damage.  I'm still not sure the ultimate source, but I'm beginning it was a stuck effect from my last fight with the wither. getting withered again and/or dying may have fixed it. No idea to the actual root cause. I will close this for now, and reopen if I find new information.
