### ISSUE TITLE
X-Mod GUI Rendering Bug

### ISSUE THREAD

**Issue by 1skandar** [simeonradivoev/MatterOverdrive#315]
Not sure which mod is at fault, but being an android has done some fairly bad things to Chromaticraft's GUIs:
![2015-11-12_07 20 36](https://cloud.githubusercontent.com/assets/4127779/11118203/0f1a1ffc-890e-11e5-83ca-dc778d30d441.png)

I'm reporting it on both your and Reika's bugtracker, as I'm not sure where the problem is.

**Comment by simeonradivoev** [comment]
Strange. What version of the mod are you using ?

**Comment by 1skandar** [comment]
Build 158 and Chromaticraft/DragonAPI 9b.

**Comment by Belgabor** [comment]
Doesn't only affect ChromatiCraft, lots of other mod GUIs are affected, albeit not as heavily.

Example AE2:
![2015-11-20_07 30 45](https://cloud.githubusercontent.com/assets/36589/11293282/019a95c2-8f59-11e5-9ba5-b48ce064dd83.png)

As android:
![2015-11-20_07 31 47](https://cloud.githubusercontent.com/assets/36589/11293283/0ce02b5e-8f59-11e5-89ce-5644ba33acba.png)

Others I've found are OpenComputers (case inventory GUI) and Traveller's Gear (enhanced player inventory).

This is with 0.4.0 and unrelated to ChromatiCraft (tested in an instance that had just Matter Overdrive, AE2 and NEI).

**Comment by simeonradivoev** [comment]
@Belgabor when is that happening exactly? Do you have the Android HUD or have you opened another Matter Overdrive window?

**Comment by Belgabor** [comment]
I only had the android GUI. To make sure it wasn't some kind of interaction with ChromatiCraft I threw in Matter Overdrive into a pure AE test instance I had, went in, took the red pill and checked (that's where the screenshots are from). It goes away if you take the blue pill and go "meaty" again =)

**Comment by shadowfacts** [comment]
@simeonradivoev Is MO doing anything weird with the GUI rendering code?

> I have custom render code - that included ASMing into GuiContainer's drawScreen - but it should not spontaneously stop working. I suspect MO is doing something odd with zLevel or OpenGL state in his GUI code.

From ReikaKalseki/Reika_Mods_Issues#391

**Comment by simeonradivoev** [comment]
I don't know. I think I fixed it by pushing and popping GL attribute groups. So that any changes made by my code won't affect others.

**Comment by shadowfacts** [comment]
@Belgabor @1skandar Can you test with the [latest build] of MO?

[latest build]: http://simeon.co.vu/Mods/MatterOverdrive/builds/

**Comment by simeonradivoev** [comment]
It's not pushed yet. Working on a Questing system so I can't push it qute yet.

**Comment by Belgabor** [comment]
Sure, I will test as soon as @simeonradivoev gives the go =D

**Comment by simeonradivoev** [comment]
Fixed in a79e7254b0bb235d98120c622f2e56744cf33077
