### ISSUE TITLE
Phaser Rifle Crash

### ISSUE THREAD

**Issue by sirpixels** [simeonradivoev/MatterOverdrive#325]
Playing on Horizons Dawnbreaker and as soon as I made the Phaser Rifle my game crashed and now everytime I try to log into my server I crash... Any idea how to fix without deleting player data?

**Comment by sirpixels** [comment]
I forgot the crash report so here it is http://pastebin.com/Nfw8NBpu

**Comment by simeonradivoev** [comment]
This should be fixed in the latest versions of Matter Overdrive. Try and update it.

**Comment by sirpixels** [comment]
That indeed fixed the problem good sir. Thank you very much!
