### ISSUE TITLE
Dying recharges capacitors/energy cells

### ISSUE THREAD

**Issue by PsionicArchon** [simeonradivoev/MatterOverdrive#327]
Using the latest version of Matter Overdrive, if a player dies their energy values are reset to 100%.

This can be used to refill things like a resonant flux capacitor instantly. Thankfully no one on my server has discovered this yet.

**Comment by simeonradivoev** [comment]
This was designed to help the player get back up on their feet. There is a config option to disable it. I will probably change the recharging to be done by a specific amount.
