### ISSUE TITLE
Safely Feeding Of An Anomaly

### ISSUE THREAD

**Issue by Badcholo** [simeonradivoev/MatterOverdrive#329]
So i have created a Pixelmon Modpack Called Espeon From Technic Launcher and i have a set it up so that players don't die, take hunger, no fall damage, ect. I have installed towny so they can protect their base and it will be a very friendly server to play on with no mobs or ways of dying. 

I have turned off the entity block destruction and entity pull from the config, but i can't seem to feed the anomaly now. It just won't eat anything. 

I didn't want a immortal player to get forever stuck in an anomaly, so i was hoping there could be a way to feed a anomaly without it causing any destruction or possibly getting a player stuck.

**Comment by Badcholo** [comment]
I can see that it kills you even if you are in god mode or invincible at spawn. It would be nice to be able to feed it without it killing you, but its not so bad. I can deal with it killing players. They will have gameruleKeepinventory true anyways, so it's ok. It would be nice to have a config so it pulls entities in but not players.

**Comment by Badcholo** [comment]
What if you can feed a Anomaly using a Stabilizer? that would make it so you can create matter and feed it to the anomaly. Maybe pump it in like a liquid. Or just put cobblestone directly into the stabilizer and have it suck it up.

**Comment by Alexismachina** [comment]
quote: It would be nice to have a config so it pulls entities in but not players.

But there's already an item for that it would make that item useless...

**Comment by Alexismachina** [comment]
@Badcholo You could always use MineTweaker to make the Space-time cheaper

**Comment by DaMachinator** [comment]
Normally I get launched 100+ blocks into the air by anomalies (spawned by the creative item) and die of fall damage.

**Comment by Alexismachina** [comment]
lol

**Comment by Alexismachina** [comment]
Do you have the Space and Time flux ?

**Comment by DaMachinator** [comment]
I have yet to get stuck in an anomaly. The same thing happens with the NPC's whose village I was hoping it would eat.

**Comment by DaMachinator** [comment]
I did and did not
Same results

**Comment by Alexismachina** [comment]
Does it give you creative fligth when you wear it ?

**Comment by Alexismachina** [comment]
i know it works really well on androids.

**Comment by DaMachinator** [comment]
I thought you meant the android ability to not take gravitational anomaly damage

**Comment by DaMachinator** [comment]
I may have done something wrong but it didnt help

**Comment by Badcholo** [comment]
It is for a tech pixelmon server, so players are in god mode at all times. They also don't die from hunger and gamerulekeepinv is enabled. I wanted to make sure players didn't get stuck in the anomaly without being able to die before they realized they needed certain items.

**Comment by Alexismachina** [comment]
@Badcholo ask them to wear the Space time Flux lol.

**Comment by Badcholo** [comment]
I don't think you guys get it. Can you guys please stop posting troll comments on here. I clearly have the capability of making a tutorial, creating a info center at spawn to inform players, I can make books with all the information and precautions in it, I can even equipt players with the items required as soon as they join the server, none of that has any relevance to what i was suggesting / requesting. Maybe you should go back up and read it again. This server is for younger kids that older kids can also enjoy and teach the younger ones tech type stuff without having to worry about any harm or destruction coming to them or their bases.
Example, they set their home near the anomaly, they feed it way too much, they get pulled in and die, they keep their stuff, but every time they go home they die again. As the owner of the server i would have to keep helping players out of such jams. Same as if they accidentally dropped something onto the floor and it got sucked up and destroyed. A max anomaly size config would be very helpful as well, but that might already exist. I just haven't checked in a while. My point is if there was a way to feed the anomaly with a matter feeding laser or using the stabilizers to feed the anomaly would be a much safer way to feed the anomaly. Matter Export with cool particles effects reaching the anomaly indicating the anomaly was receiving the matter particles pumped in by a pipe.

**Comment by Badcholo** [comment]
For servers that have the anomaly config settings for block destroy and entity pull turned off.
A way to still be able to feed the anomaly.

**Comment by Alexismachina** [comment]
It's just that if Simeon does that most likely everyone in other packs are gonna be lazy and just make the anomaly not do anything. This is like Botania Passive Flower Discussion all over again...

**Comment by DaMachinator** [comment]
So it doesn't eat items? Even if you drop them directly on top of the anomaly block?

**Comment by DaMachinator** [comment]
The floating itemstacks on the ground are entities - hence why when you change the configs, they aren't pulled in.

**Comment by Badcholo** [comment]
Troll comment again, alex, You can not mix fact and opinion.
I understand why it does not pull them in. I was just asking if maybe we can support an alternative for non survival servers.

**Comment by DaMachinator** [comment]
>Troll comment again.

No it isn't. Do you know what happened when Vazkii had a config for disabling passive flower decay?

Even the FTB Mod of the Month pack, starring Botania, disabled it.

>an alternative for non survival servers.
Players in creative can fly away - unless you mean servers on peaceful or something like that.

Did you try dropping items directly on to the anomaly?

**Comment by Badcholo** [comment]
Seriously dude stop bothering me. You guys are very annoying and no one was asking for your opinion  or even talking to you. I don't know nor really care about a flower or FTB modpack of the month. 
And Seriously "Have you tried dropping items directly on the anomaly while having the configs turned off??!!!!!!" 
Stop being such a troll for gods sake.

**Comment by Badcholo** [comment]
You've been blocked and i'm closing this issue cause it has gone way off topic.
