### ISSUE TITLE
[Bug] Health and speed reset between dimensions

### ISSUE THREAD

**Issue by Techtronik** [simeonradivoev/MatterOverdrive#330]
health and speed bonuses reset between dimensions.
speed can usually be reset by running but sometimes completely bugs out.
health can only be reset by quitting then loading your world. On rare occasion, removing and re-applying tiinker's construct health upgrades has reset the android bonus.
all bonuses are restored every time upon quitting then loading the world.

**Comment by simeonradivoev** [comment]
Fixed in bd287d460bd912d283b093b5cb0cf214d27586bd
