### ISSUE TITLE
Holographic sign has no recipe

### ISSUE THREAD

**Issue by Techtronik** [simeonradivoev/MatterOverdrive#331]
I'm not sure if this is still indev or what but i tried a world with only nei and matter overdrive installed and it doesn't show a recipe

**Comment by simeonradivoev** [comment]
What version of the mad are you using

**Comment by Techtronik** [comment]
0.4.0

**Comment by simeonradivoev** [comment]
The latest dev version has a recipe. Maybe try them out.
