### ISSUE TITLE
Feature Suggestion: More Resources

### ISSUE THREAD

**Issue by Badcholo** [simeonradivoev/MatterOverdrive#333]
I have always liked mining for resources and gathering all sorts of cools stuff. It would be nice to have more minerals to harvest. Like oil, i have always loved pumping out oil for stuffs.

**Comment by AHrubik** [comment]
Very few mods have done oil as well as Buildcraft. Random spawning oil spouts of random heights all going down to bubble wells of random sizes at random depths. A pump that is easily powered and selective about the liquid it pumps.

If you add it use Buildcraft as an example and not Galacticraft. Of everything Micdoodle did right oil was not one of them.

**Comment by simeonradivoev** [comment]
Matter Overdrive is a sci fi mod. I doubt I'll ever add Fossil Fuels.

**Comment by Badcholo** [comment]
That's ok, How about a tracker then?, so that players can track each other down. To be able to find the coords to someones base for pvp purposes, config to disable for those who don't like it. I run a grief, pvp, raid, scamming, swearing server and i could use a tracker that when you right click on a player it saves their data, when you place the tracker into a machine, it gives you the coords to that player at that point in time as long as you are in the same world as them. also a simple relog will cause the track to be lost. fingers crossed, but i know your gonna say no, but thanks anyways,
