### ISSUE TITLE
Bounding block cannot be removed

### ISSUE THREAD

**Issue by PsionicArchon** [simeonradivoev/MatterOverdrive#334]
Charging stations destroyed by explosions leave behind bounding blocks that cannot be removed.

Screenshot: http://i.imgur.com/KVWGMzX.png

I've tried everything short of MCEdit to remove this thing.

**Comment by simeonradivoev** [comment]
Ho. I knew that would happen. @shadowfacts didn't foresee that.

**Comment by shadowfacts** [comment]
Right, redoing bounding blocks! Going to add a TileEntity to them so they can store their owner coord/type and if the owner goes missing or is changed, break themselves. Shouldn't cause big problems for existing worlds.

**Comment by shadowfacts** [comment]
Whelp, finally sat down (for 5 hours) on the plane and worked on this. (See 42a2b1a02c8981880add33954095e9e943064e6e) As far as I can tell, it works, but I'm probably missing an edge case or two.

**Comment by simeonradivoev** [comment]
Nice
