### ISSUE TITLE
Crash when near a mushroom biome while Rogue Android spawn chance is set to '0'.

### ISSUE THREAD

**Issue by laserlemons** [simeonradivoev/MatterOverdrive#337]
http://pastebin.com/F9NTKdZW

Any time someone gets near the mushroom island it crashes. If I switch the spawn chance from 0 to 5 it's fine again. The island also has about 20-30 Rogue Androids under the ground too. IMO they should not be able to spawn there, since normal monsters can't either.

**Comment by simeonradivoev** [comment]
That seems to be a minecraft crash. You can blacklist the mushroom island biome in the configs. It's "MushroomIsland" and "MushroomIslandShore".
