### ISSUE TITLE
Weird Android "info-hud" glitch

### ISSUE THREAD

**Issue by webmilio** [simeonradivoev/MatterOverdrive#340]
For some reason, when I look at stuff, theres a weird grid in the back.
https://imgur.com/0XdA6OM
https://imgur.com/USzpK5u

**Comment by simeonradivoev** [comment]
Something is messing up the blending modes.

**Comment by webmilio** [comment]
Any idea how to figure out what it is ?

**Comment by simeonradivoev** [comment]
I doubt it. I will have to see if I force the blending mode.

**Comment by simeonradivoev** [comment]
I do force the blending mode on. I even change the blending type. Some other mod may be messing up the OpenGl state.

**Comment by shadowfacts** [comment]
Other mod issue.
