### ISSUE TITLE
Star Map graphic issues and compatibility

### ISSUE THREAD

**Issue by EzerArch** [simeonradivoev/MatterOverdrive#342]
It seems that the Start Map lets other visual elements from the surroundings and other mods leak into its interface.

**1) More Player Models mod compatibility:** I have dozens of tech-mods, one of them is More Player Models which allows me to retexture the 1st-person view player hand 1, as you can see in this screenshot:

![2015-11-28_19 15 55](https://cloud.githubusercontent.com/assets/6743303/11453936/7789be5a-9604-11e5-9746-330ac9abbe6b.png)

The problem here is MPM affects the Star Map so that the map itself doubles in size and longer fits in the game window, and other elements "leak" into the interface:

![2015-11-28_19 14 59](https://cloud.githubusercontent.com/assets/6743303/11453945/d5ab2244-9604-11e5-89e0-b9f238d0b316.png)

Now if I remove MPM, same GUI scale (normal):

![2015-11-28_19 09 51](https://cloud.githubusercontent.com/assets/6743303/11453894/ccd612f6-9603-11e5-8ad0-dd02dab8216b.png)

Way better.

**2) MO alone:** Then I removed all mods except MO and my resource pack:

![2015-11-28_20 02 34](https://cloud.githubusercontent.com/assets/6743303/11454188/4d7ad160-960b-11e5-9a3b-7c568c0a2217.png)

Looks like the Star Map lets other surrounding elements leak into its interface. On the left is the fusion reactor (which is 20 blocks off screen) and on the right are 3 weapon stations.

**Comment by simeonradivoev** [comment]
The star map is not yet implemented. The GUI is still in progress and there is not much I can do about other world elements bleeding through. I use world rendering with a fake player as the view. What you see is the starmap seen from a fake player that's just above it.
