### ISSUE TITLE
Server Crash v0.4.0

### ISSUE THREAD

**Issue by Keridos** [simeonradivoev/MatterOverdrive#346]
https://paste.ee/p/boqKt

Forge version 10.13.4.1558-1.7.10

Apparently you require Java 8 for this. Can you maybe remove that requirement, Java 8 is not really an option on most linux systems.

**Comment by simeonradivoev** [comment]
We can't just remove Java 8 requirement. It's a requirement because it's woven into the mod code. And the crash happens because you don't have Java 8.

**Comment by shadowfacts** [comment]
> Java 8 is not really an option on most linux systems.

o_O wat. [Oracle's JRE](http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html) has a linux version *and* there is a Java 8 version of [OpenJDK](http://openjdk.java.net/)

**Comment by Keridos** [comment]
The problem is that both Ubuntu AND Debian still ship OpenJDK 7 and you cannot install java 8 via the default packaging system (apt). I know how to install Oracle JDK and I did it only because of this mod on my server, but still this can be a bit of an annoyance because you actually have to install Oracles JDK...

**Comment by shadowfacts** [comment]
> annoyance

≠

> not really an option

**Comment by Keridos** [comment]
Yes, I see that now. BTW what features are you using that require Java 8, Lambda Expressions?

**Comment by shadowfacts** [comment]
Lambdas, interface defaults, streams, and (IIRC) optionals.
