### ISSUE TITLE
Error when logging into server: Could not spawn entity ID 86 (phaser fire)

### ISSUE THREAD

**Issue by ajthemacboy** [simeonradivoev/MatterOverdrive#348]
https://gist.github.com/ajthemacboy/d5a2052a37f8906fd625

This occurs randomly when logging into server, or at random times once logged in. The only solution was to remove the mod from the server, and eventually the client, if it can't be fixed.

**Comment by simeonradivoev** [comment]
Did you check if the server and client configs are the same. Especially the entity ids.

**Comment by ajthemacboy** [comment]
They are.

**Comment by simeonradivoev** [comment]
Are you sure? The crash log says they are not.

**Comment by ajthemacboy** [comment]
I literally just copied the client configs to the closed server and started it. My other players are having the same problem.

**Comment by simeonradivoev** [comment]
But does it change after you start the server? and are they the same after that. Some people are having the problem of ever changing server config.

**Comment by ajthemacboy** [comment]
I'm calling it quits for the night, but tomorrow I'll try copying the server configs to client and see what that does.

**Comment by simeonradivoev** [comment]
Fixed in 305f74b16cb91e9c7c2e651f8ec29f3c4a704625

**Comment by ajthemacboy** [comment]
This is probably an unrelated problem, but we ended up having to remove MO from the server again. Every time a player logged in no chunks would load and we'd eventually time out.

It was tested only to occur with MO installed.

**Comment by simeonradivoev** [comment]
strange

**Comment by ajthemacboy** [comment]
No errors in client or server logs, it just lags a ton.

**Comment by simeonradivoev** [comment]
what version are you using ?

**Comment by ajthemacboy** [comment]
0.4.0

**Comment by simeonradivoev** [comment]
You can try the dev builds if you want or wait for another release.
