### ISSUE TITLE
No texture for MK1 circuits / cards / whatever they're named

### ISSUE THREAD

**Issue by Nexey** [simeonradivoev/MatterOverdrive#35]

**Comment by simeonradivoev** [comment]
missing texture ?

**Comment by Nexey** [comment]
Seems to be missing some textures indeed.

**Comment by QuiOui** [comment]
If you rename the .pngs to have lowercase I's at the beginning it will fix the textures.

**Comment by simeonradivoev** [comment]
the textures names are in lowercase. I will need more info, like what system are you using what version of the mod and what other mods are you using.

**Comment by QuiOui** [comment]
I'm using 0.3.4.1 in the ftb Horizons daybreaker pack on windows 8.1, but I can see on the repo as well that the isonlinear circuits have the I capitalized in their name.

**Comment by simeonradivoev** [comment]
hmm quite weird, but in the builds you can open the jar file to check, the names are not capitalized, so that's not the problem.

**Comment by simeonradivoev** [comment]
Actually, for the bugfix i downloaded the repository and used it to build it. That's why the names are messed up.

**Comment by QuiOui** [comment]
Yea I was just looking through all the previous versions and they were correct, it was just the bugfix version that had the borked names.
