### ISSUE TITLE
Crash when generating world

### ISSUE THREAD

**Issue by ajthemacboy** [simeonradivoev/MatterOverdrive#351]
I can't seem to stop having problems with MatterOverdrive! This time a crash occurs when creating a world, only when MatterOverdrive is present.

Crash Report: https://gist.github.com/ajthemacboy/1df7049278a8e69fb9dc
Log: https://gist.github.com/ajthemacboy/7f4a3bbde0b208898e27

**Comment by simeonradivoev** [comment]
Update to the newest Matter Overdrive version and see if that fixes the problem, if not report back.
