### ISSUE TITLE
Thaumcraft "potion" effect 

### ISSUE THREAD

**Issue by Keridos** [simeonradivoev/MatterOverdrive#358]
Using build 487 from the dev builds, I encountered that the Warp Ward effect from Thaumcraft is being removed when in android form. This is usually not a potion effect but rather some sort of protection shield from negative/destructive magic influence. Could you please add in that that effect is not being removed, like night vision is?

**Comment by simeonradivoev** [comment]
Androids remove all potions effects. The night vision effect is just on the client side. This is just the benefit/drawback of the android form. You can change if potion effects are removed in the config.
