### ISSUE TITLE
Galacticraft integration - No damage in the absence of oxygen

### ISSUE THREAD

**Issue by Raffy43** [simeonradivoev/MatterOverdrive#359]
While playing I realized that when my character is an android is not damaged by lack of oxygen

Sorry for any errors

![screenshot 2015-12-22 16 20 58](https://cloud.githubusercontent.com/assets/16402912/11958466/53a53b78-a8c8-11e5-93fa-c3ea31b5bab5.png)

**Comment by simeonradivoev** [comment]
Yes androids do not breathe air so they can't suffocate.
