### ISSUE TITLE
Stabilizer Screen disappears when facing North or West

### ISSUE THREAD

**Issue by Alaberti** [simeonradivoev/MatterOverdrive#360]
Noticed a weird issue with stabilizer screens (may affect other like items, if applicable) where, if I'm facing north or west, the screen will blank out if I look at it from certain angles. Below are screenshots that better help Illustrate the issue.

Also, HAPPY HOLIDAYS!! Enjoy your vacation! And if you weren't vacationing, I think you are now lol.

![Uploading 2015-12-25_02.03.47.png…]()
![2015-12-25_02 03 49](https://cloud.githubusercontent.com/assets/10929796/11998703/29953640-aaac-11e5-84fe-1ac142b3dc8e.png)
![2015-12-25_02 03 53](https://cloud.githubusercontent.com/assets/10929796/11998704/29963f90-aaac-11e5-999d-446043259ae4.png)
![2015-12-25_02 03 54](https://cloud.githubusercontent.com/assets/10929796/11998706/2997da4e-aaac-11e5-9566-65fc8a3a4596.png)
![2015-12-25_02 03 56](https://cloud.githubusercontent.com/assets/10929796/11998707/29983458-aaac-11e5-9c17-34b1692ce369.png)
![2015-12-25_02 03 58](https://cloud.githubusercontent.com/assets/10929796/11998705/29970fec-aaac-11e5-9a51-e04f7f231f30.png)
![2015-12-25_02 04 01](https://cloud.githubusercontent.com/assets/10929796/11998709/29ac729c-aaac-11e5-8daf-0632f421411e.png)
![2015-12-25_02 04 02](https://cloud.githubusercontent.com/assets/10929796/11998708/29ab8d0a-aaac-11e5-9613-18e77e39acce.png)

**Comment by simeonradivoev** [comment]
Happy Holidays to you as well! I it indeed quite strange why it's doing that. It's not gonna be the culling of the object.
