### ISSUE TITLE
Duplicate Ids with WarpDrive?

### ISSUE THREAD

**Issue by Gatamigo** [simeonradivoev/MatterOverdrive#362]
Hello! Forgive me for bothering you, this does seem like a rather minor thing, but I thought I might as well bring it to somebody's attention! I was attempting to play with a few alike mods in Single player, and came across this incompatibility. The duplicate id in question seems to be with your "Transporter." A shame... I'd hoped with the move away from numerical ids this wouldn't be anything I had to see again, y'know? =w=

Now, I'm not demanding or even asking that something be changed- Warp Drive, the other mod in question, is very much in Alpha anyway, and are probably in a better place to change something on their end; I'm heading to their gitHub right after this to give them a similar message. But with one mod offering Space voyages, and yours offering Star Trek-esque technology, I find it plausible that I won't be the only person who tries to play the two at once. Again, sorry for bothering you, but thank you for your time!
[crash-2015-12-28_20.18.36-client.txt](https://github.com/simeonradivoev/MatterOverdrive/files/73674/crash-2015-12-28_20.18.36-client.txt)

**Comment by simeonradivoev** [comment]
Hopefuly that doesn't mess with the world saves.

**Comment by simeonradivoev** [comment]
Yep. It deleted all NBT data for tile entities on previous worlds.
