### ISSUE TITLE
Wrong location! PlasmaBolt 'entity.phaser_fire.name' in server console

### ISSUE THREAD

**Issue by Alaberti** [simeonradivoev/MatterOverdrive#367]
http://pastebin.com/NGemCvYi

Running build 198, and just happened to glance at the console and saw this pop up a few times. I don;t think it's anything game breaking, just kinda...there?

**Comment by simeonradivoev** [comment]
What the... Do you have any corrupted chunks ? Does this error persist or does it cause other problems ?

**Comment by shobu9** [comment]
i was about to ask the same thing. Is it on a server or is it multiplayer. Because if its multiplayer it could just be some kinda of desync that caused it.

**Comment by shobu9** [comment]
Hum , there is something related to Remote IO. Is it possible that the mod is in your modpack?

**Comment by Alaberti** [comment]
Dedicated server, remote io is not in the pack. Corrupted chunks are possible, the map has been around six months or so for 24/7.
