### ISSUE TITLE
Crash when trying to join the server

### ISSUE THREAD

**Issue by tobiasklemp** [simeonradivoev/MatterOverdrive#368]
I added matter overdrive in its latest version to my ftb infinity server. then it crashes when i try to join it.
log:
http://paste.feed-the-beast.com/view/655567c2

thanks

**Comment by simeonradivoev** [comment]
Try and update to the dev version and see if you still get the crash.

**Comment by tobiasklemp** [comment]
Used build 206 now. Interesting is that i logged out in the nether and then installed the mod. when i logged in again everythings was fine but when i tried to reenter the overworld it crashed again. Maybe there is an issue with the entities ?
log:
http://paste.feed-the-beast.com/view/e82644b7

**Comment by simeonradivoev** [comment]
are the entity IDs on the client the same as the server ?

**Comment by tobiasklemp** [comment]
I copied the config files from the server. now i am at least able to join lets see how long it lasts. thank you ;)

**Comment by Alexismachina** [comment]
@simeonradivoev he didnt comment i think this its working can you close it XD ?
