### ISSUE TITLE
Androids got stuck

### ISSUE THREAD

**Issue by Badcholo** [simeonradivoev/MatterOverdrive#369]
Androids seem to get stuck on world gen.
Found a ship with alot of androids stuck inside.
Love the world gen btw.
![2016-01-02_15 20 33](https://cloud.githubusercontent.com/assets/10932905/12076348/8414de30-b165-11e5-854f-78a43501137b.png)
![2016-01-02_15 21 25](https://cloud.githubusercontent.com/assets/10932905/12076352/87e765e6-b165-11e5-912f-ef8a40b1b4b6.png)

**Comment by simeonradivoev** [comment]
Yeah... that happened to me as well. I will have to fix that.

**Comment by shobu9** [comment]
THEY ALL SURVIVED!

**Comment by Badcholo** [comment]
Also i got an internat error and was unable to log back into the server until i deleted my player file and respawned at spawn. 
I was looking at the androids and i was looking at chrome. When i went back to minecraft there was the internal error and i was unable to log back in until i deleted my data. It did not cause me to crash so i don't have any info.
Even after i restarted the server i was still not able to log in. it was the moving out of that area.
I did random spawn so i am unable to get back to that specific location. 
I'll see if i can reproduce or if you want logs i can provide.
