### ISSUE TITLE
Issue with Malwarebytes Anti-Malware

### ISSUE THREAD

**Issue by 100chilly** [simeonradivoev/MatterOverdrive#374]
I have Malwarebytes Anti-Malware Premium and it seems to detect traffic either going or coming from your website via the mod. Also it blocked all my web browsers from accessing your site. I know how to add exceptions but why does the mod try to connect to your website? Here's a link: http://pastebin.com/zcY2qa6Z

**Comment by 100chilly** [comment]
@simeonradivoev My assumption is statistics information but might want to add some sort of notice saying it collects that kind of info. :smiley:

**Comment by simeonradivoev** [comment]
It's not statistics it's just getting the version number. If you want you can disable that in the config file.
