### ISSUE TITLE
Weird server crash java.lang.NoClassDefFoundError: org/apache/http/client/HttpClient

### ISSUE THREAD

**Issue by Milii20** [simeonradivoev/MatterOverdrive#381]
Greetings, i just updated matterOverdrive from 0.4.0 to 0.4.1 in a custom pack, and the server wont launch, i will attach the log since it's not generating any crash-report, i just found this in the log which may be intresting:

[16:30:04] [Server thread/ERROR] [FML/]: Caught exception from mo
java.lang.NoClassDefFoundError: org/apache/http/HttpEntity
	at matteroverdrive.handler.GoogleAnalyticsCommon.load(GoogleAnalyticsCommon.java:98) ~[GoogleAnalyticsCommon.class:?]
	at matteroverdrive.MatterOverdrive.serverStarting(MatterOverdrive.java:187) ~[MatterOverdrive.class:?]

Please, in case i am doing something wrong tell me, and thank you soo much for your time!

(link to the log: https://mega.nz/#!jkoxhIgL!5UB3khT9_E8MVuXpa-2p7t71pf8ZlgLRA6FnqkFI7HI )

**Comment by simeonradivoev** [comment]
Did you try the hotfix or the dev builds ?

**Comment by simeonradivoev** [comment]
should be fixed in 8d6f6f0788ad5a1f4d0691ec96bf2be89cb66f43

**Comment by Milii20** [comment]
yes!, that one works, thank you soo much!
