### ISSUE TITLE
Crash When Loading Instance - 1.4.1 Hotfix

### ISSUE THREAD

**Issue by TrojanHashtag** [simeonradivoev/MatterOverdrive#384]
I am running a custom pack and I recently updated the mod, but upon loading it up, it crashed because of an already registered id. When I looked through the config file, the id was not found. Not sure what caused it, but I will post the log here: http://pastebin.com/37krvqke

**Comment by simeonradivoev** [comment]
You can change the entity IDs in the Matter Overdrive Config file.

**Comment by TrojanHashtag** [comment]
The ID I'm looking for isn't in the config, or in any other config file for the mods I'm using.

**Comment by TrojanHashtag** [comment]
Scrap that, I found out that orespawn takes the ID thanks to another mod I used and orespawn doesn't let you change ID's :/ Just gonna generate the config file in another instance and add the value in my config since it hasn't generated.

**Comment by simeonradivoev** [comment]
171 looks like the default ID for one of the failed Animals.

**Comment by TrojanHashtag** [comment]
How interesting, whatever free ID I choose to use still crashes me.

Crash Log: http://pastebin.com/37krvqke

Free ID's (According to AntiIDConflict): http://pastebin.com/uLuPYUH1

**Comment by simeonradivoev** [comment]
Wow all my default ID are taken :laughing:  So you changed the entity ID in my config to a free one and it still crashes ?

**Comment by TrojanHashtag** [comment]
Yep, I don't know what's causing it to happen either. Such a hassle to dig into.

**Comment by TrojanHashtag** [comment]
It's also weird that forge isn't fixing the issue either

**Comment by TrojanHashtag** [comment]
I'm gonna post the same issue on orespawn's website and see if I can get some assistance there.

**Comment by DraksterAU** [comment]
I don't use OreSpawn and still get this issue... :/

**Comment by simeonradivoev** [comment]
This will no longer be an issue with MC 1.8 and 1.9.
Unfortunately 1.7.10 doesn't allow for automatic entity registration and still having Spawn Eggs.

**Comment by DraksterAU** [comment]
You can bypass the issue from what I've seen by generating a default config and changing the entity id away from 171...
Not so bad.

Cant wait til the mod is a bit more complete! is awesome! :)
