### ISSUE TITLE
Rogue androids drop two types of torso

### ISSUE THREAD

**Issue by CplPibald** [simeonradivoev/MatterOverdrive#39]
Rogue android drops include two types of torso.  One has meta 3 and is used in the recipe and by mad scientist.  The other has meta 4 and isn't used for anything.  The second one comes about from in entity/EntityRougeAndroidMob.java : 95

    this.entityDropItem(new ItemStack(MatterOverdriveItems.androidParts, 1, rand.nextInt(5)), 0.0F);

This creates a part with random meta between 0 and 4 inclusive.  But in items/RougeAndroidParts.java, only 0 to 3 are valid.  For name and icon meta 4 is clamped to 3, which is why it is a torso instead of a crash.  But it isn't valid for crafting.

To fix, change the line above to `rand.nextInt(4)` instead of 5.

**Comment by simeonradivoev** [comment]
Thanks :smile:
