### ISSUE TITLE
Google Analytics causes crash, does not update/generate new config

### ISSUE THREAD

**Issue by PsionicArchon** [simeonradivoev/MatterOverdrive#391]
Using the latest version of Matter Overdrive produces this crash: http://pastebin.com/pzKV1jDd

This occurs before the config can be updated, thus I am unable to disable analytics. Reverting to previous version in the mean time. Deleting the config file and attempting to allow it to generate a new one did not help. No config was ever generated. 

Edit: Reverted to version .218, this allowed the config to regenerate. I disabled analytics, updated to .229 and still crashed with the same error.

**Comment by simeonradivoev** [comment]
Shadow deleted the Google Analytics source files and added it as maven dependency. I replaced the missing logger in the source files and had gotten rid of the issue. But we will have to see how to fix it.

**Comment by shadowfacts** [comment]
Fixed by ba09ffde9501231b0e06f16c18b2f51b25cb4995.
