### ISSUE TITLE
Immediate crash

### ISSUE THREAD

**Issue by Tdrake02** [simeonradivoev/MatterOverdrive#394]
[crash-2016-01-12_20.58.44-client.txt](https://github.com/simeonradivoev/MatterOverdrive/files/88391/crash-2016-01-12_20.58.44-client.txt)

I had a crash while the game was loading, however I also have a lot of other mods that are probably the problem. I just want to know what the problem is.

**Comment by simeonradivoev** [comment]
It's an Entity ID conflict. Just go into Matter Overdrive's config file and chose different IDs for the entities that are not already taken.

**Comment by Tdrake02** [comment]
Thanks for the help

**Comment by Tdrake02** [comment]
Which item do I need to change?

**Comment by simeonradivoev** [comment]
See your log and you will find the ID that's causing the problem.

**Comment by Mkchief34** [comment]
I have this problem too. Can you give me a step by step guide to what to change in the Config?
