### ISSUE TITLE
Crash with android hud minimap and CustomNPC mod

### ISSUE THREAD

**Issue by bludde** [simeonradivoev/MatterOverdrive#395]
When trying to get the Android map radar, the mod CustomNPC crashes the client.

http://pastebin.com/Srk4EN00

Dont know if its on this side or the other.

MatterOverdrive-1.7.10-0.4.1-build-222
CustomNPCs_1.7.10d

**Comment by simeonradivoev** [comment]
theirs

**Comment by bludde** [comment]
ill blame them:)
