### ISSUE TITLE
Enhancement: Rogue androids in crashed ships.

### ISSUE THREAD

**Issue by DaMachinator** [simeonradivoev/MatterOverdrive#397]
Add ability for android players to trade and/or do quests for rogue androids in crashed ships.

Suggestion came from what I tried to do when I first came across a crashed ship in creative.

**Comment by simeonradivoev** [comment]
Your suggestion is very vague. You should elaborate. There is already a quest line associated with the crashed ships.

**Comment by Alexismachina** [comment]
I think he suggests to add quests to the rogue androids or special androids (quest from like the mad scientist) and for the trade part i think he means trading like a villager would do.

**Comment by DaMachinator** [comment]
I mean a similar system to the mad scientist, yes.
