### ISSUE TITLE
Crash with latest Dev build

### ISSUE THREAD

**Issue by ajthemacboy** [simeonradivoev/MatterOverdrive#398]
https://gist.github.com/ajthemacboy/dfbbf59c31de22bfce86

**Comment by simeonradivoev** [comment]
The latest dev builds are broken. They probably won't be fixed. MO is being ported to 1.8.

**Comment by Alexismachina** [comment]
1.8 or 1.8.9?

**Comment by simeonradivoev** [comment]
2.0

**Comment by Badcholo** [comment]
Guess i'll be updating to 2.0 now.

**Comment by Badcholo** [comment]
is there even a forge version at 2.0?

**Comment by ajthemacboy** [comment]
What? There is no Minecraft 2.0... there's 1.8.9, then 1.9 coming soon... the devs have said no 2.0, although I guess that could change.

Despite my yearnings for a C++ re-write of the Desktop versions, I assume Simeon is saying that, the next version of MO will be version 2.0, for Minecraft 1.8.

**Comment by simeonradivoev** [comment]
No I was making a sarcastic joke.

**Comment by Alexismachina** [comment]
omg everyone tough he was serious XD!

**Comment by Alexismachina** [comment]
omg everyone tough he was serious XD!

**Comment by DaMachinator** [comment]
wait, so we can track your progress by getting a dev build, running it under Forge for 1.8.9, and seeing how broken it is?

**Comment by Badcholo** [comment]
ha ha, facepalm -_-
:+1:
