### ISSUE TITLE
No such thing as Communication Relay...

### ISSUE THREAD

**Issue by Hiddenisme** [simeonradivoev/MatterOverdrive#399]
My quest seems to be broken. It gave me a Coil and I can't find the machine it was trying to give me.

**Comment by simeonradivoev** [comment]
The machine it was trying to give you was coils :laughing: . It is just a renamed item of the coils block. You have to place it near the place you took it. You have to be careful to not place it too far or you can not pick it up with and have the same name. You can get around that by renaming it to exactly the same name and trying again. The objective of the quest should tell you how far you are from the place. But it's generally near the chest you took the original quest from. There is like a 3-4 block radius from the chest.

**Comment by Hiddenisme** [comment]
Thanks :D

**Comment by bludde** [comment]
/give @p mo:decorative.coils 1 0 {display:{Name:"Communication Relay"}}
