### ISSUE TITLE
No matter values

### ISSUE THREAD

**Issue by fwyrl** [simeonradivoev/MatterOverdrive#40]
So... I added this to a personal pack, and copied my multimc folder to my bro's PC, and his minecraft has matter values, mine, however has none. I checked the config>MatterOverdrive>registry, and the file size differed from his by 2 Kb, though I couldn't check anything else, because of the file format.
What should I open it in BTW? (Also, don't save as .reg files, those are a filetype that windows uses to modify the system).

**Comment by simeonradivoev** [comment]
do all items have missing matter values ? You can delete the Registry.reg file and let the game recalculate it again. Also make sure that the config doesn't have any blacklisted items.

**Comment by shadowfacts** [comment]
Closed due to inactivity.
