### ISSUE TITLE
more enchantments

### ISSUE THREAD

**Issue by shadoxxhd** [simeonradivoev/MatterOverdrive#400]
(sorted by enchantment ID)

*armor enchants: can be applied to robot parts; when installed enchantments give special benefits*
protection: increased damage protection (small bonus) OR shield can stay on for longer periods of time
fire protection: chance to take no damage on each fire tick (bonus stacks) OR shield makes you fireproof while active
feather falling: like the normal enchantment
blast protection: shield blocks percentage of explosion damage
projectile protection: chance to deflect arrow w/o shield active (still costs energy (higher than normal shield cost, but decreased if deflect chance >100%); works like an ADS)
respiration: -
aqua affinity: like the vanilla enchantment
thorns: shield deals damage to attacking entity (even at melee), stomp deals more damage

*weapon enchantments: n/a (no melee weapons available)*

*tool enchantments: can be applied to weapons and tools*
efficiency: decreases energy use (like unbreaking does atm)
silk touch: like vanilla effect on tools, no effect on weapons
unbreaking: reduces heating rate
fortune: tools: vanilla, weapons: chance to fire multiple shots? (or maybe chance to not generate any heat when firing)

*bow enchantments: could be used on projectile weapons (railguns/plasma crossbows/etc.)*

*custom enchantments*
overclock: increases weapon damage & tool speed
cooling: increases heat drop (useful with heat capacity upgrades)
thermal buffer: increases heat capacity
stealth: invisible projectiles

*upgrade modules (should have some (maybe expensive) way to use multiple types)*
warp lens: increased projectile velocity (hitscan)
thermal buffer: increases heat capacity (100->200), can be 'supercooled' (very expensive&big machine, needs lots of energy) to provide 1-time heat absorption (maximum ca. 10k stored negative heat (NH), but cooling gets more expensive the cooler the buffer is)
superconductivity upgrade: **extremely** expensive, has big (maybe as much as 100k?) NH storage, needs to be cooled down to at least 80% NH to work, energy consumption is greatly decreased (x0.2), normal heating disabled, but weapon slowly looses NH simply by being equipped
active cooling: cooling rate massively increased (x4?), can 'overcool' (toggleable) but needs energy (normal cooling is quite cheap, overcool is 50% more expensive than with a dedicated cooling machine, overcool cap can be set in weapon bench) (maybe 3 variants: passive cooling upgrade (x1.5, no energy drain), active cooling upgrade (x4, energy drain), 'supercooling' upgrade (x5, can 'overcool'))
energy pattern stabilizer: increases range (x2)
pulse precharger: enables burst fire (3-shot burst, s/m x0.5)
alternating capacitor precharging: s/m x2, energy drain x2.5
multi cell capacitor: expensive. 1.5x energy drain per damage. ability to change fire rate/pattern. weapon has 6 energy cells. cyclic cell charging. possible patterns:
-1/1/1/1/1/1: s/m x3, damage x0.5 (spray&pray)
-2/2/2: s/m x1.5, damage x1
-3/3: s/m x1, damage x1.5
-6: s/m x0.5, damage x3 (useful for snipers)
-3/1/1/1: dmg: 1.5/.5/.5/.5; delay: .33/.33/.33/1
charge/time table for last sequence: (time unit=base delay/3; energy unit: 1/6 cell capacity; dmg unit: 0.5 base dmg)

time | c1 | c2 | c3 | c4 | c5 | c6 | dmg
--- | --- | --- | --- | --- | --- | --- | ---
0|	0|	0|	0|	6|	6|	6|	3
1|	1|	1|	1|	0|	6|	6|	1
2|	2|	2|	2|	1|	0|	6|	1
3|	3|	3|	3|	2|	1|	0|	1
4|	4|	4|	4|	3|	2|	1|
5|	5|	5|	5|	4|	3|	2|
6|	0|	0|	0|	5|	4|	3|	3
7|	1|	1|	1|	0|	6|	6|	1
...

combined w/ puls precharger: needs 2 energy cells for 3-shot burst w/ .5 base dmg; can't shoot in 2 successive ticks (2-2-2-0-0-0 not possible; weapon fires at 0/0.5/1 -> 2-0-2-0-2-0 becomes 111011101110)
-2/2/2: s/m x1.5, dmg 3x.5
-3/3 (3-0-0-3-0-0): s/m x1, dmg 3x.75
-4-0-0-2-0-0:  s/m x1, dmg 3x1/3x0.5

inhomogeneous focus crystal: converts projectile into multiple 2-3 damage ones with significant spread. projectile count based on damage of weapon *1.2 (because the energy doesn't need to be focused that well, leading to higher conversion efficiency)(or maybe N=min(damage,50)^0.75+max(damage-50,0)^(1/3) ?)

**Comment by simeonradivoev** [comment]
Oh my goodness.

**Comment by shadoxxhd** [comment]
it looks complicated, but implementing it should be way easier than it sounds at the first moment

**Comment by simeonradivoev** [comment]
Unfortunately vanilla enchantments cannot be applied to items different than the vanilla ones. You can apply the looting enchantment only to items that extend the Sword item.

**Comment by shadoxxhd** [comment]
would it be possible to make robot parts extend the armor base class yet be unequipable in the armor slots?

**Comment by simeonradivoev** [comment]
no

**Comment by Alexismachina** [comment]
Close this ?

**Comment by Alexismachina** [comment]
@simeonradivoev ?

**Comment by shadoxxhd** [comment]
even if enchantments are sadly not possible, the ideas about upgrade modules are still valid
