### ISSUE TITLE
entity ID conflict

### ISSUE THREAD

**Issue by AngelCry** [simeonradivoev/MatterOverdrive#401]
hi. i get ID conflict (resolved by editing config) and want to ask: are there any reason to assign IDs this way (some numbers from config)? i not a modder, but was reading there some auto-resolve IDs system in Forge, so may be your ID system need to be changed? as i understand, there (in Forge) now even ID system based on strings, not numbers (which are limited).
to be more specific, i got ID conflict beetween NuclearCraft and Matter Overdrive, start from id 24, but as NC at least use findGlobalUniqueEntityId() i decided to address this to you.

**Comment by simeonradivoev** [comment]
Automatic ID resolvement is implemented works only with block and item IDs. Entity IDs still don't have this feature. I made one myself but had problems with IDs on servers and clients not syncing up. That's why I chose to have preset IDs that can be changed manually. PS findGlobalUniqueEntityId() doesn't always work. It's not reliable.

**Comment by simeonradivoev** [comment]
I guess I was mistaken. It seem forge automatically assigns IDs. I was just using old methods for registering entities. The new ways don't have easy Egg generation. But 1.8 does. So I will fix it in 1.8.

**Comment by AngelCry** [comment]
>The new ways don't have easy Egg generation.

you mean EntityRegistry.registerModEntity, which use strings as entity ID?
>So I will fix it in 1.8

so, MC 1.7.x will stay as is? IDs from config not so bad way to assign them, especially if you using same mods for long time. but if you change mod list from time to time, resolving ID conflicts by hand just may become annoying. anyway, thanks for answer and explanation.

**Comment by Mkchief34** [comment]
Yeah, I have this problem too. Know of any mods that auto-assign entity-ids?

**Comment by shadowfacts** [comment]
Global entity IDs are no longer used.
