### ISSUE TITLE
Potential Thaumcraft Compatibility error

### ISSUE THREAD

**Issue by Alaberti** [simeonradivoev/MatterOverdrive#403]
From a player on my server: "So found a slight bug. You can apparently scan Matter Overdrive machines with a Thaumometer multiple times."

**Comment by DaMachinator** [comment]
Do they give any research points?

**Comment by Alaberti** [comment]
I'm told they do, yes.

**Comment by DaMachinator** [comment]
did you use the cheat thaumonomicon (to discover all aspects) and try scanning one yourself?

**Comment by Alexismachina** [comment]
Can confirm i manage to reproduce it. But it doesnt seem to give you that much research point it seems just to be bugged.
