### ISSUE TITLE
Crashing Modded survival

### ISSUE THREAD

**Issue by gingerale42** [simeonradivoev/MatterOverdrive#404]
[crash-2016-01-17_15.40.33-client.txt](https://github.com/simeonradivoev/MatterOverdrive/files/93621/crash-2016-01-17_15.40.33-client.txt)

**Comment by simeonradivoev** [comment]
Java 8 is required.

**Comment by gingerale42** [comment]
I'm running java 8

**Comment by simeonradivoev** [comment]
The crash log says something different. Java Version: 1.7.0_79

**Comment by gingerale42** [comment]
interesting

**Comment by gingerale42** [comment]
thanks
