### ISSUE TITLE
Omni Tool does not drain energy with right-click 1.7.10 - 0.4.1

### ISSUE THREAD

**Issue by Archangelius** [simeonradivoev/MatterOverdrive#405]
Energy is drained on left click, but right click does not consume energy

**Comment by simeonradivoev** [comment]
Are sure it's not draining a small amount of energy ?

**Comment by Archangelius** [comment]
I am almost positive. It drains slowly on version 0.4.0 but when testing with version 0.4.1 there is no drain on right-click. To verify I let the laser run for about 2 minutes with no change.

**Comment by simeonradivoev** [comment]
I will have to look into it.

**Comment by Alexismachina** [comment]
Ok , i manage to reproduce something similar. It seem it DOES drain energy. But sometimes it doesn't render the "damage bar" (Power bar). But yes i manage to drain one completely it just didn't show. However on server its different for some reason. It doesnt sync and the omitool has infinite power. And sometimes even doesnt mine the block. But the *damage shot* works always.
