### ISSUE TITLE
Ivorius mods

### ISSUE THREAD

**Issue by Suikju** [simeonradivoev/MatterOverdrive#406]
There is a compatibility issue in the version 0.4.1 with ivorius mods (ye gamols chattels, Iv Toolkit and psychedelicraft).
The android HUD is dublicated in a smaller form. Could you fix that, or i have to ask ivorius or i have to live with that problem?

http://www.bilder-upload.eu/show.php?file=de421e-1453118525.gif

i hope the picture could help a little. 

Greetings

**Comment by simeonradivoev** [comment]
I don't even know why this is happening :confused: . Maybe ask them the as well.

**Comment by Ivorforce** [comment]
@Suikju The website bilder-upload.eu is on a malware site list. Please upload the gif to imgur of gfycat.

I can imagine about what might be happening, but I'll need to see how exactly it looks if I want to make a quick judgement and not look through this whole project.

**Comment by Suikju** [comment]
http://imgur.com/aYr7zWZ here the link

**Comment by Ivorforce** [comment]
Honestly, that doesn't even look like much of a technical OGL problem.

Try turning off the 2D shaders, 3D shaders, depth test, and bypassing the FBO in the Psychedelicraft config. If none of those fix the issue, Psychedelicraft is very likely not involved (IvToolkit and YGC won't be either way, they don't do much).

**Comment by Suikju** [comment]
So looks like none of the configchanges could solve the problem... . i will deactivate those mods first.

**Comment by shadowfacts** [comment]
No longer applicable as Ivorius' mods aren't updated to 1.10.2
