### ISSUE TITLE
Gamecrash while trying to build fusionreactor

### ISSUE THREAD

**Issue by Suikju** [simeonradivoev/MatterOverdrive#407]
whenever ill try to build a fusionreactor with fusionreactor IO, the game crashes.
But only if there is placed an anomaly in the middle of the reactor.

[crash-2016-01-18_14.51.11-server.txt](https://github.com/simeonradivoev/MatterOverdrive/files/94455/crash-2016-01-18_14.51.11-server.txt)

**Comment by simeonradivoev** [comment]
It must be a mod config. Some mod changing the base isInvalid method.

**Comment by Suikju** [comment]
ok my description has lack of some informations... . ill try to upload a short video to show the issue.

**Comment by Suikju** [comment]
try this build and tell me, if you get some crash.

![issue](https://cloud.githubusercontent.com/assets/11639581/12394701/ccb52a92-bdfd-11e5-9f2c-5f3ef3e60f2c.png)

**Comment by simeonradivoev** [comment]
No I do not. The crash you're getting is a very peculiar one. The error will be detected at compile time. The mod will not be able to even compile if the error was caused by my mod. Even the 10+ famous mods I test it with.

**Comment by Suikju** [comment]
ok, ill try to reinstall forge, redownload the mod and delete everything in minecraft folder

**Comment by Alexismachina** [comment]
That's an interesting crash @_@

**Comment by shadowfacts** [comment]
Fixed a while ago
