### ISSUE TITLE
No drowning bubbles

### ISSUE THREAD

**Issue by b0bst3r** [simeonradivoev/MatterOverdrive#41]
They were there in the previous release but the bug fix seems to have removed them entirely and no I'm not an android however I was in SSP so whether that information has saved somewhere and carried over to SMP I'm not sure.

Just to reiterate we're talking about the bubble indicator above the food indicator not being present at all.  Can someone clarify if they have them on SMP or not?

**Comment by shadowfacts** [comment]
> No need for air when in Water.
http://simeon.co.vu/Mods/MatterOverdrive/android-guide/

**Comment by b0bst3r** [comment]
As I pointed out in the first post I am NOT an android and everyone on the server is experiencing the same thing.  I know it's an android feature, I've no idea what's causing this.

**Comment by simeonradivoev** [comment]
try and use the command /android set false [Player Name]

**Comment by b0bst3r** [comment]
I saw the [Matter Overdrive] b0bst3r is no longer an android reply but still getting no air bubble/breathing indicators.  I've asked the server owner for a copy of the world so I can have a look and see if I can figure it out.  My test server/world doesn't have this problem.

**Comment by shadowfacts** [comment]
Yeah, I just started playing single player Horizons: Daybreaker and I've had the same problem.

**Note:** The air bubbles don't render visually, but the player still takes damage when they run out of air.

**Comment by b0bst3r** [comment]
We just updated to Hotfix 3 from 0.3.4.1 and we have air bubbles back. I suppose you can test it easy enough to see whether it was MO causing the issue or another mod (since the update to the pack was a big one).
