### ISSUE TITLE
MatterOverdrive Androids spawning where they should not

### ISSUE THREAD

**Issue by DaMachinator** [simeonradivoev/MatterOverdrive#414]
Matter Overdrive androids are *all over* the Eldritch dimension. I am pretty sure they shouldnt be there.

**Comment by simeonradivoev** [comment]
Why aren't they suppose to spawn in the Eldritch dimension. Did you blacklist it and it's not working ?

**Comment by DaMachinator** [comment]
They aren't supposed to spawn there because nothing is except the Eldritch things.

I...did not look at the config.

**Comment by simeonradivoev** [comment]
Unfortunately If I want Rogue Androids to spawn in most biomes and dimension, the only thing I can do is to add them to all and blacklist the exceptions. Adding biomes and dimensions to the whitelist is jut not practical. If other modder what me to blacklist specific dimensions I will gladly do so.
