### ISSUE TITLE
crash with fusion reactor io

### ISSUE THREAD

**Issue by krisdeds** [simeonradivoev/MatterOverdrive#418]
when I place block fusion reactor io, and I accidentally replace another above when broken:
[crash-2016-01-24_14.04.28-server.txt](https://github.com/simeonradivoev/MatterOverdrive/files/102342/crash-2016-01-24_14.04.28-server.txt)

**Comment by simeonradivoev** [comment]
Yes this is a known bug in Forge. I might try and fix it on my side somehow or I can wait for Forge to fix it. But it will probably be in 1.8

**Comment by netzgeist** [comment]
Any workaround present? This still(0.41-hotfix) happens in the 1.7.10 branch for me.

**Comment by shadowfacts** [comment]
Fixed a while ago
