### ISSUE TITLE
android crash?!? HELP

### ISSUE THREAD

**Issue by Xetoe** [simeonradivoev/MatterOverdrive#419]
```
 java.lang.NoSuchMethodError: cofh.lib.gui.GuiColor.multiply(F)Lcofh/lib/gui/GuiColor;
	at matteroverdrive.gui.GuiAndroidHud.<init>(GuiAndroidHud.java:116)
	at matteroverdrive.proxy.ClientProxy.registerProxies(ClientProxy.java:57)
	at matteroverdrive.proxy.CommonProxy.init(CommonProxy.java:56)
	at matteroverdrive.proxy.ClientProxy.init(ClientProxy.java:115)
	at matteroverdrive.MatterOverdrive.init(MatterOverdrive.java:129)
```

**Comment by shadowfacts** [comment]
Do you have CoFHLib installed?

**Comment by Alexismachina** [comment]
Cofh lib is required...

**Comment by Alexismachina** [comment]
Well unless he is using 4.1

**Comment by Alexismachina** [comment]
@Xetoe Could you provide us the full log ?

**Comment by Xetoe** [comment]
@Alexismachina sure
thanks for getting back so quick :D

**Comment by Xetoe** [comment]
would you like a list of used mods as well?

**Comment by Alexismachina** [comment]
Not necessary  i will see them in the log

**Comment by Xetoe** [comment]
[crash-2016-01-25_17.04.52-client.txt](https://github.com/simeonradivoev/MatterOverdrive/files/102571/crash-2016-01-25_17.04.52-client.txt)

**Comment by simeonradivoev** [comment]
You are using an older version of CofhLib. Either upgrade to Matter Overdrive 4.1 or update your CofhLib version.

**Comment by Alexismachina** [comment]
No i want this http://i.imgur.com/vMO9M0S.png XD

**Comment by Alexismachina** [comment]
but yeah
