### ISSUE TITLE
Google Analytics Client Crash in Dev Builds 226 and higher

### ISSUE THREAD

**Issue by Alaberti** [simeonradivoev/MatterOverdrive#420]
I'm getting this error on the client with dev builds 226 up to 230: http://pastebin.com/ZsaK0jVt

I downgraded to release with the config setting to disable google analytics, which worked until 226. have tested every version from 0.4.1 to 230 to verify. This is on the client. Is there a library I need to download for the client I'm missing? Thanks!

**Comment by simeonradivoev** [comment]
No you are not. The new builds are broken.
