### ISSUE TITLE
Going into a black hole with Draconic Armor doesn't kill you

### ISSUE THREAD

**Issue by DaMachinator** [simeonradivoev/MatterOverdrive#423]
I mean, it's a black hole...

All the code is visible on GitHub if you want to figure out how the Chaos Dragon bypasses Draconic Armor.

**Comment by shadoxxhd** [comment]
if you do implement this please make it configurable, as draconic armor is sorta meant to be invulnerable

**Comment by DaMachinator** [comment]
Where's my Sword of the Dragonslayer...

**Comment by shadoxxhd** [comment]
where's my chaos armor...

**Comment by Alexismachina** [comment]
Please don't start a mod figth here... Use irc for that

**Comment by shadowfacts** [comment]
@DaMachinator @shadoxxhd not the place.

**Comment by Alexismachina** [comment]
Anyw ay , next draconic evolution update this won't be an issue. Brandon decided to make the armor vulnerable now. You will still be pretty strong and have every effect cancelled, but the black hole will def be able to kill you overtime.
