### ISSUE TITLE
[Enhancement] Tab key is bound by Matter Overdrive by default

### ISSUE THREAD

**Issue by ajthemacboy** [simeonradivoev/MatterOverdrive#425]
This isn't anything major but...

This is an issue that all new players on my server are annoyed by. The "Tab" key is bound to "Android Switch Ability" by default, which isn't a problem in singleplayer, but literally everyone who comes on my server asks about it.

**Comment by DaMachinator** [comment]
I suggest binding it to the LALT or T key by default.

**Comment by ajthemacboy** [comment]
Not the T key.. that's for chat.. even worse

**Comment by DaMachinator** [comment]
right...I forgot...

F is bad because so many people have Thaumcraft.

_I love my 5 button mouse for this reason..._

**Comment by simeonradivoev** [comment]
I think R (my original choice) is the best one

**Comment by simeonradivoev** [comment]
The key is now moved to R by default in 1.8
