### ISSUE TITLE
How can I edit entity Ids in the config?

### ISSUE THREAD

**Issue by Mkchief34** [simeonradivoev/MatterOverdrive#426]
I am having a problem with a rogue Entity ID (171 to be specific) and I am not sure how to change the config to change the ID. Anyone know how to do so? This ID is crashing my game whenever I try to launch. 

[crash-2016-01-30_12.04.02-client.txt](https://github.com/simeonradivoev/MatterOverdrive/files/110900/crash-2016-01-30_12.04.02-client.txt)

**Comment by simeonradivoev** [comment]
Use any text editor to open the Matter Overdrive's config file located in the config folder of your Minecraft installation as follows config/MatterOverdrive/MatterOverdrive.cfg. Then find the section of the config called "entities". In there you will find all the entity IDs. Look for the problematic entity ID and change it to another free ID. Some testing may be required.

**Comment by Mkchief34** [comment]
Thing is, there are no Entity IDs in the config file. I've checked multiple times.
