### ISSUE TITLE
No entity IDs in config

### ISSUE THREAD

**Issue by Mkchief34** [simeonradivoev/MatterOverdrive#427]
I just downloaded the mod, and it crashes my game, saying ID 171 is already registered. I have received advice to change it in the config, but when I go to the config TO change it, there are no entity IDs to show. Nothing. There are no config options either. What should I do?

**Comment by ajthemacboy** [comment]
Line 124: http://i.imgur.com/lFpsy0J.png

**Comment by simeonradivoev** [comment]
What version of the mod are you using ?

**Comment by Mkchief34** [comment]
THe most recent one. And Ok, Ill quit with the issues.

**Comment by Mkchief34** [comment]
I made the entity ID changes, are the ones below it (the android blacklist stuff) personal, ajthemacboy?

**Comment by ajthemacboy** [comment]
It shouldn't matter which order they are in afaik.

**Comment by simeonradivoev** [comment]
This will be fully fixed in 1.8. I've registering entities the old way which is deprecated.
