### ISSUE TITLE
Androids not following difficulty rules

### ISSUE THREAD

**Issue by ThatOneTraitor** [simeonradivoev/MatterOverdrive#428]
In Version 0.4.1, Androids keep spawning, even in peaceful

**Comment by DaMachinator** [comment]
As a temporary fix, spawn a command block, insert /cofh killall rogue_android, and run on a redstone clock (30 second delay?).

Be aware that this will make completing a major part of the mod very difficult, as the only way to become an android without android parts is to find a red pill as chest loot.

**Comment by simeonradivoev** [comment]
Strange, androids shouldn't spawn in peaceful. They are like any other vanilla hostile mob.

**Comment by Alaberti** [comment]
@ThatOneTraitor do you have any other mods, such as Just Another Spawner or Custom Mob Spawns? They may be influencing the spawning mechanics to some degree, but they are just a few examples of mods that can have that effect.

**Comment by ThatOneTraitor** [comment]
hmm, well i've lost the only copy of the pack i had and the server shut down but i remembered there being infernal mobs and special mobs
