### ISSUE TITLE
Cannot make Sniper Scope

### ISSUE THREAD

**Issue by SOL3675** [simeonradivoev/MatterOverdrive#429]
It has a wrong recipe. This recipe using Glass Panes(102:13), but it does not exist.
![2016-02-04_20 31 15](https://cloud.githubusercontent.com/assets/16431933/12813936/abe322c2-cb7e-11e5-80b0-6749e2b2d8f4.png)
Maybe you mistaken for Green Stained Glass Pane(160:13), because the scope color is green.

**Comment by ajthemacboy** [comment]
See https://github.com/simeonradivoev/MatterOverdrive/issues/416

**Comment by simeonradivoev** [comment]
duplicate #416

**Comment by SOL3675** [comment]
Oh, sorry sir.
I didn't check closed issues enough.
