### ISSUE TITLE
A Few Things

### ISSUE THREAD

**Issue by Beadsmith2** [simeonradivoev/MatterOverdrive#432]
1. I am 21 years old, and have been modding minecraft for over 2 years. This is, if not my favorite mod, definitely up there (top 3)

2. I found another mod, by Cr0s, which you should take a look at. It's called the "Warp Drive" mod. It is another Sci-Fi themed mod, which would work wonderfully with yours. Also like yours, it is a somewhat new mod, in its early stages, and so things are being added/updated frequently (which means Cr0s is still active). I strongly recommend you check out Cr0s' work. If you two teamed up and merged your mods, you could have an unstoppable (and very Star-Trek/Sci-Fi) mod! His mod focuses more on the space travel side of Star Trek, which I think would fit in well with your mod, especially the quests. Check it out here: --- https://github.com/Cr0s/WarpDrive/wiki ---

3. If you want (and I am not a coder, although I have experience in modelling and animation), I would love to help out with your mod. I have some ideas for the quest system, to make it very advanced. I have been, and still am, working on a system for making randomized, incontinuous quests, that work like "episodes." I think that a quest system like that could make any game far more interesting. Anyway, let me know if you're interested!

4. I really want to stress that I think merging "Matter Overdrive" with "Warp Drive" would be the most amazing thing ever. I think it would be very feasible, and a lot of mincrafters would love it! I hope this helps!

sincerely,
    Beadsmith2

P.S. I am also a Trekkie, Whovian, Star Wars fan, LotR fan, and much much more. Sci-fi/fantasy is my thing, and I actually intend to start a film company at some point (hopefully soon - working on a script write now!), making Scifi/fantasy films.

**Comment by ajthemacboy** [comment]
A possible portal reocmmendation to fit the Star Wars theme: Transwarp conduits. Also other BORG inspired tech.

**Comment by shadowfacts** [comment]
We considered this a while ago, and decided it would take more time than it's worth.
