### ISSUE TITLE
No recipe for holographic sign

### ISSUE THREAD

**Issue by TheNumenorean** [simeonradivoev/MatterOverdrive#433]
Newest version, NEI isn't showing a recipe for the holographic sign. There also is no recipe shown on the wiki.

**Comment by TheNumenorean** [comment]
Checking the recipe I was able to find in the recipes file, it does not work.

**Comment by simeonradivoev** [comment]
So can you craft the sign or not ?

**Comment by TheNumenorean** [comment]
No

**Comment by TheNumenorean** [comment]
This should now be fixed. Will there be an official update pushed soon, or should I just use a development build?

**Comment by shadowfacts** [comment]
Use the development builds, it is unlikely there will be any other release versions of MO before 1.8.

**Comment by TheNumenorean** [comment]
A question: Considering that this broken recipe prevents replication and fusion reactors from working, shouldn't there be a 1.7 release? People aren't going to instantly move to 1.8

**Comment by TheNumenorean** [comment]
Also, the dev builds don't work

**Comment by shadowfacts** [comment]
ba09ffde9501231b0e06f16c18b2f51b25cb4995 should fix the dev builds.
