### ISSUE TITLE
Mad scientist crashing when right clicked

### ISSUE THREAD

**Issue by swarley1998** [simeonradivoev/MatterOverdrive#436]
I was in a village and i found a building meant for mad scientists, there wasn't one so i spawned one in with NEI and when I right clicked on him the GUI popped up for roughly 5 seconds and then my game crashed back to the launcher, if it helps I've been playing on a mod pack called Revenge of the C-team, here is the crash report.

http://pastebin.com/wmR1CszF

**Comment by simeonradivoev** [comment]
It seems that this is a speedytools error. They will need to check if the player is of a specific type.
