### ISSUE TITLE
How to Reinstate Biological Existence

### ISSUE THREAD

**Issue by Alazu** [simeonradivoev/MatterOverdrive#44]
Once you inject yourself all the android parts, with the help of the scientist you can't return back to normal maybe the way you  could revive your fleshy body, with the help of the radioactive failed animals, but thats just my opinion..... Unless Permanent Robotification is your goal

**Comment by simeonradivoev** [comment]
I will add a way to turn back, Just thinking of a cool way to that.

**Comment by Alazu** [comment]
Add that?

**Comment by shadowfacts** [comment]
Closed in favor of #56
