### ISSUE TITLE
Bugged chat after mod installation

### ISSUE THREAD

**Issue by axelpx** [simeonradivoev/MatterOverdrive#440]
"=============================" are added before every message in chat after I install your mod on my server. Everything is ok in singleplayer. Can you help?

![chatbug](https://cloud.githubusercontent.com/assets/1360553/13006541/94e26b9c-d19a-11e5-852c-d03ce6304aa9.JPG)

**Comment by shadowfacts** [comment]
Are you 100% sure this is caused by Matter Overdrive? I'm fairly certain MO does nothing regarding the chat.

**Comment by axelpx** [comment]
We have a lot of mods installed. 

Yesterday I've spent the whole night deleting all the mods 1 by 1 from the server and nothing changed. Then I've deleted all the mods from client, and started adding them 1 by 1 again. Chat became corrupted after i've added Matter Overdrive to client. Btw console doesn't have those '================' in it, so the must be added clientside (singleplayer is fine though).

Just checked it again: deleted MO from client and server - chat is fine now.

Mods list on client:
![default](https://cloud.githubusercontent.com/assets/1360553/13012477/7afa41e2-d1bc-11e5-94b7-0190eba1b7ba.JPG)

**Comment by shadowfacts** [comment]
Well it's certainly not Matter Overdrive, as I'm very sure MO doesn't interact with the chat like that.

Try removing mods except for MO to isolate which one breaks when MO is present.

**Comment by axelpx** [comment]
I'll do it, but later :) Im too tired removing all mods for the third time) its like 73 server and client restarts all over again... its gonna be a long night XD

**Comment by Anigami** [comment]
"=============================" are added before every message in chat after I install your mod on my server. Everything is ok in singleplayer. Can you help?
![screenshot_2](https://cloud.githubusercontent.com/assets/10668706/13654696/d0b622be-e66a-11e5-840e-1a816f0d8203.jpg)

**Comment by ajthemacboy** [comment]
FastCraft has various chat options... could it be one of those? Try removing FastCraft temporarily.

**Comment by Anigami** [comment]
![screenshot_3](https://cloud.githubusercontent.com/assets/10668706/13661220/e15a97e4-e6a1-11e5-92b3-91305c217ff7.jpg)

**Comment by Barhandar** [comment]
Can anyone NOT running Russian language confirm this?

**Comment by sheynandr** [comment]
#503
