### ISSUE TITLE
java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory

### ISSUE THREAD

**Issue by Tsyklop** [simeonradivoev/MatterOverdrive#447]
I download src from here. and I compiled it.

After starting so that's an error:

http://pastebin.com/w2Zw0wr7

**Comment by Tsyklop** [comment]
Not fixed: https://github.com/simeonradivoev/MatterOverdrive/issues/441

**Comment by shadowfacts** [comment]
Are you using the latest dev build?

**Comment by Tsyklop** [comment]
@shadowfacts no. I download github repository and build it "gradlew build".

**Comment by Tsyklop** [comment]
@shadowfacts i download laset dev build and all fine:)

**Comment by shadowfacts** [comment]
If you use the repository, you need to make sure you check out the `1.7.10` branch in git.
