### ISSUE TITLE
Android Part loss

### ISSUE THREAD

**Issue by Lizarman200** [simeonradivoev/MatterOverdrive#453]
Whenever I die using the Sync mod I lose my equipped android parts. At first I thought it might be where I died but when I go back I cant find it. It should be noted that I am using the Openblocks grave too and it wasn't there when I broke my grave.

Steps to reproduce: Just die using Openblocks and Sync.

MatterOverdrive version: 4.1

Minecraft version: 1.7.10

**Comment by shadowfacts** [comment]
No longer applicable as neither OpenBlocks nor Sync are updated to 1.10.2.
