### ISSUE TITLE
Matter Overdrive and CustomNPCs Incompatibility

### ISSUE THREAD

**Issue by axelpx** [simeonradivoev/MatterOverdrive#454]
Brief explanation of problem:
If you go anywhere near NPC being an Android from Matter Overdrive mod, game crashes.

Steps to reproduce:
Same as in the "explanation of problem"

Crash report paste (if any) on [gist](gist.github.com):
http://pastebin.com/Tqky0KKu

MatterOverdrive version:
MatterOverdrive-1.7.10-0.4.1

Minecraft version:
1.7.10, KCauldron server

**Comment by simeonradivoev** [comment]
Same as #448

**Comment by simeonradivoev** [comment]
I think they fixed in their latest version
