### ISSUE TITLE
Galacticraft intergration

### ISSUE THREAD

**Issue by Shurik1236** [simeonradivoev/MatterOverdrive#455]
По английски я не умею, буду краток. Переведёте в google.

Зачем роботу кислород? Ну, ладно термо-костюм. Техника не выносит жару и холод.
Но кислород то зачем? Не логично.
<a target="_blank" href="http://radikal.ru/fp/940bc30cb0e54db2ae3126da84653d6e"><img src="http://s017.radikal.ru/i435/1602/f4/5e8404df7819t.jpg" ></a>

**Comment by simeonradivoev** [comment]
Integration with Galacticraft will happen as soon as they update to 1.8
