### ISSUE TITLE
Reactor Controller Crash

### ISSUE THREAD

**Issue by enterprise12nx** [simeonradivoev/MatterOverdrive#457]
Brief explanation of problem: one of my players made a reactor and when it established, the server crashes.

Steps to reproduce: Build reactor

Crash report paste (if any) on [gist](gist.github.com): https://gist.github.com/enterprise12nx/df27b26d9312648fed7a

MatterOverdrive version: MatterOverdrive-1.7.10-0.4.1

Minecraft version: 1.7.10

**Comment by ajthemacboy** [comment]
See https://github.com/simeonradivoev/MatterOverdrive/issues/446. Should be fixed in the latest version. If not compile from source.

**Comment by enterprise12nx** [comment]
is it fixed in this version?
MatterOverdrive-1.7.10-0.4.1-build-26.jar

**Comment by ajthemacboy** [comment]
If you got that build from the website, as far as I know all beta/builds are broken from there. I recommend compiling from the 1.7.10 branch source, as I've tested it myself and it should be up to date.

The website may have the latest builds compiled from source but I haven't tested them, so I can't guarantee it, and many of the ones on the website have a crash on startup.

**Comment by simeonradivoev** [comment]
The build should not be broken anymore.

**Comment by enterprise12nx** [comment]
@simeonradivoev i will give it a try
@ajthemacboy i have no idea how to compile, im just starting programming in college in CST112

**Comment by ajthemacboy** [comment]
@enterprise12nx It's pretty easily actually, I do it all the time with almost no programming knowledge. This may not work completely for MatterOverdrive but the basic steps should follow.

1. Install Git for your platform: https://git-scm.com/downloads
2. Install Gradle for your platform: http://gradle.org/
3. Open a Terminal or Command Prompt, navigate the directory where you want to clone the repository, and type `git clone -b 1.7.10 https://github.com/simeonradivoev/MatterOverdrive`
4. Navigate to the repository you just cloned and type `gradle build`. 

The final jar should appear somewhere, maybe the `target` folder under the cloned repository, fairly easy to find.
