### ISSUE TITLE
Infinite power draw using ElectriCraft RF cabling

### ISSUE THREAD

**Issue by Pyrolusite** [simeonradivoev/MatterOverdrive#460]
**Brief explanation of problem:**
Infinite power draw from MO Solar Panels when using ElectriCraft RF Cables.
The buffer goes in the negatives while the Charging Station gets a lot of RF, all of that at night.

![Negative SP buffer](http://i.imgur.com/hTuz3ti.png)
![Setup](http://i.imgur.com/jt9cxJL.png)

**Steps to reproduce:**
cf. screenshots provided.

**MatterOverdrive version:**
0.4.1 build 35 for Minecraft 1.7.10

**Additionnal notes :**
It doesn't happen when using Buildcraft kinetic pipes.

**Comment by shadowfacts** [comment]
No longer applicable as ElectriCraft hasn't been updated to 1.10.2
