### ISSUE TITLE
New to the mod

### ISSUE THREAD

**Issue by ohbradman** [simeonradivoev/MatterOverdrive#461]
I dont want to be the android anymore is there anyway i can toggle it off?

**Comment by ajthemacboy** [comment]
You can take one of the pills, I don't remember which.. you can find them in crashed ship chest or from villagers.

**Comment by ohbradman** [comment]
i have the android ability on and im not liking it, is there a way i can turn it off i took the red pill btw.

**Comment by simeonradivoev** [comment]
You can turn into a human using the Blue pill, found at Dungeon chests and sold by mad scientist.
The only way to unlearn abilities is to reset them all by eating a Yellow pill found at Dungeon chests and sold by mad scientist.

Please Use the IRC #matteroverdrive chat for questions regarding the mod. This is a place for Issues and requests.

**Comment by ohbradman** [comment]
oh thanks man,
yes sorry didnt realise this wasnt the right place i will know for next time.

again thanks man!
