### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by Fariyan** [simeonradivoev/MatterOverdrive#463]
Brief explanation of problem:well it just crashes every time i load it

Steps to reproduce:what? i dont  understand

Crash report paste (if any) on [gist](gist.github.com):https://gist.github.com/Fariyan/3c918fc6a3eeb701681c

MatterOverdrive version :MatterOverdrive-1.7.10-0.4.0

Minecraft version:forge-1.7.10-10.13.4.1517-1.7.10

**Comment by simeonradivoev** [comment]
For version lower than 0.4.1, Cofh Lib is required.
