### ISSUE TITLE
please help my game always crash

### ISSUE THREAD

**Issue by MrSasan** [simeonradivoev/MatterOverdrive#464]
Brief explanation of problem: my game always crash when i open it please help

Steps to reproduce:

Crash report paste (if any) on [gist](gist.github.com): https://gist.github.com/MrSasan/be5451420bf869112b8b

MatterOverdrive version: 0.4.1

Minecraft version: 1.7.10 - Forge 10.13.4.1614

**Comment by simeonradivoev** [comment]
http://hopper.minecraft.net/help/pixel-format-not-accelerated/

**Comment by MrSasan** [comment]
My Video cards are all up to date still doesnt work :(

**Comment by simeonradivoev** [comment]
So without MO it will not crash ?

**Comment by MrSasan** [comment]
yeah

**Comment by MrSasan** [comment]
is it because i installed Java 8 ? cuz i readed that i Java 8 i had java 7 befor but it was still crashing

**Comment by simeonradivoev** [comment]
Java 8 is required. So no

**Comment by MrSasan** [comment]
found out 64bit java 8 doesnt work but java 7 64bit works :( well rip my FPS

**Comment by simeonradivoev** [comment]
So Java 7 works with MO ?

**Comment by MrSasan** [comment]
no i was saying java 8 64 bit wasnt working for MO 32 bit works

**Comment by shadowfacts** [comment]
@MrSasan Don't use MineShafter, ***buy the game***. Any further issues posted using MineShafter will not receive support.
