### ISSUE TITLE
Galaxy is Missing Error

### ISSUE THREAD

**Issue by XDragonAce** [simeonradivoev/MatterOverdrive#467]
I just installed the 0.4.1 version of the mod and whenever I try to load a world, it freezes and says "Shutting down internal server". When I look at the game output, it says "Galaxy is missing". I have even attempted to run the mod by itself but it still does not work. 

MatterOverdrive version: 0.4.1

Minecraft version: 1.7.10

**Comment by Alexismachina** [comment]
Can you give a log ?

**Comment by XDragonAce** [comment]
**With the map on website**
Here's the game output
[first loading attempt error.txt](https://github.com/simeonradivoev/MatterOverdrive/files/178829/first.loading.attempt.error.txt)
Here's the crash report
[crash-2016-03-17_19.03.11-client.txt](https://github.com/simeonradivoev/MatterOverdrive/files/178830/crash-2016-03-17_19.03.11-client.txt)

**With new world**
Game output:
[error.txt](https://github.com/simeonradivoev/MatterOverdrive/files/178832/error.txt)
Crash report:
[crash-2016-03-17_19.05.58-client.txt](https://github.com/simeonradivoev/MatterOverdrive/files/178833/crash-2016-03-17_19.05.58-client.txt)

**Comment by XDragonAce** [comment]
also for some reason, this did not happen when i loaded with ftb infinity evolved with every mod there enabled as well as matter overdrive

**Comment by simeonradivoev** [comment]
Have you tried using the latest Dev builds for 1.7.10 ?

**Comment by XDragonAce** [comment]
I have and I've also tried 0.4.0. It seems like it only works for me when in certain modpacks.

**Comment by XDragonAce** [comment]
Also, I don't know if you could fix this, when in one block high morphs, like the bat, from the morph mod, the weapons still shoot from around the head level when non-morphed. So like if I use the bat morph, it would shoot above me.

**Comment by shadowfacts** [comment]
1.7.10 is no longer being supported.
