### ISSUE TITLE
White screen issue

### ISSUE THREAD

**Issue by baceball7666** [simeonradivoev/MatterOverdrive#469]
Brief explanation of problem:
When i join the server i play on, it immediately white screens and then crashes back to the launcher

Steps to reproduce:
launch into the server after unlocking the minimap in previous play session

Crash report paste (if any) on [gist](gist.github.com):

MatterOverdrive version:
0.4.1

Minecraft version:
1.7.10

Here is the modpack
http://www.technicpack.net/modpack/astronautics.791072

**Comment by shadowfacts** [comment]
Please provide the fml-client-latest.log

**Comment by shadowfacts** [comment]
User hasn't provided more info and 1.7.10 is no longer being supported.
