### ISSUE TITLE
Adding warp energy, phaser arrays and photon torpedoes

### ISSUE THREAD

**Issue by minebuild3543** [simeonradivoev/MatterOverdrive#476]
Well, what's a Star Trek mod without all the ship systems?
Shields would be built using the MFFS mod; warp speeds can be achieved with WarpDrive.
But what about warp power and weapons?
I am proposing.
1) Make a Warp Core system. That would require antimatter pods, deuterium tanks, containment fields. The core would generate RF.
2) If we're talking about WarpDrive compatibility, add an energy converter.
3) Phaser arrays with a controller block. Would use RF, lots of it - a warp core would be used.
The system works like that:
You build the array, connect it to your power network, place the controller block on your "bridge", at the "tactical station".
When the enemy vessel approaches, you click on the controller block.
A GUI would open, showing you the surrounding environment, something like the sensor network.
Click on a spot. The phaser array fires.
4) Photon torpedoes. The mechanics could be based on TNT minecarts, but they won't fall down.
You would be able to set the detonation countdown.
5) And most of all. Auto-destruct sequence.

**Comment by minebuild3543** [comment]
Concept arts would be provided soon.

**Comment by shadowfacts** [comment]
Wayyyy out of the scope of this mod, not to mention completely unfeasible. Your ideas might be possible if there was a team of developers working full time on MO, but it's just Simeon and occasionally myself.
