### ISSUE TITLE
Matter Registry Tritanium Ingot

### ISSUE THREAD

**Issue by rheimus** [simeonradivoev/MatterOverdrive#479]
Brief explanation of problem:
Seems that tritanium ingots will not register in the matter registry, adding either ore dict ingotTritanum or mo:ingot_tritanum to the new_items list will not change the value from none.

Everything else I have attempted to add to the registry has worked fine so far including other items from MO like the circuits.
[fml-server-latest.txt](https://github.com/simeonradivoev/MatterOverdrive/files/201213/fml-server-latest.txt)

Steps to reproduce:
Attempt to add tritanium ingots to registry

MatterOverdrive version: 0.4.1

Minecraft version: 1.7.10

**Comment by simeonradivoev** [comment]
Yes this is planned. It is done for balancing purposes.

**Comment by rheimus** [comment]
fair enough i suppose, :)
