### ISSUE TITLE
Railcraft Invisible Blocks Broken by Gravitation Anomaly

### ISSUE THREAD

**Issue by Thunder7102** [simeonradivoev/MatterOverdrive#480]
**Brief explanation of problem:**
When standing within range of a gravitation anomaly, Railcraft 'heat exchange' items will fly past you into the anomaly or collect inside your inventory. When speaking with the Railcraft developers, they mentioned it was the fault of the anomaly breaking all blocks, not excluding invisible ones. 
**Steps to reproduce:**
Install Railcraft and Matter Overdrive. Use creative mode or stay within range of a gravitation anomaly which has been grown. railcraft heat exchange items (they look like desert dead bushes with a different name) will fly into your inventory consistently as long as you stay within range of the anomaly. 
**Crash report paste (if any) on [gist](gist.github.com):**
None
**MatterOverdrive version:**
0.4.1
**Minecraft version:**
1.7.10

**Comment by shadowfacts** [comment]
No longer applicable as Railcraft hasn't been updated to 1.10.2.
