### ISSUE TITLE
[Suggestion] Allow IC2 Compatibility and showing of EU units instead of RF

### ISSUE THREAD

**Issue by Thunder7102** [simeonradivoev/MatterOverdrive#481]
If possible, please allow the mod to take compatibility from IC2 power sources for charging and taking power in addition to displaying power units in EU as opposed to RF. Please include config-available conversion ratios if possible.

**Comment by simeonradivoev** [comment]
That would require a lot of work. Supporting another Electricity system.

**Comment by Thunder7102** [comment]
This is a mod that has all the features I've mentioned and I figured it'd be a useful reference. 

https://github.com/MachineMuse/MachineMusePowersuits

**Comment by shadowfacts** [comment]
It's not that we don't know how to do it, it's just a massive change and would require large amounts of code to be rewritten.

**Comment by aiRobot13** [comment]
I can imagine.

that would be an absolute ton of work to do.

**Comment by shadowfacts** [comment]
Tesla is supported as well as RF in 1.10.2. EU won't be (without major changes to the EU API) due to technical reasons.
