### ISSUE TITLE
trying to add Items with Meta data like dyes in configs to the Matter Registry: not working

### ISSUE THREAD

**Issue by mariodk** [simeonradivoev/MatterOverdrive#484]
Brief explanation of problem:

trying to add Items with Meta data like dyes in configs to the Matter Registry
”tile.projectred.exploration.stone|2″ (on the website) does not work at all
i tried: "minecraft:dye|15"=16 (for bonemeal)
does not work 
i tried ingame command & holding bonemeal(or other item with metadata) it just become:
I:"minecraft:dye"=16 and not working for any dyes

i tried alot of stuff with many other items that are like that 
nothing really works i have tried everything (also tried to find other modpacks with matter overdrive but no one really edited that part of the configs)

i would love if we could have something like use the same names like for minetweak
bonemeal is: <minecraft:dye:15>
for minetweak or even use Minetweak to add items to matter registry(and still for 1.7.10 updates mainly for fix this problem with adding items with meta data like Dyes)
also kinda would love to have ingame command for remove item/oredicts
and if using a ingame command for a Existing items/oredicts in the Matter Registry
it will go into item overrides instead of new items
or maybe a Creative only Item that can edit with Matter Registry with its own GUI

also tried with the stone monster egg blocks(since they also have meta data)
tried all of this:
        I:"minecraft:monster_egg,1"=666
        I:"minecraft:monster_egg,2"=777
        I:"minecraft:monster_egg.1"=666
        I:"minecraft:monster_egg.2"=777
        I:"minecraft:monster_egg:1"=666
        I:"minecraft:monster_egg:2"=777
        I:"minecraft:monster_egg;1"=666
        I:"minecraft:monster_egg;2"=777
        I:"minecraft:monster_egg|1"=666
        I:"minecraft:monster_egg|2"=777
nothing worked and if just do: 
        I:"minecraft:monster_egg"=777
again not working (only on the item that has 0 meta data but not on the others)

MatterOverdrive version: 0.4.1

Minecraft version: 1.7.10

**Comment by simeonradivoev** [comment]
Yes this is a limitation of the 1.7.10 MC version. The matter registry has been reworked in 1.8.9 and 1.9. You can try and download the 0.4.2 version of MO for minecraft 1.7.10 it uses registry names and not unlocalized names.

**Comment by mariodk** [comment]
i only see 0.4.2 for 1.8.9 not for 1.7.10

**Comment by simeonradivoev** [comment]
Yes, my bad I edited the comment.
