### ISSUE TITLE
No recipes for all these blocks, is there supposed to be?

### ISSUE THREAD

**Issue by b0bst3r** [simeonradivoev/MatterOverdrive#485]
Brief explanation of problem:
No recipes

Steps to reproduce:
Try to look for recipe in NEI

MatterOverdrive version:
0.4.1 build 35

Minecraft version:
1.7.10

Affected blocks
Tritanium Lamp
All blocks which start <color> Colored Tritanium Plate - for example Red Colored Tritanium Plate

**Comment by simeonradivoev** [comment]
There have recipes in 1.9. I might add some in 1.7.10.

**Comment by b0bst3r** [comment]
I tried to minetweaker the colored blocks in but you add a recipe for 1 and it changes them all to that color so maybe something not quite right in the code.
