### ISSUE TITLE
Crash on the-you guessed it-the matter analyser GUI! Three pack!

### ISSUE THREAD

**Issue by KILLAKAN10** [simeonradivoev/MatterOverdrive#487]
Crash after accessing pattern monitor after scanner gui.
http://pastebin.com/zNctaLhi

and just my luck, firing a left-click reactive weapon, after accessing scanner GUI- and visa-versa.
http://pastebin.com/BpUhQkzS

I am also finding problems with the creative storage drive, just by using it in a storage.
http://pastebin.com/52jpWgdV

Thanks for having a look.

MatterOverdrive version: 0.4.1

Minecraft version:1.7.10

**Comment by simeonradivoev** [comment]
Duplicate #482
