### ISSUE TITLE
Coils and Communication Relay(quest item) have the same ID

### ISSUE THREAD

**Issue by Vhnori** [simeonradivoev/MatterOverdrive#488]
So I did the quest to make the Security Protocal and got the Communication Relay. I placed the relay near the crashed ship but when I did, it instantly just turned into the Coils block. I looked and it seems that they both have the same ID and image. Is this intentional?

MatterOverdrive version: 0.4.1

Minecraft version: 1.7.10

**Comment by simeonradivoev** [comment]
That's because it's just a coils block but renamed.

**Comment by netzgeist** [comment]
This leads to my not being able to complete the 2nd given Quest. "Place the Communication Relay near the ship at .."

**Comment by simeonradivoev** [comment]
You can just rename the block in an anvil to the same name and it should work.

**Comment by netzgeist** [comment]
Did so and it worked. Good thing you're here! Though maybe consider changing this. If I weren't online and aware of github my questchain would be uncompleteable by now.

**Comment by vrelk** [comment]
I am having the same issue. I placed it after being given the item. After I found this, I tried renaming the block since it had reverted back to coils but still no luck. I am using the same version as Vhnori.

**Comment by netzgeist** [comment]
Rename the coil in an anvil. Place it and remember that you will have to
place it inside the ship. If that doesn't work for your version, update.


2016-04-30 7:28 GMT+02:00 Controller Vrelk <notifications@github.com>:

**Comment by Zsashas** [comment]
Are there any quests after this, or just the two?

**Comment by Slif51** [comment]
I may or may not have destroyed the ship before getting to this part, and I tried renaming the coils and placed them at the spot where the data pad says to, but still no luck. Is there anything I can do?

**Comment by Muirrum** [comment]
Slif, you are responding to a post which is now 10 months old.
