### ISSUE TITLE
NullPointerException: Ticking entity, mod incompatibility 

### ISSUE THREAD

**Issue by lightning02** [simeonradivoev/MatterOverdrive#489]
Brief explanation of problem: This happens when you try to break an ender chest with omni tool 

Crash report paste (if any) on [gist](gist.github.com): http://pastebin.com/XkGTfcfS

MatterOverdrive version: 0.4.1-build-35

Minecraft version: 1.7.10

**Comment by simeonradivoev** [comment]
The crash was actually caused by enderstorage. I will have to look into it.

**Comment by shadowfacts** [comment]
Dupe of #499
