### ISSUE TITLE
Rouge Androids Not spawning

### ISSUE THREAD

**Issue by Gr12zly** [simeonradivoev/MatterOverdrive#49]
This is occurring in Horizons: Daybreaker. The mad scientist is spawning, however, the Rouge Androids are not spawning anywhere. I have done more than 15 hours of searching to no avail.

**Comment by simeonradivoev** [comment]
It seems to spawn fine in my worlds. You can try and increase the spawn chance in the Mod Options.

**Comment by Gr12zly** [comment]
I thought about that, and I was going to talk to the server admin about it, but then I saw a post on the forums about how another person was having no spawns at all either

**Comment by Gr12zly** [comment]
update: We set the spawn rate as high as 70 and still no spawns at all.

**Comment by shadowfacts** [comment]
Is someone using a Extra Utilties Magnum Torch  (or any other spawn-blocking item) nearby?

**Comment by Gr12zly** [comment]
No, wind mages, and vanilla mobs are all spawning. Its literally just the android that isn't

**Comment by shadowfacts** [comment]
Hmm, what biome are you in?

**Comment by Gr12zly** [comment]
I have traveled more than 8k blocks looking for one, I went to Taiga, Extreme Hills, Plains, and all kinds of others

**Comment by shadowfacts** [comment]
Can you test in a fresh single player world, please?

**Comment by Gr12zly** [comment]
I will now

**Comment by simeonradivoev** [comment]
I tested it on SP with the Horizons Modpack and it works. Where did you download the server from ?

**Comment by Gr12zly** [comment]
From the FTB launcher

**Comment by Gr12zly** [comment]
Are there any special conditions or anything that I may be missing?

**Comment by simeonradivoev** [comment]
none that i know of

**Comment by simeonradivoev** [comment]
was the server reset after the spawn rate change ?

**Comment by Gr12zly** [comment]
Yes it was, as well as we disabled head crumbs to see if the FTB mobs were preventing it.

**Comment by Gr12zly** [comment]
So far no spawns in SP either

**Comment by shadowfacts** [comment]
Can you use Dropbox (or something similar) to send us an .zip of your instance folder?

**Comment by simeonradivoev** [comment]
I just downloaded the server and the client form FTB launcher and created a new world and it works. I have no clue what the problem might be.

**Comment by Gr12zly** [comment]
I am getting a link ready now, are you finding yours randomly in the world?

**Comment by simeonradivoev** [comment]
yes after 1 minute i found 2 in a Extreme Hills biome, with 70 spawn chance.

**Comment by Gr12zly** [comment]
hmmmm that is very odd, i changed the spawn rate back on my client because it didn't affect it

**Comment by simeonradivoev** [comment]
So even in SP there were no spawns ?

**Comment by Gr12zly** [comment]
No there weren't for me, i searched for 10 minutes, 5 on 70 and 5 on default, but no dice

**Comment by Gr12zly** [comment]
https://www.dropbox.com/s/uxzec5t9366mxjl/FTBHorizonsII.zip?dl=0

**Comment by simeonradivoev** [comment]
Tested it with your version, and still works. Androids spawn.

**Comment by simeonradivoev** [comment]
It seem the Rouge Android spawns only in Extreme Hills for some reason. There might be a mod that changes the vanilla bioms.

**Comment by shadowfacts** [comment]
@simeonradivoev Try disabling Realistic World Gen and creating a new world. I'm not sure if that replaces Vanilla biomes, but it might. I'll take a look at adding compat for it later.

**Comment by Gr12zly** [comment]
ah thank you very much!!!

**Comment by shadowfacts** [comment]
I take it that fixed the problem?

**Comment by Gr12zly** [comment]
honestly no idea, as I haven't been able to find extreme hills yet

**Comment by shadowfacts** [comment]
Yep Rogue Androids don't spawn in RWG biomes as of 0.3.5. However, this has been fixed for 0.3.6.

For now I'm not sure if there's anything you can do other than spawn them in or wait. You *might* be able to use RFTools to make a vanilla biome dimension.
