### ISSUE TITLE
SMP server crash on MatterOverdrive-1.9-0.4.3-build-40

### ISSUE THREAD

**Issue by b0bst3r** [simeonradivoev/MatterOverdrive#492]
Brief explanation of problem: Crash on SMP Server startup

Steps to reproduce: Create 1.9 SMP Server and launch

Crash report paste (if any) on [gist](gist.github.com): http://pastebin.com/N3kTiUK5

MatterOverdrive version: 1.9-0.4.3-build-40

Minecraft version: 1.9

**Comment by simeonradivoev** [comment]
Minecraft forge 1.9 is still in development. They change a lot of stuff. It is just not feasible to update every single time a change has been made in the beta version of Forge.

**Comment by b0bst3r** [comment]
So what Forge version will this work on?

**Comment by simeonradivoev** [comment]
I don't remember. Now that I look at it might be a thing on my part. The 1.9 is still wip.
