### ISSUE TITLE
Fusion Reactors on a server being destroyed even tho 6 stabilizers are active

### ISSUE THREAD

**Issue by rhaejr** [simeonradivoev/MatterOverdrive#495]
Brief explanation of problem:
We have created 2 different fusion reactors around anomalies on our server and both have had 6 stabilizers, but they somehow keep somehow eating our reactor. We set them up and they work great until we all log off for the night and the next day all we have left is an anomaly. Are server restarts causing the anomaly to eat the reactor before its loaded in or something? We can't figure it out. 
Steps to reproduce:
We built 2 and it happened both times
Crash report paste (if any) on [gist](gist.github.com):

MatterOverdrive version:
1.7.10-0.4.1
Minecraft version:
1.7.10

**Comment by simeonradivoev** [comment]
It may be because of chunk loading. If the stabilizers are in a different chunk and that chunk stays unloaded it will not affect the anomaly. That's just how minecraft works. You can try and chunkload all the chunks containing  the stabilizers.

**Comment by rhaejr** [comment]
I will try making sure they are/ were loaded. thanks for the fast reply.

**Comment by rhaejr** [comment]
I made sure the stabilizers were in the same chunk and it happened again. I placed them close to the anomaly because I didn't have time to move it.

**Comment by simeonradivoev** [comment]
Yes it would be wise.

**Comment by rhaejr** [comment]
Every component of the reactor was in the chunk that was loaded and we did a server restart. 3 stabilizers were gone and all of the power conduit and item conduit was gone. We are using the ferret business pack. I am going to report this to the pack forum as well since this issue could be becuase of the other mods.

**Comment by Frostthejack** [comment]
I too have had the same issue. Everything is in the same chunk and the chunk is always loaded if I'm logged in but this happens sometimes

**Comment by eRixxje** [comment]
Having the same problem on Bevo's Tech Pack. Every time I restart the server, i find some stabilizers to be gone and the anomaly grown to 'eat' its surroundings. The reactor is chunkloaded. It never happens when logging in after leaving the game. It always happens after a server restart.

Could it be that the anomaly is loaded before the stabilizers are? If this is the case, would it be a solution to enlarge the timespan for the anomaly to check for stabilizers?
