### ISSUE TITLE
Crash when entering server/world

### ISSUE THREAD

**Issue by Coolmanzz2** [simeonradivoev/MatterOverdrive#497]
Brief explanation of problem:
  Crash when logging in to world
Steps to reproduce:
  Become android and get the minimap upgrade
Crash report paste (if any) on [gist](gist.github.com):
  http://paste.ee/p/XoIy1
MatterOverdrive version:
  MatterOverdrive-1.7.10-0.4.1
Minecraft version:
  1.7.10

**Comment by b0bst3r** [comment]
Try build 35 from here http://simeon.co.vu/Mods/MatterOverdrive/builds/ pretty sure it's been fixed.

**Comment by Coolmanzz2** [comment]
It's fixed thank you
