### ISSUE TITLE
1.9 - NoClassDefFoundError: com/mojang/realmsclient/gui/ChatFormatting

### ISSUE THREAD

**Issue by Telemain** [simeonradivoev/MatterOverdrive#504]
Brief explanation of problem: Try to start server with only matter overdrive mod and server crashes

Steps to reproduce: Used forge installers to create server, dropped matter overdrive into mod folder and started server

Crash report paste (if any) on [gist](gist.github.com): [Crash report](https://gist.github.com/Telemain/59fa8bd3ad78b92446533f9df00061ea)

MatterOverdrive version: `MatterOverdrive-1.9-0.4.3-build-40.jar`

Minecraft version:
Happens with all three
forge-1.9-12.16.1.1904
forge-1.9-12.16.1.1892
forge-1.9-12.16.1.1887

**Comment by shadowfacts** [comment]
89bc56fc3316e62b553da7ac63ff6a6ce6b2846e
