### ISSUE TITLE
Yet Another Crash (YAT)

### ISSUE THREAD

**Issue by bird1000000** [simeonradivoev/MatterOverdrive#505]
Brief explanation of problem:
The game crashes, cant open the save again without the game crashing.

Steps to reproduce:
Step 1: Make a new world
Step 2: Place down the starmap
Step 3: Click on one of the boxes (Quadrants I believe) on the left side of the GUI
Step 4 :Click on one of the planets on the the left hand side
Step 5: Congratulations! You Prema-Crashed your world

Crash report paste (if any) on [gist](gist.github.com):
http://pastebin.com/HWKk4Ffu
https://gist.github.com/bird1000000/de9e3dae2b582b5aa4f03d20e53db527

MatterOverdrive version:
MatterOverdrive-1.9-0.4.3-build-42.jar

Minecraft version:
1.9
1.9-forge1.9-12.16.0.1865-1.9

Other mods
jei_1.9-3.3.3.197
Wawla-1.9-2.2.0.186

**Comment by bird1000000** [comment]
EDIT: Still happens with latest version of forge and matter overdrive.
Forge 1.9.12.16.1.1907
Matter overdrive MatterOverdrive-1.9-0.4.3-build-47.jar

**Comment by shadowfacts** [comment]
4b59f7a60c3c50a38d059853d20b46cbdbd8b43e
