### ISSUE TITLE
1.9 - Client side methods being called on the server

### ISSUE THREAD

**Issue by Lazarix** [simeonradivoev/MatterOverdrive#507]
Brief explanation of problem: crash in MOStringHelper line 114 due to java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n

Steps to reproduce:

Crash report paste (if any) on [gist](gist.github.com): https://gist.github.com/Lazarix/5ae3146685728569bc95b3fe07517670

MatterOverdrive version: 1.9-0.4.3

Minecraft version: 1.9

**Comment by Lazarix** [comment]
Tried changing it to the below but did not solve the problem:

`        @SideOnly(Side.CLIENT)
        public static String translateToLocal(String string, Object... params)
        {
                return I18n.format(string, params);
        }

        public static String translateToLocal(PlanetStatType statType)
        {
                return I18n.format("planet_stat." + statType.getUnlocalizedName() + ".name");
        }

        public static String translateToLocal(UpgradeTypes type)
        {
                return I18n.format("upgradetype." + type.name() + ".name");
        }

        public static String weaponStatTranslateToLocal(int type)
        {
                return I18n.format("weaponstat." + type + ".name");
        }
`

**Comment by Telemain** [comment]
I also had this issue
[Crash report](https://gist.github.com/Telemain/45abfc7c1a83793012b1087c6c18a17a)

Using only
forge-1.9-12.16.1.1904
MatterOverdrive-1.9-0.4.3-build-43

**Comment by simeonradivoev** [comment]
The 1.9 Is still in Development. I've currently stopped the development of the mod so it won't be fixed anytime soon.

**Comment by Lazarix** [comment]
@simeonradivoev oh, I'm sorry to hear that. Are there plans to pick up development again?

**Comment by Alexismachina** [comment]
Probably when he gets bored of Unity. Even tough shadowfacts does some fixes time to time.

**Comment by Lazarix** [comment]
Fixed the code and issued a pull request. Tested it on my server and it works as expected now. Mod doesn't crash, server starts up and mod works.
Other issues found, will be creating other issues for those.

**Comment by shadowfacts** [comment]
119290ab9f169ab594a4da5cc317340f99f85e61
