### ISSUE TITLE
Android left eye

### ISSUE THREAD

**Issue by Chinthor** [simeonradivoev/MatterOverdrive#508]
Brief explanation of problem: 

Looking at a mob/entity shows a patch of garbled symbols and null characters. The mad scientist even comments on there being something wrong with your left eye. But there doesn't seem to be any way to fix it. This appears to be where "scanning data" should go. Name and vital stats of the targeted creature. That would be cool. But how does one change from garbage text to useful data?

Steps to reproduce: 

1. Become an android. 
2. Look at a creature of any kind.

Crash report paste (if any) on [gist](gist.github.com): 

n/a

MatterOverdrive version: 

0.4.0, included in the "Evolving Technology" pack, latest stable version.

Minecraft version: 

1.7.10

**Comment by simeonradivoev** [comment]
Maybe try and upgrade to MO 0.4.1

**Comment by Chinthor** [comment]
Ok. Tried that. Upgraded to Beta 0.4.1 and made no other changes to the pack. I cannot load a saved world or create a new one. There is no crash, but I get kicked back to the main menu. The launcher log that scrolls by shows mostly-fatal errors in connection with TiCon and related mods (because they fail if TiCon fails). I see that 0.4.1 has changes that affect TiCon. Does it require a certain version of TiCon?

**Comment by Chinthor** [comment]
Weird after note. Downgraded back to 0.4.0. The pack loads fine, and the eye glitch is gone. Make what you will of that.
