### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by itchibli** [simeonradivoev/MatterOverdrive#510]
sorry for my bad english, I speak french

Brief explanation of problem:
I have a server minecraft to play with my friends with MatterOverdrive. When I try to connect to the server a message disconect me: A fatal error has occured, this connection is termined, but the server doesn't crash. I can't connect to my server but it doesn't crash
Steps to reproduce:
[...]
Crash report paste (if any) on [gist](gist.github.com):
there are no crash report, the server and the game don't crash
MatterOverdrive version:
0.4 / 0.4.1 (I try 0.4 and 0.4.1 in the server, the versions don't function)
Minecraft version:
1.7.10

Keep me informed at: itchibli@gmail.com

**Comment by Alexismachina** [comment]
@itchibli Est-ce que la console du serveur imprime une erreur?

**Comment by Alexismachina** [comment]
@itchibli Regarde si la configuration de dans le dossier (config) dans Matter Overdrive est pareille avec celle du serveur.

**Comment by shadowfacts** [comment]
If it doesn't crash post the FML log.

**Comment by itchibli** [comment]
le message dans la console: itchibli lost connection: TextComponent{text='Disconnected', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
meme si je ne pense pas que sa a un rapport avec la deconextion

**Comment by itchibli** [comment]
shadowfacts 
what log, there is a lot of different logs

**Comment by itchibli** [comment]
the problem really comes from matter overdrive because if I uninstall I can connect

le probleme vient bien de matter overdrive car si je le désinstalle je peux me connecter

**Comment by itchibli** [comment]
may be that I have to reinstall the server on an older Forge version

**Comment by shadowfacts** [comment]
Post the most recent log (`logs/fml-client-latest.log` in your instance folder).

**Comment by itchibli** [comment]
http://www.partage-facile.com/U5N1QE86IV/fml_server_latest.log.html 

the log is too big

**Comment by itchibli** [comment]
you could find a solution to my problem ?

**Comment by itchibli** [comment]
@shadowfacts this is the good log ?

**Comment by shadowfacts** [comment]
As far as I can tell, nothing from Matter Overdrive caused that issue. Make your you have the same mods/versions/configs on the client and the server.
