### ISSUE TITLE
Advanced Genetics cloning no gun

### ISSUE THREAD

**Issue by Kezeal** [simeonradivoev/MatterOverdrive#512]
Brief explanation of problem: When cloning ranged Androids with Advanced Genetics the gun doesn't show up and the game will crash if you kill a ranged legendary without a gun.

Steps to reproduce: Get insulated helix from range android. Clone it.
For the legendary bug, keep cloning until a legendary spawns.

Crash report paste (if any) on [gist](gist.github.com): https://gist.github.com/Kezeal/2ee0853175ac35d0135fa7086f07adb7

MatterOverdrive version: 0.4.1

Minecraft version: 1.7.10

**Comment by Lazarix** [comment]
which build of 0.4.1 is it?

**Comment by Kezeal** [comment]
Both the file and the in-game mod list simply say "0.4.1". Where can I check which build it is?

**Comment by shadowfacts** [comment]
No longer applicable as Advanced Genetics isn't updated to 1.10.2.
