### ISSUE TITLE
Replicator tnt bug

### ISSUE THREAD

**Issue by hxpx** [simeonradivoev/MatterOverdrive#517]
Brief explanation of problem: When i was trying to create tnt in replicator and then right clicking on it i'm crashing

Steps to reproduce: step 1)Start produce tnt in replicator  step 2) Right click on replicator to open gui replicator

Crash report paste (if any) on [gist](gist.github.com): https://gist.github.com/hxpx/2039527d0617a781b806f6d7acc90315

MatterOverdrive version: 0.4.1

Minecraft version: 1.7.10

**Comment by lordtoucan** [comment]
Same thing is happening to me when I try to replicate a block of coal. Even after logging back in, and the process completes, my client still crashes EVERY time I attempt to right-click the replicator to open the GUI.

**Comment by simeonradivoev** [comment]
This should be fixed in the reworked replication system in 1.9+
