### ISSUE TITLE
[Suggestion / Question] How hard is it to port to 1.9.4?

### ISSUE THREAD

**Issue by Lazarix** [simeonradivoev/MatterOverdrive#520]
Considering that we have a build working on 1.9 now, how hard is it to fork again to 1.9.4?
The 1.9 builds don't currently work in 1.9.4

**Comment by shadowfacts** [comment]
Not hard, but both Simeon and I are busy. It will happen Soon™, definitely in-time for BTM16.2

**Comment by Lazarix** [comment]
Excellent, thanks for the update!
