### ISSUE TITLE
[1.9.4] See-through Hand Glitch

### ISSUE THREAD

**Issue by Alaberti** [simeonradivoev/MatterOverdrive#527]
Brief explanation of problem:
![2016-06-08_05 21 19](https://cloud.githubusercontent.com/assets/10929796/15881770/e2c570ee-2d38-11e6-9f6f-25f2bced71a4.png)
Hand is weirdly spectral. 

Steps to reproduce: 
Add forge, add mod, play game. 

MatterOverdrive version: 
1.9.4-0.4.4-build-52

Minecraft version: 
1.9.4, Forge 12.17.0.1954

Edit: Only using this mod. No Optifine etc.

**Comment by simeonradivoev** [comment]
Yes I get the same thing. I still can't trace where it's coming from.

**Comment by Kosti1** [comment]
I think its something fishy in forge
