### ISSUE TITLE
[1.7.10] Duping MO machines with Calculator wrench

### ISSUE THREAD

**Issue by MineWitherMC** [simeonradivoev/MatterOverdrive#528]
# Brief explanation of problem:
When you RMB-click on MO machine with calculator wrench while shifting machine drops but still exists in world. More info can be found here: https://youtu.be/nS6ewiBylcs, and this also happens with tritanium crate so...

# Steps to reproduce:
1. Place a MO machine that works with matter or Tritanium Crate (matter pipes aren't duping, network cables are);
2. Take Calculator wrench and Shift-Rmb-click on the machine.
Result: infinite machines. Items don't stay inside the machine though.

# MatterOverdrive version:
0.4.1 latest

# Minecraft version:
1.7.10

**Comment by simeonradivoev** [comment]
That's a bug on his part. He should use dismantleBlock not harvest block.

**Comment by simeonradivoev** [comment]
I suggested the fix https://github.com/SonarSonic/Calculator/pull/110
