### ISSUE TITLE
Disappearing Dilithium when mined with Iron or better pick.

### ISSUE THREAD

**Issue by Dragnier** [simeonradivoev/MatterOverdrive#529]
Brief explanation of problem: Data pad says you can mine Dilithium ore with any tool capable of iron or better mining. However, when I try to mine dilithium ore with an iron, tritanium, or equivalent pick; the ore disappears as if the mining level were too low

Crash report paste (if any) on [gist](gist.github.com): N/A

MatterOverdrive version: 0.4.4

Minecraft version: 1.9.4

**Comment by Alexismachina** [comment]
@Dragnier the 1.9.4 version is not complete , there is still a lot of bug.

**Comment by Dragnier** [comment]
@Alexismachina That is why I'm reporting the bug here. That way, it can be fixed.
