### ISSUE TITLE
Inventory goes invisible 

### ISSUE THREAD

**Issue by xhiyikfkox** [simeonradivoev/MatterOverdrive#532]
Brief explanation of problem: Inventory goes invisible after obtaining Matter Overdrive Guns

Steps to reproduce: Obtain a gun, have gun selected on hot bar and open inventory, close inventory, scroll to another item on hot bar, open inventory again to see its invisible, close inventory, scroll back to gun, open inventory, all is fine in inventory so long as you hold the gun or access an inventory like a chest, backpack or furnace.

Crash report paste (if any) on [gist](gist.github.com): None as dose not cause a crash just an in game graphics bug

MatterOverdrive version: 0.4.1

Minecraft version: 1.7.10

**Comment by simeonradivoev** [comment]
Yes I had that bug as well. It only happened with the phaser rifle for me. I have no idea what is causing that. It most certainly is another mod.

**Comment by xhiyikfkox** [comment]
I have it in a custom modpack, I have a text document with all the mods I have in the pack. If you would like I could provide a copy of that text document so you could compare it with other packs having the same issue and see what common mods might be causing it. I removed several mods attempting to try to fix it but the only specific one I was able to do so with was Matter Overdrive itself. It might be the renderer for the rifle itself perhaps? not sure.

**Comment by shadowfacts** [comment]
1.7.10 is no longer supported. Open a new issue if this is persistent in 1.9.4+ versions.
