### ISSUE TITLE
1.9.4 crash when emptying bucket of water in the air

### ISSUE THREAD

**Issue by Lazarix** [simeonradivoev/MatterOverdrive#534]
Unusual crash caused by trying to empty water into the air.

https://gist.github.com/Lazarix/32925bb3dd74d60b4e40a87dd743b1b0

MatterOverdrive version: 1.9.4-0.4.4-build-52

Minecraft version: 1.9.4

**Comment by Kosti1** [comment]
same with lava

**Comment by shadowfacts** [comment]
Closed in favor of #632.
