### ISSUE TITLE
Becoming an android results in disconnect from dedicated server.

### ISSUE THREAD

**Issue by cloakable** [simeonradivoev/MatterOverdrive#545]
Brief explanation of problem:
Becoming (and being) an android results in an instant disconnect from a dedicated server.

Steps to reproduce:
Become an android on a dedicated server.

Crash report paste (if any) on [gist](gist.github.com):
https://gist.github.com/cloakable/740f2af35d5c31d7a9725be0f991eac2

MatterOverdrive version:
0.4.4-build-55

Minecraft version:
1.9.4

**Comment by shadowfacts** [comment]
9cd4c48f950c973610eb9cfc5e067c3adac8c870
