### ISSUE TITLE
Plasma Weapons and Tinting GUI

### ISSUE THREAD

**Issue by Zsashas** [simeonradivoev/MatterOverdrive#546]
Brief explanation of problem:
Two-fold.

1: Using a Phaser causes the hotbar and other visible UI elements to darken noticeably. Simply holding the Phaser does nothing.
2: Simply holding a Plasma Shotgun with any color module causes UI elements to become tinted that color, this does NOT affect the hotbar for whatever reason. I can't tell if this happens without a color module, as most UI elements are the same color (grey).
Steps to reproduce:
1: Shoot a Phaser.
2: Put any color on a Plasma Shotgun, then hold it. Red is very noticeable, good for testing.
Crash report paste (if any) on [gist](gist.github.com):
N/A
MatterOverdrive version:
0.4.1
Minecraft version:
1.7.10

Screenshots:

Phaser Held
![2016-06-14_11 12 43](https://cloud.githubusercontent.com/assets/6917535/16056735/bc65b3da-322b-11e6-9297-64f561754e82.png)
Phaser Fire
![2016-06-14_11 12 46](https://cloud.githubusercontent.com/assets/6917535/16056736/bc692164-322b-11e6-8092-99d37f07b65f.png)
UI Normal
![2016-06-14_11 12 33](https://cloud.githubusercontent.com/assets/6917535/16056734/bc64a986-322b-11e6-9fdd-1213da567a51.png)
UI Shotgun
![2016-06-14_11 12 28](https://cloud.githubusercontent.com/assets/6917535/16056737/bc66cb26-322b-11e6-8ddb-1c350344e494.png)

**Comment by shadowfacts** [comment]
Unable to reproduce on 1.10.2

**Comment by Zsashas** [comment]
But this issue isn't for 1.10.1, it's for 1.7.10.

**Comment by shadowfacts** [comment]
I know, but 1.7.10 isn't supported anymore. I would have left this issue open if I could have reproduced it on 1.10.2
