### ISSUE TITLE
Decoration Tab Misnamed

### ISSUE THREAD

**Issue by mandm635** [simeonradivoev/MatterOverdrive#547]
Brief explanation of problem:
     The creative tab decoration is misnamed.
![8018f6bfd17cfa7667399311f0003610](https://cloud.githubusercontent.com/assets/13128898/16065599/25a9263a-3261-11e6-885c-0afbfb69fa6b.png)

MatterOverdrive version:
     0.4.1

Minecraft version:
     1.7.10

**Comment by shadowfacts** [comment]
ed21073f1f90eabd80fc822dfb53ccbb4da0ec66
