### ISSUE TITLE
Fire upgrade useless with Phaser

### ISSUE THREAD

**Issue by Zsashas** [simeonradivoev/MatterOverdrive#548]
Brief explanation of problem:
Incendiary barrel has no effect with the Phaser.
Steps to reproduce:
Install the incendiary barrel on the phaser, fire it at anything.
Crash report paste (if any) on [gist](gist.github.com):

MatterOverdrive version:
0.4.1
Minecraft version:
1.7.10

**Comment by shadowfacts** [comment]
Incendiary Barrel isn't applied on the stun setting but is on other settings. Working as intended.
