### ISSUE TITLE
[1.9.4] Missing Textures

### ISSUE THREAD

**Issue by Alaberti** [simeonradivoev/MatterOverdrive#555]
Brief explanation of problem:
Attached are screenshots of all the missing textures I found. Missing is the Tritanium Axe mentioned in a previous issue.
![2016-06-23_10 22 35](https://cloud.githubusercontent.com/assets/10929796/16307024/cd1b0c9e-392d-11e6-9123-3b4932ae0c5e.png)
![2016-06-23_10 22 37](https://cloud.githubusercontent.com/assets/10929796/16307026/cd1a900c-392d-11e6-8ac7-8134ccd65b60.png)
![2016-06-23_10 22 38](https://cloud.githubusercontent.com/assets/10929796/16307021/cd17dd08-392d-11e6-8fcc-97c56e9a6688.png)
![2016-06-23_10 22 40](https://cloud.githubusercontent.com/assets/10929796/16307022/cd187d80-392d-11e6-9435-521caa816efc.png)
![2016-06-23_10 22 46](https://cloud.githubusercontent.com/assets/10929796/16307023/cd18c9a2-392d-11e6-8e43-7ee85f4f1e9d.png)
![2016-06-23_10 22 48](https://cloud.githubusercontent.com/assets/10929796/16307025/cd1c6a9e-392d-11e6-96cb-f3478e2a6465.png)
![2016-06-23_10 22 49](https://cloud.githubusercontent.com/assets/10929796/16307028/cd23391e-392d-11e6-9b55-af8a639fc195.png)
![2016-06-23_10 22 50](https://cloud.githubusercontent.com/assets/10929796/16307027/cd20aa32-392d-11e6-8888-12e9dbc0953c.png)
![2016-06-23_10 22 59](https://cloud.githubusercontent.com/assets/10929796/16307030/cd25ec18-392d-11e6-8aa5-23073fd08a5a.png)
![2016-06-23_10 23 01](https://cloud.githubusercontent.com/assets/10929796/16307029/cd24764e-392d-11e6-97d1-3bddcb0b4c04.png)
![2016-06-23_10 23 02](https://cloud.githubusercontent.com/assets/10929796/16307032/cd2742c0-392d-11e6-8f32-23ff516aaaed.png)
![2016-06-23_10 23 03](https://cloud.githubusercontent.com/assets/10929796/16307031/cd266562-392d-11e6-95c0-3cf2a5d433d4.png)

Steps to reproduce:
N/A

Crash report paste (if any) on [gist](gist.github.com):
N/A

MatterOverdrive version:
MatterOverdrive-1.9.4-0.4.4-build-55

Minecraft version:
1.9.4

**Comment by simeonradivoev** [comment]
1.9.4 is in a dev.
