### ISSUE TITLE
Server crash upon entering Twilight Forest

### ISSUE THREAD

**Issue by KajesLorian** [simeonradivoev/MatterOverdrive#558]
Brief explanation of problem: Crash when entering Twilight Forest dimension.

Steps to reproduce: Enter Twilight Forest portal. Once dimension loads server crashes. If I disable spawn-monsters in the server options it stops the crash. If I remove MO it stops the crash. I have set the following in the MO config, but still causes crash:
       
        # The max amount of Rogue Android that can spawn in a given chunk
        I:max_android_per_chunk=0

        # The spawn change of the Rogue Android [range: 0 ~ 100, default: 15]
        I:spawn_chance=0

Crash report: https://gist.github.com/KajesLorian/3130db65352bee47cb7d9ccf8bb98cc3

MatterOverdrive version: 0.4.1

Minecraft version: 1.7.10

**Comment by shadowfacts** [comment]
No longer applicable as Twilight Forest has not been updated to MC 1.10.2.
