### ISSUE TITLE
EnderIO SAG Mill creates infinite Tritanium

### ISSUE THREAD

**Issue by forrester-marc** [simeonradivoev/MatterOverdrive#559]
Problem:
Grinding a Tritanium Plate in the Ender IO SAG Mill creates three Tritanium dust instead of two.

Steps to Reproduce:
Install Ender IO
Make two Tritanium plates
Grind plates in SAG Mill
Cook dust
Make three Tritanium plates
Profit!

MatterOverdrive version:
0.4.1
Minecraft version:
1.7.10 Forge 10.13.4.1614

Note: If this SAG Mill recipe is being added by Matter Overdrive, it's doing so in a way that overrides SAGMillRecipes_User.xml, which is not ideal for server admins.

**Comment by Ganjalf-Amsterdoom** [comment]
I'm confirming this, I've tried to write a custom sagmill recipe but it get overwritten somewhere and in the enderio core file there isn't anything about tritanium.
As a workaround I'm making tritanium plates require 3 ingots via minetweaker. A necessary evil until a 1.7.10 version of MO(or enderio) fix is out, my play mates are pissed, but hey, necessary evil. ]:D

**Comment by ktole1999** [comment]
i am using MatterOverdrive-1.7.10-0.4.0.jar and it takes  3 to make a plate and then grind down to 3 dust.

**Comment by Ganjalf-Amsterdoom** [comment]
Thank you for pointing that out, but I think I cannot downgrade so I just added a minetweaker workaround.

**Comment by forrester-marc** [comment]
If tweaking the costs is making Tritanium availability an issue, the Extra Utilities QED works as an ore tripler.  Sounds like the two-cost plates might be a temporary typo in any case.

Regarding the compatibility issue, can we request that MO injects its recipes into the config files for other mods rather than modifying them directly?  This would make everything much more visible to server admins, and allow them to make changes easily.

**Comment by forrester-marc** [comment]
[Oops]

If tweaking the costs is making Tritanium availability an issue, the Extra Utilities QED works as an ore tripler.  Sounds like the two-cost plates might be a temporary typo in any case.

Regarding the compatibility issue, can we request that MO injects its recipes into the config files for other mods rather than modifying them directly?  This would make everything much more visible to server admins, and allow them to make changes easily.

**Comment by shadowfacts** [comment]
207d46598a1368caa0d76fd3521cd6c9ad3e8922
