### ISSUE TITLE
Android Status breaks Zelda Sword Skills

### ISSUE THREAD

**Issue by Zsashas** [simeonradivoev/MatterOverdrive#560]
Brief explanation of problem:
The sword skills almost all use hunger to perform, but Androids don't have hunger, which makes the skills completely unavailable except the basic targeting.
Steps to reproduce:
Become an Android, use some Skill Orbs, try to use them on any target.
Crash report paste (if any) on [gist](gist.github.com):

MatterOverdrive version:
0.4.1
Minecraft version:
1.7.10

**Comment by Zsashas** [comment]
Would probably require some sort of compatibility module to allow the skills to draw from the energy supply of the player instead of hunger.

**Comment by shadowfacts** [comment]
No longer applicable as Zelda Sword Skills has not been updated to Minecraft 1.10.2

**Comment by Zsashas** [comment]
Well, this isn't FOR 1.10.2.

**Comment by shadowfacts** [comment]
I'm updating it
