### ISSUE TITLE
cant create/load world

### ISSUE THREAD

**Issue by AlienXtream** [simeonradivoev/MatterOverdrive#562]
Brief explanation of problem: cant load/create worlds using 0.4.1 version of the mod "state engine" error or something. loads wine in 0.4.0.

MatterOverdrive version: 0.4.1

Minecraft version:1.7.10

**Comment by shadowfacts** [comment]
1. You didn't post the log.
2. 1.7.10 isn't supported any more

**Comment by AlienXtream** [comment]
1. there was no log to be found, i searched and nothing i could see in my files was applicable.
2. fair enough :P
