### ISSUE TITLE
Exploration crash [Beta Bug]

### ISSUE THREAD

**Issue by estradus** [simeonradivoev/MatterOverdrive#563]
Brief explanation of problem:
World crashed while exploring. What, exactly, it was that caused the crash is not in evidence as it was not visible yet. It might have been a ship generating? 

Steps to reproduce:
Just happened while exploring. Head out there and if you roll snake eyes, you'll get a crash?
I have a slight suspicion that I was reentering an area I had already explored and it was caused by the interaction between a gravitational anomaly and the area once occupied by a variety of stone from a I had cut, but I have no idea if that would cause a problem before the cut blocks revert to air.

Crash report paste (if any) on [gist](gist.github.com):
https://gist.github.com/estradus/10a88746c81b1673009707b0dae346eb

MatterOverdrive version:
0.4.4, build 55

Minecraft version:
1.9.4

**Comment by shadowfacts** [comment]
f97068e0d3d018293ed806b3cb1e9c04d48e17f9
