### ISSUE TITLE
[1.7.10] Crash with Fastcraft (also without) on going in an area with a fusion reactor controller

### ISSUE THREAD

**Issue by b0bst3r** [simeonradivoev/MatterOverdrive#571]
MatterOverdrive-1.7.10-0.4.1-build-56
Forge 1614

Removing fastcraft fixed it for 1 player but the other 2 still crashed when the fusion reactor controller came into view.

With Fastcraft - http://pastebin.com/HmEDZcTL & https://paste.ee/p/U2UlI

Without Fastcraft - http://pastebin.com/fxuFTKzy

**Comment by shadowfacts** [comment]
1. The without FastCraft crash is completely unrelated, turn your view distance down.
2. Carpenter's Blocks is trying to use the Fusion Reactor Controller as a cover, which should not be allowed.
3. 1.7.10 is no longer supported.

**Comment by Sharidan** [comment]
Already tried reducing viewdistance. What would be the recomended lower viewdistance to avoid this issue?

**Comment by Sharidan** [comment]
Reducing viewdistance does not resolve the issue.

Interaction between Matter Overdrive and Carpenter's Blocks Garage Doors is causing the issue. Bad code handling and no error trapping, possibly either end or both ends.

Stopping issue support on a mod that is still heavily used is imho a lousy choice. That's no way to support the many communities fighting these issues.

**Comment by shadowfacts** [comment]
If reducing the view distance doesn't help, I'm sorry there's nothing I can do.

1. "many communities" are living in the past. 1.7 was released 3 years ago, catch up with the times.
2. I'm currently working on MO for 1.10.2 which has massive internal changes, it is impossible to support both versions at the same time. 1.7 being older, it is being dropped.

**Comment by Sharidan** [comment]
I would love to "catch up with the times", if there were any stable 1.10 mods/packs out, but sadly there arnt really any packs out yet that I can offer up to my comminuty. Thanks for the face-slap though :)
