### ISSUE TITLE
1.7.10 Ingots are in OreDictionary, recipes are not bound by OreDictionary.

### ISSUE THREAD

**Issue by MaDmaxwell311** [simeonradivoev/MatterOverdrive#573]
Hello, I was playing on the server I develop on today and noticed this "bug/oversight" Tritium Ingots are OreDictionaied, yet the recipes are not bound to the OreDictionary, only the MO version.  I believe that this is an oversight on MO's part, not other mods part, I could be wrong. I found this "oversight/bug", whatever it should be called, when processing the Tritanium Ore with RotaryCraft and Gregtech 5 and I got a Gregtech 5 Tritanium Ingot, ( OreDictionary name: ingotTritanium ). Both the Gregtech 5 ingot and MO ingot have the same OreDictionary name. The Gregtech 5 ingot version cannot be used at all for anything MO. I also tested with a MFR unifier and converted the GT5 version to MO version, and I got the MO version out when I specified it. 

MO version: 0.4.1
Rest of mods: https://www.atlauncher.com/pack/DigitalReality

**Comment by shadowfacts** [comment]
Will be fixed in MO for 1.10.2

**Comment by MaDmaxwell311** [comment]
UPDATE: After further testing, it seems that all items/ore, Dilithium, Tritanium, ect. are OreDictionaried, but recipes using them are not.

**Comment by 6210classick** [comment]
1.7.10 is no longer supported so don't bother

**Comment by shadowfacts** [comment]
@6210classick Yes, I said "Will be fixed in MO for 1.10.2", you don't need to stalk the issue tracker commenting "don't bother".
