### ISSUE TITLE
Game crashes during loading

### ISSUE THREAD

**Issue by ThomasHere123** [simeonradivoev/MatterOverdrive#574]
Minecraft Version: 1.7.10
Mod version(filename): MatterOverDrive-1.7.10-0.4.1-build-15.jar
Crashfile included.
[crash-2016-08-15_19.10.37-client.txt](https://github.com/simeonradivoev/MatterOverdrive/files/418440/crash-2016-08-15_19.10.37-client.txt)

**Comment by shadowfacts** [comment]
1. Java 8 is required.
2. 1.7.10 is no longer supported.
