### ISSUE TITLE
is this normal? :O

### ISSUE THREAD

**Issue by lightning02** [simeonradivoev/MatterOverdrive#575]
http://pastebin.com/rX2Uivn5
I noticed this in the logs, should I worry about it?

**Comment by shadowfacts** [comment]
@simeonradivoev I believe this is a problem with the JSON on your website, not the mod itself.

**Comment by Oatmas64134** [comment]
Judging by the second line of the logs, there is improperly formatted JSON at line 1 column 12 of the website, which then caused the string of errors afterwards. This is something only people with access to the website can fix.

**Comment by shadowfacts** [comment]
This has been fixed.
