### ISSUE TITLE
1.7.10 Omni Tool have some problem mining obsidian

### ISSUE THREAD

**Issue by lightning02** [simeonradivoev/MatterOverdrive#576]
When you are tryng to mine obsidian with omni tool, even on client side it doesn't break the block and restart mining the same block, it need 5-6 or even more attempts to mine a block of obsidian with the omni tool

**Comment by 6210classick** [comment]
1.7.10 is no longer supported so don't bother

**Comment by lightning02** [comment]
it was a problem that was occurring since when I tryed the mod the first time (december 2015)

**Comment by shadowfacts** [comment]
This will be fixed if the problem persists on 1.10.2
