### ISSUE TITLE
Game Crash after placing Gravitational Anomaly

### ISSUE THREAD

**Issue by Oatmas64134** [simeonradivoev/MatterOverdrive#578]
Crash Report: http://pastebin.com/Aud1M6bZ
If you need the logs, reply.
After placing my gravitational anomaly at the centre of my Fusion Reactor, it started to produce energy, then my game froze, and crashed.
Steps to Reproduce:
Mod version: 0.4.1
MC Version: 1.7.10
Build reactor first, then place anomaly.

**Comment by shadowfacts** [comment]
1.7.10 is no longer supported, and this has been fixed for 1.9.4

**Comment by Oatmas64134** [comment]
Ok, thanks.

**Comment by simeonradivoev** [comment]
https://mo.simeonradivoev.com/builds/
