### ISSUE TITLE
1.7.10 accessing malware URL simeon.co.vu

### ISSUE THREAD

**Issue by NitroxydeX** [simeonradivoev/MatterOverdrive#581]
I don't know if you're still doing something on the 1.7.10-branch and I just noticed this because a user came to me with a problem in BTP modpack using Traincraft. BTP uses 0.4.1 build-56 and it seems that your mod tries to access to simeon.co.vu (maybe an old url from you?). My Malwarebytes is blocking access to the URL and it's IP behind it. If you don't own the domain anymore push a build where you remove all stuff that's pointing to the URL.

**Comment by shadowfacts** [comment]
https://minecraft.curseforge.com/projects/matter-overdrive/files/2330925 (currently pending approval by CurseForge)
