### ISSUE TITLE
Android high jump

### ISSUE THREAD

**Issue by Fortist** [simeonradivoev/MatterOverdrive#583]
It seems I can high jump regardless of sneaking. 4.2 version.

**Comment by m0nkm0nk** [comment]
Ye this is very annoying. Having the same problem. Development is holded so I dont expect a fix..

**Comment by Muirrum** [comment]
Well, I wouldn't say Development is halted. We are all working hard to fix bugs, while at the same time trying to get a 1.10 version production-ready, and juggling real-life stuff.

**Comment by m0nkm0nk** [comment]
I'm quite sure i saw Simon writing somewhere it was halted. Sorry for telling false information hehe.
Or maybe it was for the 1.7.10 version which im referring to.

**Comment by Muirrum** [comment]
Simeon did say that he was not going to be working on it anymore, so now
Shadowfacts and I are working on it.

EDIT: Removed unnecessary content

**Comment by m0nkm0nk** [comment]
Well thats great to hear! Are you guys gonna do some 1.7.10 patching too or mainly newer MC builds?

**Comment by shadowfacts** [comment]
No, 1.7.10 is no longer being developed or supported.

**Comment by jtrent238** [comment]
The last commit to the 1.7.10 version was 3 months ago, (Sep 19, 2016)

> [commit bfe5586e212b651167d5752488fb64736361d775](https://github.com/simeonradivoev/MatterOverdrive/commit/bfe5586e212b651167d5752488fb64736361d775)

**Comment by shadowfacts** [comment]
And it was something completely inconsequential. 1.7.10 is no longer being developed or supported in any meaningful way.

**Comment by m0nkm0nk** [comment]
I get it guys. Its too bad cause its really the only noticeable android issue in 1.7.10 :(
Thanks anyway!

**Comment by Muirrum** [comment]
Closing due to unsupported version.
