### ISSUE TITLE
Why this project has not been updated yet?

### ISSUE THREAD

**Issue by SourcePowered** [simeonradivoev/MatterOverdrive#584]
We these players can't wait!
Can you tell us about the release date of 1.10.2?

**Comment by simeonradivoev** [comment]
I've stopped working on MO. @shadowfacts is the only one working on it now.

**Comment by shadowfacts** [comment]
I'm working on it on and off, I have other projects and a life outside of modding. Matter Overdrive for 1.10.2 will be ready when it's ready.

[ETA](https://www.youtube.com/watch?v=dQw4w9WgXcQ)
