### ISSUE TITLE
not sure if bug/mod interaction, or just derp

### ISSUE THREAD

**Issue by plaguewolf** [simeonradivoev/MatterOverdrive#587]
so i'll preface by saying my kitchen sink pack, has started to include the garage. and the attic. and the basement. and your neighbors stuff too. going strong at 192 mods installed. so mod interaction derps are a thing, like big time, and im still working through it all, but as of now, things are more or less stable.

so i added in MO, cause things look pretty neat, and had a few questions, but thats for after my bug concern.

loading MC is fine, get to main menu, create new world, worldgen goes by without errors, then;

`[12:45:50] [pool-3-thread-1/INFO]: Starting Matter Recipe Calculation !`
`[12:45:50] [pool-3-thread-1/INFO]: Matter Recipe Calculation Started for 47453 recipes at pass 1, with 202 matter entries`

wheww... that could take a while, and im assuming its all multi-threaded and stuff, cause my amd FX9370 8core OC'd @ 4.8Ghz has load shoot up to 50-60%

but thats not really too concerning, i'd assume the recipe profiler would just run, and then things will be fine. except gregtech.

both gregtech 6 and gregtech 5 unofficial do this.

MO recipe calc seems to loop on gregtechs meta-items/blocks. so log spam is suddenly from ~100k lines to over a million in a few seconds.

gunna test this with just gregtech, and MO soon, to see if thats really whats going on.

also, Mo and galacticraft, whats that like? MO has space travel stuff?

EDIT: well thats disapointing, gregtech/IC2 + MO in test instnace, took <100millis to do matter calc

**Comment by Muirrum** [comment]
Well, 100msec isn't really that bad, compared to my kitchen sink pack, currently going at over 350 mods, and that takes around 3 seconds to run the matter recipe calculations.
