### ISSUE TITLE
Visual bug with certain shaders

### ISSUE THREAD

**Issue by Adarcer** [simeonradivoev/MatterOverdrive#588]
Just a heads up if you use the phaser rifle with certain shaders you get a box in middle of screen adding the scope in does not fix this, this box dissapears for the second your firing the rifle . the shaders i have noticed this on are Cartoon shaders, Chocapic13 v3 low, Rudoplays, cuda shaders v4 pr1 and pr 4, docteur dreads v0.1,  high performance shader, plunder pixels, Tr3clipes ulitimate shaders default-ultra, waveing shader pack, paolos laggless shaders v03 rc 3 and 7 

seus shaders v10 rc7 is the worst example i have found it leaves a white box in center of screen,

silder's enhanced default v1.0.0 is not effected by this

**Comment by Muirrum** [comment]
What Mod Version are you using?
What MC Version are you using?

**Comment by shadowfacts** [comment]
Closing due to lack of response.
