### ISSUE TITLE
Omni Tool Mining Speed Issues

### ISSUE THREAD

**Issue by Shahelion** [simeonradivoev/MatterOverdrive#590]
If an Omni Tool is digging a type of block too fast, it takes multiple attempts to break each block. For example, endstone or netherrack. (does the Dilithium whatever upgrade increase mining speed?)

**Comment by Muirrum** [comment]
What mod version are you using?
What MC Version are you using?

**Comment by Shahelion** [comment]
0.4.1 Mod version
1.7.10 MC version

It also happens with Obsidian, which breaks any ideas I had on why it was happening...works fine on most ores, wood blocks, and grass & dirt.

I know you guys have moved on from 1.7.10, but what if it's still an issue in later versions and just no one has found it yet/bothered to report it?

Alternately, there might be an explanation for why it's doing this, and may or may not be fixable on the user's end.

Sorry, I'm just tired of reporting bugs, being told the version is unsupported, and it being left at that. Part of fixing problems is knowing why there's a problem in the first place.

**Comment by Muirrum** [comment]
I'll look at the branch comparisons for the OmniTool files tomorrow. Right now I don't have the energy to look.
G'night

**Comment by Muirrum** [comment]
Unfortunately, 1.7.10 is no longer supported. Please consider updating.

Closing due to unsupported version.
