### ISSUE TITLE
Crash upon start

### ISSUE THREAD

**Issue by Sasszem** [simeonradivoev/MatterOverdrive#593]
I've installed MO to Minecraft 1.7.10 with forge 10.13.4.1614, Asielib 0.4.5, but crashes the game with `cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: pl/asie/lib/block/BlockBase`
Full crash report: http://pastebin.com/wrMzE0Ld

**Comment by shadowfacts** [comment]
1.7.10 is no longer supported.
