### ISSUE TITLE
Spaceship!

### ISSUE THREAD

**Issue by GreninjaGuy** [simeonradivoev/MatterOverdrive#595]
Hi! I don't know if your mod has spaceships or not, but since it is based off star trek, I thought I should mention. And sorry if a million people have already spoken about this, but I didn't see it. If you did decide to add ships, you could make it so you build your ships out of bricks, then placed a warp engine inside with all the other stuff you'd need, and you could fly your ship! Like in real time, not teleporting like some mods. (_cough_cough_warpdrive_cough_cough_. Lol just kidding around so don't take offense warpdrive authors! I love your mod!) Now you may say, "Well, there are already some spaceship mods out there, even for moving in real time. Use one of those!" But then I say, "Not for 1.7.10!"

So, ya, I hope you guys respond! Even without spaceships, still looks like best star trek mod out there! :P

**Comment by Muirrum** [comment]
Unfortunately, 1.7.10 is not supported.

**Comment by GreninjaGuy** [comment]
Oh. :(

**Comment by shadowfacts** [comment]
Having flyable structures is ridiculously complicated to make inside of Minecraft's engine and is far out of the scope of this project.

**Comment by Divineaspect** [comment]
I suggest @GreninjaGuy add davinci's vessels to make "shuttles"

**Comment by jtrent238** [comment]
Oh that explains why i cant spawn a ship. :laughing: lol
