### ISSUE TITLE
crash after using teleport

### ISSUE THREAD

**Issue by KiraLinux** [simeonradivoev/MatterOverdrive#596]
when teleported to block tar happens crash
This block from tar mod Magneticraft
[crash-2016-11-02_13.15.15-client.txt](https://github.com/simeonradivoev/MatterOverdrive/files/566269/crash-2016-11-02_13.15.15-client.txt)

**Comment by Muirrum** [comment]
MC Version 1.7.10 is no longer supported, please consider upgrading.

**Comment by Muirrum** [comment]
Closed due to unsupported version.
