### ISSUE TITLE
Fatal Error upon right-clicking blocks

### ISSUE THREAD

**Issue by Gideonseymour** [simeonradivoev/MatterOverdrive#6]
This happens whenever I right-click any of the blocks. I'm assuming it's another Java 1.8 thing? http://paste.feed-the-beast.com/view/418e8e1e

It doesn't crash the game, it only exits the world.

**Comment by simeonradivoev** [comment]
Yep, it's a function that combines the upgrade stats in 1.8 :D, I'll have to implement my own.
