### ISSUE TITLE
Entity spamming for Gravitational Anomaly

### ISSUE THREAD

**Issue by bagomot** [simeonradivoev/MatterOverdrive#600]
The gravity anomaly spamming entities during absorption blocks. On my server, a gravitational anomaly spawn 39,000 entities in the same block. If to give this item the players, the end of the world in the form the burnt server hardware.
Server: Thermos-1.7.10-1492-57
MatterOverdrive: 1.7.10-0.4.1

Small log for example:
matteroverdrive.tile.TileEntityGravitationalAnomaly.onServerTick() 16.33%
matteroverdrive.tile.TileEntityGravitationalAnomaly.manageEntityGravitation() 14.5% 8700ms
matteroverdrive.tile.TileEntityGravitationalAnomaly.getAcceleration() 7.33%
matteroverdrive.tile.TileEntityGravitationalAnomaly.getRealMass() 7.33%

[Log entity spamming](http://pastebin.com/xudNyLMC)

**Comment by Muirrum** [comment]
1.7.10 is no longer supported. Please upgrade to a newer version.
