### ISSUE TITLE
Limb Overclocking FOV effect

### ISSUE THREAD

**Issue by Ahlforn** [simeonradivoev/MatterOverdrive#601]
Is there any way of turning off/negating the speed potion effect on the field of view that you get from the Limb Overclocking ability? Some of my friends say they don't notice it but it's driving me **crazy**. I would really like the space-time stabilizer ability but this effect is ruining it for me.

**Comment by Divineaspect** [comment]
https://minecraft.curseforge.com/projects/nofov?gameCategorySlug=mc-mods&projectID=227965

In the mean  time.

**Comment by Muirrum** [comment]
@Ahlforn Do you mean as a config setting, or as a hardwired setting that cannot be changed except by asking us to push a change?

**Comment by shadowfacts** [comment]
This isn't possible from MO's end, the FOV change is part of Vanilla.
