### ISSUE TITLE
[1.7.10] Game crashing due to memory overload when shooting multiple guns at a time, possibly a Mod Conflict

### ISSUE THREAD

**Issue by Famous5000** [simeonradivoev/MatterOverdrive#604]
So I have a bad feeling that this can be very easily replicated by just spamming a whole bunch of weapons in a row. **Because that's how my computer crashed.**

I can't really provide logs. They don't display anything about Matter Overdrive being silly like this, but I definately know it's a bug that needs to be fixed. Yes, from here on out I'll be more carefull, but it's still a bug that can kill people's interest in the mod.

Let me know if you cannot replicate this, then I'll give my modlist and logs [doubt it'll help]

**Comment by Muirrum** [comment]
We can still use the logs, can you hastebin them?

**Comment by Famous5000** [comment]
One problem: When I do the shooting multiple weapons, it doesn't generate any logs. I checked. I'll hop on a singleplayer world for testing [Expecting it to go corrupt] and am going to start throwing my hotbar crazy by filling it up with weapons then going ham. Once it crashes, I'll see if it generates a report.

I'll also say when I start shooting.

Edit: Removed unnecessary content. Silly email replies...

**Comment by Famous5000** [comment]
Ok. Singleplayer testing: Nothing happens. Fired everything from this pack into air which is what caused the crash last time.

In the case of you needing logs for the SINGLEPLAYER world:
![image](https://cloud.githubusercontent.com/assets/9399230/21338977/3c78a7f8-c638-11e6-8d99-21c01a7b1ddd.png)


Now to Multiplayer.
*sigh* Here we go again.

I know it crashed while I was in Multiplayer while doing this. But I don't have a single crash report stating what went wrong where!!! Very confusing. I have a small suspicion that your mod's lasers are incompatible with Draconic Evolution or Extra Utilities 2. I'm going to test and see if that is the case, because those are the literal only mods that could have been active during a Boss Fight against some people in the server.

**Comment by Famous5000** [comment]
YES! I HAVE DONE IT! Looks like Draconic Evolution is at fault here, as soon as the weather changers activate while a weapon or 2 is firing, that's when the game crashes.

The time I started firing is after I gave myself 64 Emerald to fuel the Weather Changers [I expected it to take longer than it did.]
Here's the logs. I am not sure how it'll help, but Draconic Evolution does have a problem with this mod.

![image](https://cloud.githubusercontent.com/assets/9399230/21352615/88aeae64-c67f-11e6-870c-d1b0f9e25716.png)

**Comment by Famous5000** [comment]
More info:

When I remove the rain detector and the Weather Changer, the problem still continues. Heading over to Multiplayer at this point, where my ship also had 3 Sound Mufflers. Going to nuke those and see if the problem still exists.

If it does, then I have no clue what's going on. The crash report is the same as it was before.

**Comment by Famous5000** [comment]
NOPE. Same exact error, but it seems that using the RMB ability on weapons seems to cause the game to stop itself.

The game runs fine if I try to fire one weapon, but multiple at a time WITH their right-mouse-button ability? Nothing. This most likely is not a mod conflict at this point.

**Comment by Famous5000** [comment]
I'll try some more singleplayer testing.
Upon entering the lag spiked world, everything is fine other than the initial loading spike, which I expected.
Using the weapons just with their left-click abilities, the game doesn't crash WITH the automated weather controllers cycling the weather like crazy. When I have the Auto Weather shut off [No longer cycling], firing all weapons at once doesn't crash the game, even with the right-click ability. This is very curious for me.

On multiplayer:

With all of the mods that I have active, none of them seem to crash me IF I only use the left mouse button abilities.

I'll send you my mods if you want to do some testing yourself.

**Comment by Muirrum** [comment]
1.7.10 is not supported.
@shadowfacts please close.

**Comment by shadowfacts** [comment]
This needs confirmation in 1.10.2.

**Comment by Muirrum** [comment]
We also need a modlist to replicate @Famous5000

**Comment by Muirrum** [comment]
Closing due to unresponsive author and lack of modlist to replicate.
