### ISSUE TITLE
Starmap Whitescreen

### ISSUE THREAD

**Issue by rayn337** [simeonradivoev/MatterOverdrive#607]
Whenever i open the starmap, I get a white screen where the map should be. I can still see the quadrant buttons and system buttons, but apart from that its all white.

**Comment by Muirrum** [comment]
What MC version are you using, and what mod version are you using?

**Comment by rayn337** [comment]
MC Version 1.7.10 
Matter Overdrive Version 1.7.10-0.4.2
Added Matter Overdrive to the FTB Infinity Evolved (version 2.6.0) modpack through the Curse Launcher.

**Comment by Muirrum** [comment]
1.7.10 is no longer supported.

**Comment by rayn337** [comment]
Well thats a shame then since alot of modpacks run on 1.7.10

**Comment by Muirrum** [comment]
@rayn337 Well, I am trying to continue support over at Otmas/MatterOverdrive
