### ISSUE TITLE
Crashed ships and android houses aren't spawning

### ISSUE THREAD

**Issue by skyewolfe** [simeonradivoev/MatterOverdrive#611]
We have looked all over. but for some reason, Android houses, crashed ships or cargo ships are not spawning on the server. The ores, the mad scientists and the like are. I don't see any errors in the start up logs that will cause it, but just in case, I have included the start up log

https://www.dropbox.com/s/009w4dbnru4pebh/startup.log?dl=0

**Comment by Kiefy** [comment]
I came here looking for a solution to the same problem. on a test flat world, I get MO spawns every 100 meters, but in my actual ExtraBiomes world, I've seen nothing for thousands of miles..

but I fear I at least am out of luck, using the unsupported 1.7.10 build. :(

**Comment by Kiefy** [comment]
In my case, EBXL was the problem. Got rid of it and now all the things are spawning!

I like how rare they are too. it is truly exciting when you find one! :)

**Comment by Muirrum** [comment]
@skyewolfe 1.7.10 is no longer supported. Please consider upgrading to a newer version.

**Comment by Muirrum** [comment]
Closing due to unsupported version
