### ISSUE TITLE
Android Abilities don't work with Cauldron

### ISSUE THREAD

**Issue by Jacob345k** [simeonradivoev/MatterOverdrive#612]
I'm running a Cauldron server "KCauldron/1.7.10-1614.201" and whenever i try to use the plasma shield it says i have a 201h cooldown, and the ender teleporter is just orange. Haven't tested offensive side.

**Comment by jtrent238** [comment]
Version 1.7.10 is no longer supported, please upgrade to latest version.

**Comment by Muirrum** [comment]
Closing due to unsupported version.
