### ISSUE TITLE
Eclipse is not finding the constructor StackTitleElement(ItemStack)

### ISSUE THREAD

**Issue by IronworksProductions** [simeonradivoev/MatterOverdrive#613]
So I start working on the mod to get it to run and I find that all code errors stem from one constructor StackTitleElement which areas of the mod are trying to use an ItemStack type as an argument when it only takes a ByteBuf type. I am just wondering what you want this code to do and what to change to fix it because looking at eclipse literally all errors at this point of development in this mod stem from this constructor.

thanks,

--
NN

**Comment by IronworksProductions** [comment]
@shadowfacts can you take a look at this when you get the chance this was a class you created so your expertise would be appreciated in fixing what's broken.

**Comment by shadowfacts** [comment]
[Lombok](https://projectlombok.org/) is required.

**Comment by IronworksProductions** [comment]
I installed Lombok and the error is still there.

**Comment by shadowfacts** [comment]
How did you install it? Lombok not being present or setup correctly is the only thing that could cause that error. If the error is still occurring, you've setup Lombok wrong.

**Comment by IronworksProductions** [comment]
I executed lombok.jar then added Lombok.jar to buildpath then rebooted eclipse.

**Comment by shadowfacts** [comment]
¯\\\_(ツ)\_/¯

That should work fine. I don't have much experience with Eclipse so I can't really help you. All I know is that the [IDEA plugin](https://github.com/mplushnikov/lombok-intellij-plugin) for it works fine and lets it compile (after enabling annotation processing in the settings).
