### ISSUE TITLE
communication Relay broken, old fix doesn't work

### ISSUE THREAD

**Issue by chickenbones369** [simeonradivoev/MatterOverdrive#614]
When I place the communication relay block it immediately reverts to coils, after I rename it (properly, several times) in an anvil it immediately goes back to being a coil regardless of where it is placed. This results in the quest being unfinished.

**Comment by Muirrum** [comment]
What version, and can you send logs?

**Comment by chickenbones369** [comment]
MatterOverdrive-1.7.10-0.4.2

I can but there is no crash, what file would you like specifically? 

Even just a way to auto complete that particular quest would be fine with me.

**Comment by Muirrum** [comment]
Unfortunately, 1.7.10 is no longer supported. Please consider upgrading to a newer version.

**Comment by chickenbones369** [comment]
Cant really. is there a command to bypass the quest? If not thanks any way.

**Comment by Muirrum** [comment]
I don't believe so, but I can look.
UPDATE: Nope, doesn't look like it, Sorry.

**Comment by Muirrum** [comment]
Closing due to resolved issue.
