### ISSUE TITLE
Can't figure out how to get server class not to load client class

### ISSUE THREAD

**Issue by IronworksProductions** [simeonradivoev/MatterOverdrive#616]
Okay so i fixed the bounding box error and got it to run flawlessly on a client. Now my issue is servers. It still is trying to launch the localization class on the server which causes an immediate crash. I moved all the classes i could find that reference that class to the client proxy class and it still wants to load it as if the mod itself is written on this class not just the client version. I can push the code i have that works for client if you want to test it out and see if it works and let me know whats wrong on the server side. Just let me know what I should do. It seems to work flawlessly on clients right now.

--
NN

**Comment by Muirrum** [comment]
Oh, you fixed that error? That's good. Now my eclipse can load it without screaming at me.
Also yes, please do start a PR. My eclipse's voice is horrible in the mornings.

**Comment by IronworksProductions** [comment]
ok

**Comment by Muirrum** [comment]
Closing due to redundancy.
