### ISSUE TITLE
Discuss Updates Here.

### ISSUE THREAD

**Issue by OmegaRogue** [simeonradivoev/MatterOverdrive#617]
when are you updating this mod again?

**Comment by Muirrum** [comment]
Well, what version are you talking about?

**Comment by ETStareak** [comment]
@Dev-Osmium  
Any version。
I only want to know IF the mod is developing.
Ah，I'm a Chinese player，and I'm willing to introduce the mods to all the players.If you don't develop it，I will do other things.
It's very important to me.

**Comment by Muirrum** [comment]
@shadowfacts has all but quit the project, as of two days ago, I have taken over active development.

**Comment by ETStareak** [comment]
@Dev-Osmium  
That means the modder before you won't work to this mod any more?And now simeonradivoev has stopped his work too?
Thank you for your work.Would you develop to the 1.10.2MC or 1.11.2？I'will work on ，translating and writing introducation for Chinese players.
Good Luck!

**Comment by Muirrum** [comment]
I will continue development of 1.10.2

**Comment by ETStareak** [comment]
OK,thank you.
I'll revise the Chinese lang later.
And......do you know other ST mod for ships?[https://github.com/Cr0s/WarpDrive](url)
I think it's very great,and you can communicate with that modder.

**Comment by 63502** [comment]
Cool! I'm glad to see that someone decided to update MO. It's a really fun mod, what with becoming an android and all.

Do you have an approximate ETA for the 1.10.2 version, or will it just be ready when it's ready?

**Comment by Muirrum** [comment]
It will be ready when it is ready.
@simeonradivoev Ability to close PRs and Issues would be helpful.

**Comment by Muirrum** [comment]
@ETStarLight I really enjoy the WarpDrive mod, but I want to get a 1.10.2 version stable and production ready.

**Comment by ETStareak** [comment]
Oh，I only means you can spport each other ，and I think this will bring better ST system to minecraft.
I haven't see MO in the list of WD……and in minecraftfourm I saw the modder said he is working on 1.10.2version.

**Comment by Muirrum** [comment]
I still really want a 1.10 version before I start thinking about integrations.

**Comment by ETStareak** [comment]
Oh，I don't hope make integrations，but I think if we can use MO blocks on WD ships，it will be a good thing.

**Comment by Muirrum** [comment]
Oh, so you want that kind of integration.
Sure, that should be easy.

**Comment by b0bst3r** [comment]
[–]KingLemmingThermal Expansion Dev 1 point 23 minutes ago 

Cool!

Do me a favor and update your RF API please: https://github.com/CoFH/RedstoneFlux-API

Come 1.11, it's going to be a signed standalone jar. There are too many issues with people repacking it improperly.

:)
https://www.reddit.com/r/feedthebeast/comments/5yos6j/matter_overdrive_has_been_updated_to_1102/
