### ISSUE TITLE
Upgrades Requiring Items

### ISSUE THREAD

**Issue by Gr12zly** [simeonradivoev/MatterOverdrive#62]
Any upgrade requiring an item maintains the color red and will not allow me to receive the upgrade. I have made sure that both the item and the level req. are met.

**Comment by simeonradivoev** [comment]
Make sure you have the right amount of items. Some require more than one item. Some abilities require other to be unlocked first. Make sure you have unlocked all required abilities.

**Comment by Gr12zly** [comment]
I made sure, such as the high jump, it says it requires Limb Overclocking, of which I have the 3rd state, and a piston, of which I have, and 36 levels and I am at 38.

**Comment by mgillow** [comment]
I took me a while to work out how to get plasma shield - it says Requires [Nano Armor] but you must make sure you have the full x4 Nano Armor, not just one.+ the 2 force field emitters.

**Comment by Gr12zly** [comment]
ahhhhh, so it requires more than just one of the upgrades but 4, I understand now thank you.
