### ISSUE TITLE
[Suggestion] Change Log Command

### ISSUE THREAD

**Issue by jtrent238** [simeonradivoev/MatterOverdrive#621]
This should be added to matter overdrive.

![IMG](https://github.com/jtrent238/PopularMMOS-EpicProportions-Mod/raw/gh-pages/images/ss%20(2017-02-08%20at%2009.47.05).png?raw=true)

[https://github.com/jtrent238/Minecraft-Mod-Browser](https://github.com/jtrent238/Minecraft-Mod-Browser)

To see an example of this being used [Click Here](https://github.com/jtrent238/PopularMMOS-EpicProportions-Mod/wiki/Web-Browser).

To download the sample [Click Here](https://github.com/jtrent238/Minecraft-Mod-Browser/releases/download/1.0.0.0/Browser-Sample.jar).

I May make a pull request with this setup later

**Comment by shadowfacts** [comment]
No.

1. There are better ways of displaying a changelog.
2. The changelog is already available elsewhere.
