### ISSUE TITLE
Won't Load

### ISSUE THREAD

**Issue by LeeLR** [simeonradivoev/MatterOverdrive#622]
When I load the mod it says missing Tesla 1.2.0.38 or above.  I have Tesla 1.2.0.49 (latest stable release)
Its not recognizing Tesla for some reason.

**Comment by Muirrum** [comment]
Which version?

**Comment by LeeLR** [comment]
Latest version on curseforge

**Comment by Alaberti** [comment]
I can confirm, also having this issue. Below is the error from my logs with the mod-loading info:

http://pastebin.com/raw/w2JYwYJW

**Comment by Alaberti** [comment]
Got it to run with the exact version it's requesting (1.2.0.38) but looks like it only wants that version.
