### ISSUE TITLE
[1.10.2] [MO 0.5.0] Custom Main Menu/Resource Loader/Matter Overdrive Conflict

### ISSUE THREAD

**Issue by Alaberti** [simeonradivoev/MatterOverdrive#623]
I'm not really sure why, but after adding this mod my custom textures are no longer applied to the main menu.

After adding Matter Overdrive:<img width="960" alt="aeronauts_post_mo" src="https://cloud.githubusercontent.com/assets/10929796/23818340/b4804e2e-05bf-11e7-9cd5-3eb5a9f10f23.png">

Before adding Matter Overdrive:
![aeronauts_pre_mo](https://cloud.githubusercontent.com/assets/10929796/23818357/ddbf4fb0-05bf-11e7-92a7-0a0f0526179c.jpg)

Matter Overdrive: 0.5.0
Custom Main Menu: 2.0.2
Resource Loader: (1.9.4) 1.5.1
Forge: 2239
Journeymap: 5.4.6
Error: http://pastebin.com/raw/Lj4VVyAm

Edit 1: Edits for additional clarity.
Edit 2: Adds additional error logging, reported to CMM author as well.
Edit 3: Discovered Journeymap 5.4.6 was also a part of the error.

**Comment by shadowfacts** [comment]
I'm unable to reproduce this with the bare minimum mods necessary, and I don't see how this could be an MO bug.

**Comment by Alaberti** [comment]
I'll start pulling mods out of the pack until I have an answer for you.

**Comment by Alaberti** [comment]
I've updated the main issue with an error log (http://pastebin.com/raw/Lj4VVyAm) and some additional information and will post to the Custom Main Menu page. 

The error only happens with this mod, and the log states the images are failing to load - do you do anything unique with resource loading?

Edit: Or rendering?

**Comment by Alaberti** [comment]
I found an error in my testing, I had journeymap in a subfolder. Removed it and reran my tests with just the minimum mods again (for clarity, CMM,  Resource Loader, Forgelin, Matter Overdrive, Tesla). No issue. The moment I added Journeymap again, however, the issue returned. When I remove Matter Overdrive, no issue. Something between Journeymap and MO appears to be at play here.
