### ISSUE TITLE
[1.10.2] Can't launch client or server w/ MO installed.

### ISSUE THREAD

**Issue by AceologyGaming** [simeonradivoev/MatterOverdrive#625]
Server crash log: 
[crash-2017-03-11_11.49.12-server.txt](https://github.com/simeonradivoev/MatterOverdrive/files/835687/crash-2017-03-11_11.49.12-server.txt)

Client crash log
[crash-2017-03-11_10.56.34-client.txt](https://github.com/simeonradivoev/MatterOverdrive/files/835688/crash-2017-03-11_10.56.34-client.txt)

**Comment by shadowfacts** [comment]
The client crash you're experiencing is caused by Extra Utilities 2, try reporting it there.

**Comment by AceologyGaming** [comment]
But it doesn't crash when MO is not installed.
