### ISSUE TITLE
Conflict or non-recognizing 

### ISSUE THREAD

**Issue by Tyrantin** [simeonradivoev/MatterOverdrive#626]
OK I have downloaded all the required mods for MO. It is still asking for Tesla 1.2.0.38 or above! Currently I have Version 1.2.1.50 installed and it is still asking for 1.2.0.38 +. Assistance would be appretiated!

**Comment by shadowfacts** [comment]
Already fixed by 4813f5db51bfa0c9c486f6d0906341d66c17bf77.

A new version will be out soon.

**Comment by Tyrantin** [comment]
ETA?

Just wondering because I am Building a mod pack around MO and Advanced Rocketry.

**Comment by shadowfacts** [comment]
When it's ready

**Comment by Tyrantin** [comment]
ok thx
