### ISSUE TITLE
Tesla version discrepancy

### ISSUE THREAD

**Issue by Silvrus** [simeonradivoev/MatterOverdrive#627]
Forge 12.18.3.2239
Matter Overdrive 1.10.2-0.5.0

Game will not start with TESLA 1.2.1.41 or above, Matter Overdrive complains that it requires 1.2.0.38 or above but in fact only works with 1.2.0.38 through 1.2.1.40.

**Comment by shadowfacts** [comment]
Already fixed in 4813f5db51bfa0c9c486f6d0906341d66c17bf77.
