### ISSUE TITLE
Biobeds / charging stations

### ISSUE THREAD

**Issue by mgillow** [simeonradivoev/MatterOverdrive#63]
How about having a bio-bed for humanoids which you can heal you while you sleep (maybe add food / plants to give various different buffs for next morning) and a charging station (I'm thinking like the borg ones) for androids which will charge / repair you while sleeping when attached to power and matter.

**Comment by simeonradivoev** [comment]
Added in 7ef3dcb162e40b0d944d091cd4cc3806e988074d
