### ISSUE TITLE
[1.10.2][0.5.1][Minor] Texture Sizing Weirdness

### ISSUE THREAD

**Issue by Alaberti** [simeonradivoev/MatterOverdrive#630]
All the ranged weapon icons are tiny, but otherwise function/render correctly.

<img width="960" alt="mo_weirdness" src="https://cloud.githubusercontent.com/assets/10929796/23826430/86f8f08a-0661-11e7-9548-40bc6ec86732.png">

**Comment by shadowfacts** [comment]
Already fixed in 0587d277c5cccb4707b82dfe8300f686c1e6ae7c.
