### ISSUE TITLE
[1.10.2] The mod (Matter Overdrive 0.5.1) crashes with the crash log provided below

### ISSUE THREAD

**Issue by BadPunMaster** [simeonradivoev/MatterOverdrive#635]
https://paste.ubuntu.com/24164154
Link for the crash log

**Comment by Muirrum** [comment]
Just, whoa there. Try removing some of the mods, particularly any that reference any kind of "wcrbe remote"

**Comment by shadowfacts** [comment]
WR-CBE bug, the developer has been notified.

**Comment by Brycey92** [comment]
Okay, so I opened that issue above at https://github.com/TheCBProject/CodeChickenLib, and made 2 PRs, also above, which fix this issue in both 1.10.2 and 1.11.2, if it even happens in 1.11.2.

**Comment by Brycey92** [comment]
According to covers1624, the now-dev of WR-CBE on the PRs I opened on his repo, "Whilst this is a simple fix, i really don't support 1.10 or 1.11 anymore. As for the issue at hand, its really a matter overdrive issue, they shouldn't need vanilla's horrible texture atlas system and this wont stop other mods crashing and burning on this aswell.. I'm going to pull this, but my final word on the matter is its on matter overdrive's end."

This issue should be reopened, @shadowfacts @Dev-Osmium.
