### ISSUE TITLE
Omnitool crash, missing crosshair

### ISSUE THREAD

**Issue by LunarNocturnality** [simeonradivoev/MatterOverdrive#637]
Omnitool left click/mining beam crashes the game, both when aimed at a solid block or air.
Sniper scope weapon modification doesnt have crosshair.

**Comment by shadowfacts** [comment]
Post the crash report.

**Comment by LunarNocturnality** [comment]
http://pastebin.com/5pZDhb2j

**Comment by Muirrum** [comment]
I honestly don't see any issues in the files being referenced.
