### ISSUE TITLE
[Crash] Mod conflict with Extra Utilities 2

### ISSUE THREAD

**Issue by Dragnier** [simeonradivoev/MatterOverdrive#638]
Some kind of sprite renderer crash. I've seen this before between EU2 and Tinkers. Not sure if it is on your end or EU2 to be honest. If I need to repost this over there, let me know.

https://gist.github.com/Dragnier/73262bee228a27c6f5d8c84f9e71b466

**Comment by shadowfacts** [comment]
Duplicate of #631.
