### ISSUE TITLE
Scope not Zooming

### ISSUE THREAD

**Issue by Nomeka** [simeonradivoev/MatterOverdrive#650]
Hello. I'm currently using the AT Launcher, running the Revenge of the C Team pack on a lan instance using Hamachi.

First off, I love this mod and it's amazing and fantastic and stuff.

I'm having a problem where the scopes aren't zooming at all. I have one on my Phaser rifle, and one on my Ion Sniper, and holding right click just holds the rifle in front (as normal) and has me looking through the scope and stuff, but the perspective doesn't change. Just my looking speed. Is there something conflicting in the mods of the pack that make the zoom of the scope just not work? I was really hoping to cloak on over to a tower of a pre-rendered castle place, then snipe the mobs all night like some sort of Starcraft Ghost to fill up my Evilcraft blood extracter and stuff, but the Scope jsut refuses to do any zoom.

This is my first time posting to a place like this, and I made an account on this site thingie specifically to post this.

**Comment by shadowfacts** [comment]
1.7.10 is no longer supported

**Comment by Nomeka** [comment]
Oh, that sucks. It's the only pack that my friend has stuff she likes that MO is in. We usually prefer Resonant Rise, but the newest versions of it doesn't include Fastcraft which I basically need in order to not play Minecraft like a slideshow, and every attempt we've made to manually add MO to the pack ends up with her just crashing upon joining the world.

And no other packs I've looked into on the AT have both MO and Fastcraft or something akin, as well as the various normal mods we enjoy, like Tinkers, witchery, and the like. (I am greatly enjoying Evilcraft though).

Do you have any recommendations for a good modpack with a supported version of MO on it?

**Comment by shadowfacts** [comment]
I don't believe there are any 1.10.2 modpacks which include MO. It was only released very recently and is still very unstable.

**Comment by Nomeka** [comment]
That sucks. I really love MO so far, and other then the scope not zooming (Which it did in the Divergance pack) and not knowing how to finish the crashed spaceship "notify family": contract, I've not experienced any problems at all and it's been a complete joy.

What would your best estimate as to when 1.10.2 Modpacks start getting more stable and including all the fantastic mods? A few months, a year? 

And do you know of a good way for adding mods to modpacks that don't cause problems over Lan worlds? Because I doubt Resonant Rise will suddenly include mods like MO and Evilcraft where they didn't exist in any prior builds, and I would really love to be able to add them to such a pack, since my friend and I usually play that one.

**Comment by shadowfacts** [comment]
I have no idea, sorry.

If you include the same version of the mod on both clients, with the same config, it should work fine.

**Comment by Nomeka** [comment]
Yeah, that's what we did. Made sure it was the same one by sending her a copy of the one I downloaded and everything. It worked fine for me, but every time she tried to join, it'd crash. Ah well. Maybe I'm jsut doing something wrong.
