### ISSUE TITLE
Crash when trying to load game.

### ISSUE THREAD

**Issue by Lokii241** [simeonradivoev/MatterOverdrive#654]
When using the curse launcher to load a game with this mod, The game crashes saying there was a fatal exception: The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
"The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Matter Overdrive (mo)"

**Comment by shadowfacts** [comment]
Post the entire crash report.

**Comment by shadowfacts** [comment]
Closing because no response.
