### ISSUE TITLE
I dont know how to smelt tritanuim ore

### ISSUE THREAD

**Issue by TristanK13** [simeonradivoev/MatterOverdrive#659]
something i cant figure out is why i cant smelt tritanuim or in the furnace, i'm suck and i really need help on wath i gotta do

**Comment by Muirrum** [comment]
Which MC version are you talking about?

**Comment by TristanK13** [comment]
1.10.2

**Comment by TristanK13** [comment]
u there?

**Comment by TristanK13** [comment]
brb

**Comment by Muirrum** [comment]
This is not the place for IRC-esque conversations. 

https://mo.simeonradivoev.com
Try looking there.

**Comment by Muirrum** [comment]
@shadowfacts We don't need this issue any more.
