### ISSUE TITLE
Not sure what to make of this

### ISSUE THREAD

**Issue by Tyrantin** [simeonradivoev/MatterOverdrive#666]
[help.txt](https://github.com/simeonradivoev/MatterOverdrive/files/867402/help.txt)

**Comment by Tyrantin** [comment]
ughhh issue 666

**Comment by simeonradivoev** [comment]
![Image](https://media.giphy.com/media/lS74OiH1JYYak/giphy.gif)

**Comment by shadowfacts** [comment]
What's the issue you're experiencing?

**Comment by Tyrantin** [comment]
That is from what is going on in the server. Not really an issue but this one is.
[crash-2017-03-24_15.37.45-client.txt](https://github.com/simeonradivoev/MatterOverdrive/files/868996/crash-2017-03-24_15.37.45-client.txt)

I keep crashing out of the game. Not continually but often enough to make it annoying.

**Comment by shadowfacts** [comment]
Already fixed in c37e6cbfa7e2a126c20222a81f8f85f49ed7e5c6.
