### ISSUE TITLE
Crash when opening star map

### ISSUE THREAD

**Issue by ghost** [simeonradivoev/MatterOverdrive#669]
I crashed on 1.10.2 when opening star map

Report: http://pastebin.com/6pqvLbBW

**Comment by ghost** [comment]
Progress: I disabled NEI (Went into options and disabled it) and it worked, Please fix this bug, it only happens when NEI is enabled

**Comment by shadowfacts** [comment]
Of course it only happens when NEI is enabled, the crash is caused by NEI >.>
