### ISSUE TITLE
Android parts + titanium spine + guis render oddly/not at all

### ISSUE THREAD

**Issue by VexTheWanderer01** [simeonradivoev/MatterOverdrive#671]
![2017-03-27_08 55 55](https://cloud.githubusercontent.com/assets/26715644/24359889/50b948aa-12cb-11e7-84b1-5ad4714c93e3.png)
![2017-03-27_08 55 52](https://cloud.githubusercontent.com/assets/26715644/24359893/53340f34-12cb-11e7-8dd1-721b77785b40.png)

**Comment by Muirrum** [comment]
What version?
What mod version?
What other mods are you using?

**Comment by Muirrum** [comment]
@shadowfacts Please close this due to lack of response from issue author.
