### ISSUE TITLE
no recipe for tritanium[1.10.2]

### ISSUE THREAD

**Issue by Grizzord** [simeonradivoev/MatterOverdrive#672]
after looking around jei for quite sometime and the fourums it seems there is no recipe to get tritanium ore to tritanium ingots. im not sure why this is or if its even a bug. but i thought i would put it out there

**Comment by Tyrantin** [comment]
The ore spawns in the world upon generation. If you don't find any you probably have a mod that is overriding MO ore spawns.

**Comment by Grizzord** [comment]
The ore is spawning just fine. There is no way through JEI of changing the ore into ingots. unless the recipe is something different other than smelting.

**Comment by Muirrum** [comment]
@Grizzord I'll take a look.

**Comment by Muirrum** [comment]
Oh holy crap it's been a while, sorry mate.

**Comment by Muirrum** [comment]
Ok, so you need tritanium nuggets in the same recipe for a diamond block.
(so
nnn
nnn
nnn
where n is a tritanium nugget)
