### ISSUE TITLE
Full on Client Crash to desk top

### ISSUE THREAD

**Issue by Tyrantin** [simeonradivoev/MatterOverdrive#674]
[crash-2017-03-29_11.00.44-client.txt](https://github.com/simeonradivoev/MatterOverdrive/files/887079/crash-2017-03-29_11.00.44-client.txt)

**Comment by Muirrum** [comment]
Can you give us some form of information as to what you were doing at the time?

**Comment by shadowfacts** [comment]
Duplicate of #636. This is an issue that you yourself reported, don't report stuff multiple times.
