### ISSUE TITLE
Arcana_rpg and MatterOverdrive

### ISSUE THREAD

**Issue by LarsdeHaan** [simeonradivoev/MatterOverdrive#676]
i used youre mod inside my modpack but MatterOverdrive crashes when i put it in the same modpack as Arcana_rpg.

this is the crash report could you tell me whats wrong, our could you make a new 1.7.10 version were i can put the mods together.

crash report: https://gist.github.com/LarsdeHaan/2ab9dc89ccb352899fdf23e6d7e441ab

**Comment by Muirrum** [comment]
1.7.10 is no longer supported, please upgrade to a newer version.

**Comment by LarsdeHaan** [comment]
the problem is that i cant make a modpack in a newer version because i have got 166 mods inside the modpack

**Comment by LarsdeHaan** [comment]
and a lot of the mods are not in a newer version
