### ISSUE TITLE
[1.7.10] Temp disabling android features

### ISSUE THREAD

**Issue by IdanHo** [simeonradivoev/MatterOverdrive#683]
Hey, I'm making a capture the flag mod, for my friend's server, but it also has this mod installed, and its kinda unfair that some people have the android features while others dont while playing, so i wonered, how can i disable the features temporarily while they are ingame?

**Comment by simeonradivoev** [comment]
Unfortunately there isn't a way to do that as of now.

**Comment by IdanHo** [comment]
@simeonradivoev so i cant like import the mod to the class path of the project and like set their android level some how?

**Comment by simeonradivoev** [comment]
You can use a command to remove all their learned android abilities.

**Comment by IdanHo** [comment]
@simeonradivoev but i dont want to do it by command, i want the mod im writing to do it.

**Comment by IdanHo** [comment]
i also want to restore them after

**Comment by Muirrum** [comment]
1.7.10 is no longer supported. Please upgrade to a supported version.
