### ISSUE TITLE
[1.10.2] Crash with Mipmaps 

### ISSUE THREAD

**Issue by MokahTGS** [simeonradivoev/MatterOverdrive#684]
Getting a crash trying to load up the 0.5.1 version:

https://pastebin.com/xMAJHk5A

**Comment by andr9528** [comment]
having the same issues, it accured after i installed extra utilities 2, works fine without extra utilities 2 tho

**Comment by Muirrum** [comment]
This issue has been reported around 5 times now. Please make an effort to search the issue tracker for your error instead of immediately opening a new issue.

**Comment by andr9528** [comment]
i just commented on the first one i saw, Any clue when a version without this issue is out to the public?

**Comment by Muirrum** [comment]
We are working on it, but opening new issues does not make us go faster.

**Comment by MokahTGS** [comment]
I did search.  Didnt see it.  If you link the first issue i will close this

**Comment by Muirrum** [comment]
Issue #631 , about 5-7 lines down from this one.
