### ISSUE TITLE
Crash between Matter Overdrive and The Bettwenlands

### ISSUE THREAD

**Issue by LuxerIThink** [simeonradivoev/MatterOverdrive#686]
I have a problem with modpack, between two mods: The Betweenlands and Matter Overdrive. Can you see on this pastebin and help me with solve this error.
https://pastebin.com/FdTXiuBD

How I know, that is crash between Matter Overdrive and The Bettwenlands:
I created modpack, which on start have The Betweenlands. When I add Matter Overdrive and Matter Overdrive core mods (Tesla and ShadowMC), modpack won't work. After that event I tested modpack which have only The Betweenlands, Mater Overdrive, Tesla, ShadowMC and crash is the same. At the end I tested The Betweenlands with Tesla and ShadowMC without Matter Overdrive and It's working. From logic, that is a crash between The Betweenlands and Matter Overdrive.

**Comment by jtrent238** [comment]
They are having a texture conflict.

**Comment by LuxerIThink** [comment]
The creators of The Betweenland fixed this

**Comment by darthvader45** [comment]
If so, please close this issue unless there's a new conflict.
