### ISSUE TITLE
Crash when placing a gravitational stabilizer next to an anomaly

### ISSUE THREAD

**Issue by darthvader45** [simeonradivoev/MatterOverdrive#687]
What happens: crashes straight away.

How to reproduce: Place gravitational stabilizer next to a gravitational anomaly.

Mods used: Just MO and any requirements.

**Comment by Muirrum** [comment]
What game version?
What mod version?

**Comment by darthvader45** [comment]
0.5.1 for 1.10.2

**Comment by Muirrum** [comment]
Fairly certain this is fixed in newest version, I don't get this crash.

**Comment by darthvader45** [comment]
Okay thanks.

**Comment by darthvader45** [comment]
Wait, where is the newest version?  Not on CurseForge, afaik.
