### ISSUE TITLE
[1.10.2] [0.5.1] Crash when looking at a Mad Scientist villager

### ISSUE THREAD

**Issue by cybercat5555** [simeonradivoev/MatterOverdrive#689]
Exactly what it sounds like. I looked at a MO villager, then I crashed. If it helps, I'm an android and I have WAILA 1.7.0-B3_1.9.4

Crash: https://pastebin.com/Ln8aMMDq

**Comment by Muirrum** [comment]
I'll look at it tomorrow

**Comment by Muirrum** [comment]
You're running a multiplayer server?

**Comment by cybercat5555** [comment]
Nope, single player. Not a LAN or anything

**Comment by Muirrum** [comment]
@cybercat5555 Fixed in newest version.
