### ISSUE TITLE
Can't build MatterOverdrive

### ISSUE THREAD

**Issue by ykwdavid** [simeonradivoev/MatterOverdrive#691]
i crash when someone eat near me,i know you already fix this problem,but there are no build with that fixing.I try to build it but failed.
log:https://pastebin.com/7criWUuf

**Comment by Muirrum** [comment]
I'll verify this when I get home.

**Comment by SynexWolf** [comment]
I have also tried to build it, I got the same error.

**Comment by PENGUINLIONG** [comment]
It seems to be Java's safety check. Try remove `throws IOException` [here](https://github.com/simeonradivoev/MatterOverdrive/blob/1.10.2/src/main/java/matteroverdrive/entity/EntityDrone.java#L49) and see if it's fixed?

**Comment by Muirrum** [comment]
Wait, what? This went from a crash when someone eats to a build issue.

**Comment by Muirrum** [comment]
Builds for me.
