### ISSUE TITLE
Portable Decomposer doesn't work?

### ISSUE THREAD

**Issue by Jacob345k** [simeonradivoev/MatterOverdrive#693]
So i have a decomposer in my inventory and it's charged and everything, and it is set to stone, but it will not devour my stone and make matter plasma.
![javaw_2017-06-09_12-55-22](https://user-images.githubusercontent.com/25356889/26987872-c75bd69a-4d12-11e7-9314-6f13b5422318.png)

**Comment by Jacob345k** [comment]
Bump

**Comment by Muirrum** [comment]
Please don't bump

**Comment by Jacob345k** [comment]
Why not? this is like a serious mod problem if one of the item's doesn't even work

**Comment by Muirrum** [comment]
I'm asking you not to bump because I don't want emails popping up every time you say the word "bump"
In addition to that, is this with Minecraft Version 1.10.2?

**Comment by Muirrum** [comment]
Closed due to lack of response from author.
