### ISSUE TITLE
This is a bug

### ISSUE THREAD

**Issue by kuolemax** [simeonradivoev/MatterOverdrive#696]
When minefantasyII is used together with MatterOverdiver, Enderman can not be attacked!

**Comment by LoverHZ** [comment]
When minefantasyII is used together with MatterOverdiver, Enderman can not be attacked!

**Comment by Muirrum** [comment]
What *is* minefantasyII?

**Comment by ETStareak** [comment]
hahahhahah,that's a goodquestion.It's a mod which changed many systems of MC,a great acient like mod.
It might becausr our weapons can't hit ender mobs.I think you can make a config that could allow phraser hit ender mobs.

**Comment by kuolemax** [comment]
@Dev-Osmium This is a very interesting mod，this is its web site on curseforge https://minecraft.curseforge.com/projects/minefantasy2

**Comment by Muirrum** [comment]
Well, one of the enderman mechanics is that they can't be hit with projectiles.

**Comment by Muirrum** [comment]
I don't see a reason this should be added in, as Endermen are not supposed to be able to be hit with projectiles.
