### ISSUE TITLE
 [1.10.2] Conflict with Tough As Nails mod

### ISSUE THREAD

**Issue by Dfox444** [simeonradivoev/MatterOverdrive#698]
So basically whenever you turn into an android with that mod on then turn back into a human, it basically breaks the hydration system with Tough As Nails and you still don't have to worry about drinking water, i'm not too sure if it messes up the temperature or anything else like that.

**Comment by Muirrum** [comment]
ToughAsNails Version?

**Comment by Muirrum** [comment]
Closing due to lack of response from author.
