### ISSUE TITLE
Missing unknown Mod

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [simeonradivoev/MatterOverdrive#699]
[http://imgur.com/iJbFd8Q](http://imgur.com/iJbFd8Q)

modpack: [https://github.com/Arkyo/BigBangMods/tree/1.10.2-v0.5](https://github.com/Arkyo/BigBangMods/tree/1.10.2-v0.5)

**Comment by Muirrum** [comment]
Updated link to work.

**Comment by Muirrum** [comment]
OP, you are missing the Tesla mod.

**Comment by Pythonic-Rainbow** [comment]
I do
https://imgur.com/a/j51fj

**Comment by Muirrum** [comment]
There's no image there. Additionally, that GitHub doesn't exist.
