### ISSUE TITLE
[1.10.2] Is there a fix to this issue?

### ISSUE THREAD

**Issue by xXJamieXx** [simeonradivoev/MatterOverdrive#700]
Hi!

So I noticed that issue #657 addressed a crash that was being caused randomly and this was closed a few months ago. I just wondered if a build had been published with this issue fixed and if so where?

Thanks!

**Comment by Jacob345k** [comment]
i too would like to know about this

**Comment by Muirrum** [comment]
We are currently experiencing issues building the mod. Please stand by.

**Comment by Jacob345k** [comment]
Helpfull hint, after testing with this, it seems the crash is caused by another player eating in the rendered area that the player that recieves the crash.
