### ISSUE TITLE
Possible conflict with Voxel Minimap & Liteloader

### ISSUE THREAD

**Issue by Gamerbolts** [simeonradivoev/MatterOverdrive#701]
Hi I am creating a modpack and have been having an issue. Occasionally when I am on or one of my testers is on Minecraft will just start flashing, all the HUDs and I can still right click and hear things breaking or the menu being clicked but it's unplayable because of the flashing, It's taken me awhile but I finally caught this in my log https://pastebin.com/kEyLxAkv

It's not a crash report because Minecraft isn't crashing, I have to manually close it. I was going to try an get the fml-latest full thing but pastebin said I reached the limit. Is there anything you can see from this? It was right after this that I closed Minecraft. Please let me know because this is driving me insane. Thanks!

**Comment by Gamerbolts** [comment]
Hello. I just got this reply from the dev for Voxel Mini Map

yeah probably an interaction of the two.  a nullpointerexception there would likely cause the GUI to flash (opengl state not being reset after trying, and failing, to render a mob to an FBO in order to create an icon). 
The error is happening in MatterOverdrive's code.  Since the mob's icon fails to be created, the next round of icon placement I try to create it again (and get the same same failure).  That'll cause the gui to be wrong until opengl state is reset to the normal state in the next frame (will look like a flash)
I can certainly try to do a better job restoring state in case of a crash in some mod's mob rendering code (stick the restore code in a finally block), but he might want to look into why rendering a mob with a color can cause an NPE

**Comment by Muirrum** [comment]
MC Version, Mod Version

**Comment by Muirrum** [comment]
And link to your modpack

**Comment by Muirrum** [comment]
Closing due to lack of response from author.
