### ISSUE TITLE
[Suggestion] Structure rarely config

### ISSUE THREAD

**Issue by cybercat5555** [simeonradivoev/MatterOverdrive#703]
I've noticed that in 1.10.2-0.5.1, MO's structures spawn much rarer (if they do at all, I have yet to find any, even on a superflat with structures enabled), compared to the latest 1.7.10 version. 

Essentially this would let you configure structures spawn more frequently or more rarely, pretty much what it says on the tin, though possibly whatever the frequency of the 1.7.10 version was could be the default rarely, since it was just enough to add to the world and break up the monotony, but not to the point of being annoying.

**Comment by Muirrum** [comment]
So it turns out that the chance of a building spawning is 0.01f, as referenced in this line:
`public static float BUILDING_SPAWN_CHANCE = 0.01f;`
This will be fixed soon.

**Comment by Muirrum** [comment]
@cybercat5555 Should be fixed now, you just need to build the jar yourself as I deal with this backlog.
