### ISSUE TITLE
[SOLVED]MatterOverdrive and CustomMainMenu problem

### ISSUE THREAD

**Issue by TimeLadyAboutTime** [simeonradivoev/MatterOverdrive#705]
I have a modpack with CustomMainMenu mod, but when I try to install Matter Overdrive all my personalized menu textures goes missing(purple and black squares) and it only happens when I install MatterOverdrive

I don't know if the problem is caused by MatterOverdrive itself or by one of it dependences(ShadowMC/Forgelin/Tesla).

**Comment by TimeLadyAboutTime** [comment]
UPDATE: Already solved

**Comment by shadowfacts** [comment]
What was the solution, for future reference?
