### ISSUE TITLE
Matter Overdrive Crashing Game at Startup

### ISSUE THREAD

**Issue by AMrWhiteGuy** [simeonradivoev/MatterOverdrive#706]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Matter Overdrive (mo)
[crash-2017-07-05_17.33.18-client.txt](https://github.com/simeonradivoev/MatterOverdrive/files/1126326/crash-2017-07-05_17.33.18-client.txt)

**Comment by Muirrum** [comment]
Please use pastebin @AMrWhiteGuy

**Comment by Muirrum** [comment]
Closing due to lack of response from author.
