### ISSUE TITLE
2 hollographic signs next to eachother & hologram projectors

### ISSUE THREAD

**Issue by phospers** [simeonradivoev/MatterOverdrive#707]
Hi, when i place 2 holographic signs next to eachother they pop off from the wall. is this a bug or is there something i should set?
The thing i did was just placing the holographic signs to a wall or on a holographic matrix.
I tried this on both single user mode and multi player mode
Also when i place some hologram projectors somewhere, i cant get near that junk anymore cause it causes to crash when i load that junk. the last thing i only get when i play on my test server.

**Comment by Muirrum** [comment]
Can you provide screenshots and a crash log?

**Comment by phospers** [comment]
The error i got when crashing is added as screenshot.
I checked crashlogs and most of them are the same like, but i added the most recent item and coming back to my orrigional post... is there a known problem with placing the holographic signs?
![unknown](https://user-images.githubusercontent.com/13115081/28169213-ed2ad094-67e1-11e7-82bb-e1c76f448454.png)
[crash-2017-07-12_19.45.09-client.txt](https://github.com/simeonradivoev/MatterOverdrive/files/1145378/crash-2017-07-12_19.45.09-client.txt)

**Comment by Muirrum** [comment]
Thank you, I'll get right on it.

**Comment by Muirrum** [comment]
Can you put your crash log into a Pastebin?

**Comment by Muirrum** [comment]
Also MC Version please.

**Comment by Muirrum** [comment]
Closing due to lack of response from author.
