### ISSUE TITLE
Random Crash in 1.10.2

### ISSUE THREAD

**Issue by Jacob345k** [simeonradivoev/MatterOverdrive#708]
Happens every two to five minutes ingame, i know it's been posted already, but it's still not fixed
[crash-2017-07-15_09.17.06-client.txt](https://github.com/simeonradivoev/MatterOverdrive/files/1150389/crash-2017-07-15_09.17.06-client.txt)

**Comment by Muirrum** [comment]
Instead of making new issues, can you please post on earlier issues, as that tells me that it is a recurring problem faster than having individual issues.
