### ISSUE TITLE
Modpack crashes with Matter Overdrive

### ISSUE THREAD

**Issue by xNifYT** [simeonradivoev/MatterOverdrive#709]
I created my own modpack, when i put Matter Overdrive in it and launch the game it loads up in like 9/10 and crashes.

Minecraft version: 1.10.2
Matter Overdrive version: 0.5.1
Forge version: 12.18.3.2316

Other mods: 
![mods](https://user-images.githubusercontent.com/22347786/28250626-aa032c88-6a6d-11e7-980a-9bf7bff262d6.png)

Crash report:
[https://pastebin.com/f0MA7emZ](https://pastebin.com/f0MA7emZ)

**Comment by Muirrum** [comment]
That's an ExtraUtils bug, try removing ExtraUtils
