### ISSUE TITLE
NPE Crash when Opening Matter Scanner

### ISSUE THREAD

**Issue by Haggle1996** [simeonradivoev/MatterOverdrive#71]
One of the players of my pack is receiving this error when right-clicking on the Matter Scanner.

http://pastebin.com/W8kuyX2Y

Any ideas?

Haggle1996/RevolutionPack#38

**Comment by shadowfacts** [comment]
@simeonradivoev `holo_icons.png` is missing from the `textures/gui` folder, causing the NPE.

**Comment by DorinnB** [comment]
not right clicking but pressing the "C" (default) key to open the GUI of the matter scanner.
