### ISSUE TITLE
Crash when loading game

### ISSUE THREAD

**Issue by matyklug** [simeonradivoev/MatterOverdrive#710]
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Matter Overdrive (mo)
Caused by: net.minecraft.util.ReportedException: Registering texture

Report:
https://pastebin.com/akc7s7cz

**Comment by erics465** [comment]
Until this is fixed in the mod, you can workaround this crash by either removing Extra Utilities or Tinker's Construct from your modpack, if you still want to use Matter Overdrive.
