### ISSUE TITLE
Matter Network and (portable) Matter Scanner don't work

### ISSUE THREAD

**Issue by Technorico** [simeonradivoev/MatterOverdrive#711]
I try to analyze a block with the (portable) matter scanner, but nothing happens, so I try it with the analyzer and it works, but then when I connect them all on the network (also the cables all have bugged textures), I can not Send the request from the panel because it does not show me the items I've scanned

I am using minecraft 1.10.2

Sorry for terrible English, but I'm not native speaker

**Comment by Muirrum** [comment]
#652 

Closing
