### ISSUE TITLE
Some items in the menu don't have xp values, also player speed doesn't reflect non-matter overdrive speed updgrades

### ISSUE THREAD

**Issue by Jacob345k** [simeonradivoev/MatterOverdrive#713]
When i'm an android in the latest 1.10.2 version, i still get hungry, and thus am unable to sprint, and can die if i don't eat.

**Comment by Jacob345k** [comment]
I also still need oxygen underwater and in space.

**Comment by Jacob345k** [comment]
NEVERMIND I FIGURED IT OUT BUT SEPERATE ISSUE i cannot see how much xp things cost in the menu

**Comment by Muirrum** [comment]
What menu?
