### ISSUE TITLE
Crash upon looking at a Mad Scientist in 1.10.2

### ISSUE THREAD

**Issue by Jacob345k** [simeonradivoev/MatterOverdrive#717]
[crash-2017-08-01_17.22.14-client.txt](https://github.com/simeonradivoev/MatterOverdrive/files/1192114/crash-2017-08-01_17.22.14-client.txt)
[crash-2017-08-01_17.16.08-client.txt](https://github.com/simeonradivoev/MatterOverdrive/files/1192115/crash-2017-08-01_17.16.08-client.txt)

**Comment by Muirrum** [comment]
Can you please use pastebin?

**Comment by Muirrum** [comment]
Closed due to lack of response from the author.
