### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by craig1988** [simeonradivoev/MatterOverdrive#719]
Seems to be a problem with new galactic craft core causes crash

**Comment by erics465** [comment]
Can you provide a crash report, please? You can upload it to https://pastebin.com/ and share the link here.

**Comment by craig1988** [comment]
Iv tried but the crash report of far to big for my computer to even handle I can't copy it it like 13000 long

**Comment by ETStareak** [comment]
Can't you upload your txt correctly?Why use COPY?

**Comment by craig1988** [comment]
[2017-08-07-5.log.gz](https://github.com/simeonradivoev/MatterOverdrive/files/1205329/2017-08-07-5.log.gz)

**Comment by craig1988** [comment]
this is the log its to long for paste bin and its to long for GitHub

**Comment by craig1988** [comment]
I hope iv provided all the necessary information I really want to use matter over drive in my pack its such a cool mod

**Comment by craig1988** [comment]
Here is a more reliable source for the crash log https://gist.github.com/Ri5ux/d1b055f966d4178f78b7143830ad372c

**Comment by craig1988** [comment]
Did you mange to see this crash log ?

**Comment by Muirrum** [comment]
That's not a crash report. That's an error log.

**Comment by craig1988** [comment]
Sorry my bad It's a crash with the new version of galactic craft it just refuses to start the game with MO installed when theses 2 mods are in a pack. I don't want to cause the crash again as it destroys my whole world. Would be great if you could look at it thanks

**Comment by Muirrum** [comment]
That's not a crash report. A Crash report looks like this: https://pastebin.com/8213wwDQ

**Comment by Muirrum** [comment]
Also MC Version please?

**Comment by craig1988** [comment]
I understand that that's not a crash report that was my bad sorry what I was saying above was that I don't want to create the crash again to get the crash report as it completly screwed up my minecraft last time. But I was also apologising for not providing a crash report. MC version is 1.10.2

**Comment by Muirrum** [comment]
You should be able to find a .txt file in your .minecraft/crash-reports folder which you can put on Pastebin/Hastebin and is an actual crash report

**Comment by Muirrum** [comment]
Closing due to lack of response from author
