### ISSUE TITLE
Server crash on Pre Initialization 

### ISSUE THREAD

**Issue by mattrock93** [simeonradivoev/MatterOverdrive#72]
Mod works in single player but crashes when trying to launch a server

Crash Report: http://pastebin.com/MTLZ2KqT

**Comment by Whenlifedies** [comment]
Ahh, I guess this fix hasn't been compiled into Beta 0.4.0-RC1 as of yet?
Still having the exact same crash log from this version.

**Comment by simeonradivoev** [comment]
nope it has not
