### ISSUE TITLE
crash with galatic craft core updated crash log 

### ISSUE THREAD

**Issue by craig1988** [simeonradivoev/MatterOverdrive#720]
Here is a more reliable source for the crash log https://gist.github.com/Ri5ux/d1b055f966d4178f78b7143830ad372c

**Comment by craig1988** [comment]
Update to this crash it works with pervious versions of galactic craft just not the most recent

**Comment by Muirrum** [comment]
Alright.

**Comment by craig1988** [comment]
Why is this issue been closed has it been resolved ?
