### ISSUE TITLE
[1.12.1] extrautils2-1.12-1.6 mod conflict TConstruct-1.12-2.7.2.19

### ISSUE THREAD

**Issue by Grotts** [simeonradivoev/MatterOverdrive#723]
I apologize if this has been posted already, I searched a bit and found some older posts of the same issue, this is with 1.12.1 version.

[crash-2017-09-01_20.00.24-server.txt](https://github.com/simeonradivoev/MatterOverdrive/files/1271803/crash-2017-09-01_20.00.24-server.txt)

If I knew how to read the crash log better, I would try to explain what I think is going on, but i'll leave it to the pro's.  If this needs to be reported to TConstruct also, please advise and I will make a post there also.

**Comment by Muirrum** [comment]
We don't have a 1.12.1 version...

**Comment by Muirrum** [comment]
This isn't related to MO.
