### ISSUE TITLE
Crash When Drinking Milk

### ISSUE THREAD

**Issue by cybercat5555** [simeonradivoev/MatterOverdrive#724]
Self-explanatory, the game crashes when you drink milk, However, when you re-enter the world, the milk becomes a bucket like normal

https://pastebin.com/8213wwDQ

**Comment by Muirrum** [comment]
MC version, mod version...

On Fri, Sep 15, 2017, 12:25 AM cybercat5555 <notifications@github.com>
wrote:

Edit: Email replies are annoying

**Comment by cybercat5555** [comment]
Whoops, sorry
MC 1.10.2
Matter Overdrive 1.10.2-0.5.1
ShadowMC 1.10.2-3.6.1
Tesla 1.10.2-1.2.1.49

**Comment by Muirrum** [comment]
Thanks.

**Comment by Muirrum** [comment]
`matteroverdrive.handler.BucketHandler.onBucketFill(BucketHandler.java:46)`
doesn't appear to exist. I may be missing something, but I don't know.

**Comment by Muirrum** [comment]
And doesn't cause a crash for me.
https://gyazo.com/ab9da82b186cb6d73487809d49c42926
