### ISSUE TITLE
development

### ISSUE THREAD

**Issue by OmegaRogue** [simeonradivoev/MatterOverdrive#727]
is this still being developed?

**Comment by Muirrum** [comment]
Yes

**Comment by OmegaRogue** [comment]
cool

**Comment by OmegaRogue** [comment]
when is the next version gonna be released for 1.7.10 and is it gonna be more stable?

**Comment by Muirrum** [comment]
1.7.10 has not been supported since before I took over the project.

**Comment by OmegaRogue** [comment]
but there is a 1.7.10 version

**Comment by OmegaRogue** [comment]
can you continue it for 1.7.10?

**Comment by Muirrum** [comment]
No

**Comment by OmegaRogue** [comment]
why not?

**Comment by OmegaRogue** [comment]
could i continue the 1.7.10 version?

**Comment by Muirrum** [comment]
If you like

**Comment by OmegaRogue** [comment]
Ok, then ill start learning modding
