### ISSUE TITLE
Crash relating to "render.RenderWeaponsBeam" and consuming items on a server

### ISSUE THREAD

**Issue by cybercat5555** [simeonradivoev/MatterOverdrive#735]
According to the people who sent me the crash, when they try to consume any items (foods, potions, etc, though placed cakes are fine) while close to each other, they get this crash: https://pastebin.com/NGgmbSeg
Apparently when one person eats it causes the other to crash and vice versa, and its on a server

MO 0.5.1
Shadowfacts Forgelin 1.5.1
ShadowMC 3.6.1
Tesla 1.2.1.49

**Comment by cybercat5555** [comment]
Adding to this, I think build 0.5.2 may have fixed it

**Comment by Muirrum** [comment]
So then close it.
