### ISSUE TITLE
Crash without ComputerCraft

### ISSUE THREAD

**Issue by Gideonseymour** [simeonradivoev/MatterOverdrive#74]
http://paste.feed-the-beast.com/view/e581474d

**Comment by simeonradivoev** [comment]
Fixed in 3c55c5035235ef7a853dcf61fd62d8336be93493

**Comment by TheVizzy** [comment]
@simeonradivoev why my client crash with new version MO

**Comment by simeonradivoev** [comment]
The fix has not been build yet.
