### ISSUE TITLE
Player head renders at the angle of the head in the world

### ISSUE THREAD

**Issue by shadowfacts** [simeonradivoev/MatterOverdrive#76]
Should render facing straight

**Comment by shadowfacts** [comment]
Hmm... I'm not sure there is anything we can do about this without creating a custom Entity and a custom renderer.

**Comment by simeonradivoev** [comment]
Isn't there a head angle in the player entity ? We can change it only when rendering the player and then changing it back.

**Comment by shadowfacts** [comment]
Hmm... That would work, but it would look weird for any other players. Unless there's a way we could prevent it from syncing to the server...

**Comment by simeonradivoev** [comment]
Fixed in 7a4a2ba5983e5d4b6df84c19436362fadda58474
