### ISSUE TITLE
Issue with KCauldron 1481.144 

### ISSUE THREAD

**Issue by Udosa** [simeonradivoev/MatterOverdrive#78]
Crash your mod when server start up 
http://pastebin.com/8QhTm0mt

**Comment by shadowfacts** [comment]
What version of Java are you using?

**Comment by Haggle1996** [comment]
I get a similar crash with ForgeEssentials beta 8 instead of kcauldron. http://pastebin.com/dsp0yyPL

Works fine in single player -- crashes only when run as a server.

Java 7 on my server. Client is Java 8.

**Comment by shadowfacts** [comment]
Nether KCauldron nor ForgeEssentials are causing issues. **Java 8 is a requirement for Matter Overdrive.**

**Comment by Udosa** [comment]
I test on java 7 and 8 , and get crash two times

**Comment by Udosa** [comment]
And all information about version java and other in crash report on pastebin -_-

**Comment by simeonradivoev** [comment]
it says Java Version: 1.7.0_72 can you post the java 8 error.

**Comment by Udosa** [comment]
http://pastebin.com/vaFfchJZ
Java 1.8.0_45

**Comment by shadowfacts** [comment]
Try starting your server with version 0.4.0-RC1 HOTFIX 3

**Comment by Badcholo** [comment]
Try updating CoFH Core the newest version is CoFHCore-[1.7.10]3.0.3-303.jar.
 but i think it requieres forge 1488 min. maybe.

**Comment by Badcholo** [comment]
why not update forge to 1492, i have Kcauldron 1492 and it works just fine with the latest CoFH Core.
Mojangsters Modpack Technic launcher.
