### ISSUE TITLE
Crash when ComputerCraft is missing

### ISSUE THREAD

**Issue by Exuraz** [simeonradivoev/MatterOverdrive#79]
Hi, 

So I switched out ComputerCraft with OpenComputers today and Matter Overdrive caused a crash because it was unable to find a ComputerCraft class. Or well, that's what I understood from the crash report. 

Crash report: http://pastebin.com/VAQkWn19
Matter Overdrive version: 0.4.0-RC1
Forge: 1448

The crash is unrelated to OpenComputers being present. 
Tried resetting the configs and registry file but it didn't seem to fix it.

**Comment by simeonradivoev** [comment]
Fixed in 3c55c5035235ef7a853dcf61fd62d8336be93493
