### ISSUE TITLE
Power

### ISSUE THREAD

**Issue by Gideonseymour** [simeonradivoev/MatterOverdrive#8]
Alright, I've only got a few issues left, and these are minor.

Primarily, I'm not certain how you charge a Phaser - it starts with no power, regardless of if you craft it with a full battery. From there, I don't know where to charge it :P 
![image](https://cloud.githubusercontent.com/assets/2879999/7329917/ca820788-eaa2-11e4-8fbd-1f41c718492a.png)

And on the subject of batteries, they start out with a full charge. I'm assuming that's not your intention?
![image](https://cloud.githubusercontent.com/assets/2879999/7329923/dc91e40c-eaa2-11e4-8ac8-01c163b8fc94.png)

**Comment by simeonradivoev** [comment]
Actually the battery is intended to start with a full charge.
As the second one, seems to be a bug. A one line bug.
