### ISSUE TITLE
Crashes upon startup

### ISSUE THREAD

**Issue by Linkinexe** [simeonradivoev/MatterOverdrive#80]
Upon startup the game crashes when loading the mod in a modpack.
http://pastebin.com/5KcBq1rd

And when creating a new instance with Matter Overdrive alone it still crashes but apparently for different reasons.
http://pastebin.com/59Nwm6jm

**Comment by simeonradivoev** [comment]
the bug was fixed in 3c55c5035235ef7a853dcf61fd62d8336be93493. It happens because of missing Computercraft and Waila.
