### ISSUE TITLE
TileEntityMachineTransporter class not found

### ISSUE THREAD

**Issue by Ganjalf-Amsterdoom** [simeonradivoev/MatterOverdrive#84]
Hello,

when I load the mod I get this crash:

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: matteroverdrive/tile/TileEntityMachineTransporter

I have CoFHlib 1.0.3, am I missing something else?

Thank you for your time.

**Comment by b0bst3r** [comment]
No you aren't missing anything apart from a build with the fixed code in :)

**Comment by simeonradivoev** [comment]
Fixed in 3c55c5035235ef7a853dcf61fd62d8336be93493

**Comment by Ganjalf-Amsterdoom** [comment]
Thank you very much, ETA on the release of the fixed build?

**Comment by shadowfacts** [comment]
I've just released a hot-fix to [Curse](http://www.curse.com/mc-mods/minecraft/229694-matter-overdrive).

**Comment by Ganjalf-Amsterdoom** [comment]
Thank you very much, I'll wait that it shows up in curse. q^c^p
