### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by RedsaphirCZ** [simeonradivoev/MatterOverdrive#87]
Probably hard dependency on Computercraft?
0.3.5 is fine

crashlog: http://pastebin.com/dyc7ec1C

**Comment by simeonradivoev** [comment]
what version ?

**Comment by shadowfacts** [comment]
Try using the latest version from Curse (0.4.0-RC1 HOTFIX 2), that *should* have fuze any problems.

**Comment by RedsaphirCZ** [comment]
It was Hotfix, Hotfix 2 is probably not available yet, i will test it once Curse will publish it :)

**Comment by b0bst3r** [comment]
Yeah keeping an eye out for this too but it's not showing up on Curse

**Comment by shadowfacts** [comment]
Oops, something. Went wrong when I uploaded it to Curse. Will re-upload when I return home.
