### ISSUE TITLE
Computercraft dependency

### ISSUE THREAD

**Issue by Ganjalf-Amsterdoom** [simeonradivoev/MatterOverdrive#89]
Hello,

is computercraft a dependency to run matter overdrive? Could we expect in the future a release without CC as hard dependency?

Thank you for your time.

**Comment by simeonradivoev** [comment]
It's not a dependency. The bug that has missing computercraft functions is fixed.

**Comment by shadowfacts** [comment]
1. No
2. Yes, it's been uploaded to Curse and is pending approval.
3. **Please look at existing issues before posting a new one.**

**Comment by Ganjalf-Amsterdoom** [comment]
My bad, pardon me I checked open issues and not closed one, my fault. No need to stress. q^c^p
