### ISSUE TITLE
Server Crash with latest version

### ISSUE THREAD

**Issue by PhoenixSmith** [simeonradivoev/MatterOverdrive#93]
Pastebin-

http://pastebin.com/5zcnjmVb

1.7.10 server with latest version. Definetly MO causing the crash. Great mod btw. :)

**Comment by shadowfacts** [comment]
Cannot reproduce, try with 0.4.0-RC1 HOTFIX 3 from CurseForge.

**Comment by Ganjalf-Amsterdoom** [comment]
I have the same crash.

Install forge as a server with --installServer, possibly on a linux box.

**Comment by shadowfacts** [comment]
@Ganjalf-Amsterdoom Are you usg 0.4.0-RC1 HOTFIX 3?

**Comment by Ganjalf-Amsterdoom** [comment]
my bad shadow, its java  7, updating to java 8 fixed my issue. Pardon to have bothered.
