### ISSUE TITLE
Crash in starting minecraft

### ISSUE THREAD

**Issue by xXDerMCFreakXx** [simeonradivoev/MatterOverdrive#98]
When i start minecraft, it crashes!
It says anythink like No such class found: matteroverdrive: Matteroverdrive 
If u want more info of the crash report say it to me. Please help i really love that mod! Sorry for bad english im a bulgarian

**Comment by shadowfacts** [comment]
Modpack? Version? Crash report? I see none of these. Without this information we are unable to resolve your problem.

**Comment by xXDerMCFreakXx** [comment]
Im gonna give more info tomorrow

**Comment by TheVizzy** [comment]
kek!

**Comment by xXDerMCFreakXx** [comment]
I know that the other mods are not the problem cuz i tried to play only with cofhlib and Matteroverdrive but it crashes with same reason like crashing with other mods

**Comment by levicc00123** [comment]
I too am having the same issue, here's a full crash report.
https://gist.github.com/levicc00123/07fae1554856bc865942

**Comment by xXDerMCFreakXx** [comment]
levicc i have the same crash report but my one cant find in matteroverdrive the matteroverdrive class

**Comment by xXDerMCFreakXx** [comment]
So the first letter of the Crash Report is
cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: matteroverdrive/Matteroverdrive
Hope that will help

**Comment by xXDerMCFreakXx** [comment]
I cant give the full crash report for a long reason

**Comment by xXDerMCFreakXx** [comment]
oh wait i have the crash report.
Here is it: https://gist.github.com/xXDerMCFreakXx/f43665614413c3161344

**Comment by xXDerMCFreakXx** [comment]
Ummmmm guys? I have a crash report uploadet if you scroll up... Can u contiune with the helping?

**Comment by simeonradivoev** [comment]
@levicc00123 You have a COmputercraft missing crash that was fixed in the hotfix.
@xXDerMCFreakXx you have Java 7 whitch is no longer supported by Matter Overdrive. You need to update to Java 8. Дори и създателите на Java вече са спрели помощи за версия 7.
