### ISSUE TITLE
Matter Overdrive doesn't save registered matter from addons

### ISSUE THREAD

**Issue by Master0r0** [simeonradivoev/MatterOverdrive#99]
I have been working on an addon just to add some of the recipe handlers for Botania and maybe other mods with special crafting systems, the mod tells me that it has registered the items (http://pastebin.com/7s1s255k) however after loading a world it does not show on the item.

The only item it actually has registered the value for is the mysticFlowerWhite

Any Ideas?

**Comment by simeonradivoev** [comment]
Try and delete the reg file in config/MatterOverdrive

**Comment by Master0r0** [comment]
That fixed it thanks
